### ISSUE TITLE
Railroad tracks

### ISSUE THREAD

**Issue by 1ec5** [ZeLonewolf/openstreetmap-americana#101]
Maps published in the U.S. conventionally give railroad tracks a different appearance than European-influenced maps such as openstreetmap-carto. While the railroad ties we’re familiar with may seem kitschy, they are less likely to be confused with roads than the European approach of an alternating fill inside a casing, since the latter treatment is used for secondary roads in American topographic maps and either roads under construction or all-weather roads in general-purpose American road maps.

Here’s a comparison of map legends from [_How to Lie with Maps, Third Edition_](https://books.google.com/books?id=MwdRDwAAQBAJ&pg=PA141):

[![Screenshot-2022-1-26 How to Lie with Maps, Third Edition](https://user-images.githubusercontent.com/1231218/151245719-a1442b81-2857-4837-bb4a-4c1231d8e198.png)](https://books.google.com/books?id=MwdRDwAAQBAJ&pg=PA141)

Some highlights from maps in my collection that depict railroad tracks:

* Official state maps from Ohio, Oregon, Texas, and Washington only show Amtrak passenger routes, which might be a reasonable option at certain zoom levels to avoid distracting from roads that have a similar line width.
* Pennsylvania makes the line thicker for Amtrak routes.
* North Carolina describes it as “rail corridors”, which probably means spurs are excluded.
* Georgia gives MARTA commuter rail lines a very different appearance: a red line without ties.
* Illinois omits railroad tracks “in congested areas”, relegating them to map insets.
* Pennsylvania and Louisiana color railroad tracks red.
* A map of San Mateo County, California, by Compass Maps distinguishes BART (thick dotted line) from Caltrain (thick solid line).
* Connecticut spaces out the ties and makes them relatively large.

<img src="https://user-images.githubusercontent.com/1231218/151246473-466d42a9-a564-45a4-9bb5-bdbe8b85c734.jpg" width="250" alt="Wyoming DOT 2010"> <img src="https://user-images.githubusercontent.com/1231218/151246631-abe79068-6ba7-4445-98a7-0e2ee552fa0d.jpg" width="250" alt="Rand McNally Manhattan 1991 street map">
<img src="https://user-images.githubusercontent.com/1231218/151246736-bcbc4b03-546a-4e21-b7de-b85ae600b637.jpg" width="250" alt="Nevada DOT"> <img src="https://user-images.githubusercontent.com/1231218/151246798-5d2bd508-94d6-47a8-990e-ee1aa1e38e44.jpg" width="250" alt="Oklahoma DOT"> <img src="https://user-images.githubusercontent.com/1231218/151246910-0aca2cff-3f11-4696-8581-7ed181d9ac02.jpg" width="250" alt="Kansas DOT 2009–2010"> <img src="https://user-images.githubusercontent.com/1231218/151246974-9652f088-0bd1-4368-8cf1-28f7146df78a.jpg" width="250" alt="KYTC"> <img src="https://user-images.githubusercontent.com/1231218/151247123-82cfe81f-9b15-4ecf-a4c8-58ab9b19948d.jpg" width="250" alt="West Virginia DOT"> <img src="https://user-images.githubusercontent.com/1231218/151247186-5c5ab75f-3e17-4468-8f3d-1121f9e6c13e.jpg" width="250" alt="Tennessee DOT 2005"> <img src="https://user-images.githubusercontent.com/1231218/151247275-6ea8b1d2-4716-4262-8cf3-b8f65adf9653.jpg" width="250" alt="Texas DOT 2016"> <img src="https://user-images.githubusercontent.com/1231218/151247585-1878917d-ad53-4b8d-a5d3-eff2dd21d039.jpg" width="250" alt="Ohio DOT"> <img src="https://user-images.githubusercontent.com/1231218/151247856-b4eed1e2-7f97-47ac-946e-c2cb3a232cbd.jpg" width="250" alt="North Carolina DOT 2005"> <img src="https://user-images.githubusercontent.com/1231218/151248197-ea33fd57-a002-4481-854c-48f1fecfd455.jpg" width="250" alt="Illinois DOT 2005–2006"> <img src="https://user-images.githubusercontent.com/1231218/151248296-734a4192-2d6e-4616-8aed-404a3d6429bc.jpg" width="250" alt="Seeger Cincinnati 1991"> <img src="https://user-images.githubusercontent.com/1231218/151248365-d68df97d-f4f3-4f26-a410-528fe52ca487.jpg" width="250" alt="Rand McNally Atlanta 2000">
<img src="https://user-images.githubusercontent.com/1231218/151248615-c5671fed-529b-47bb-8cce-2ce3ebd1cf9c.jpg" width="250" alt="Compass San Mateo County 2004"> <img src="https://user-images.githubusercontent.com/1231218/151248869-52a69ae1-fdc7-4806-8317-7d1c78a0b893.jpg" width="250" alt="Pennsylvania DOT 2003"> <img src="https://user-images.githubusercontent.com/1231218/151249001-e6baa088-d418-4316-a6b2-3af726b856ac.jpg" width="250" alt="Connecticut DOT 2004–2005">

<img src="https://user-images.githubusercontent.com/1231218/151246260-a9a89f72-02fc-4df4-81b8-7355c31c109e.jpg" width="250" alt="Oklahoma agritourism"> <img src="https://user-images.githubusercontent.com/1231218/151247028-f03758f3-39fe-4fc5-a460-3080bb610275.jpg" width="250" alt="Louisiana DOTD 2010"> <img src="https://user-images.githubusercontent.com/1231218/151247422-bb27816a-f0e8-4aa1-929a-c5267a597156.jpg" width="250" alt="Oregon DOT"> <img src="https://user-images.githubusercontent.com/1231218/151247500-e60e0a05-aed1-4d78-9ef7-eb185b6f67f4.jpg" width="250" alt="Washington DOT 2008–2009"> <img src="https://user-images.githubusercontent.com/1231218/151247661-5ff3daed-c5e0-4c4f-9ef8-5c08f51ec24d.jpg" width="250" alt="AHTD 2012"> <img src="https://user-images.githubusercontent.com/1231218/151247754-f86ded44-d89a-4cbd-8921-c773d450b3d3.jpg" width="250" alt="South Carolina DOT 2005"> <img src="https://user-images.githubusercontent.com/1231218/151248051-aee21af6-bad2-4ca8-ad2d-d5365b978965.jpg" width="250" alt="Georgia DOT 2005–2006"> <img src="https://user-images.githubusercontent.com/1231218/151249099-f9684e0c-1e6d-4b7a-b854-b7e03bdf1aa4.jpg" width="250" alt="Montana DOT 2007–2008">

**Comment by wmisener** [comment]
This issue has kind of fallen by the wayside, but I just want to chime in that I think the railroad ties line is definitely the way to go for this style, very American-feeling to me. That would at least seem to work for railway=rail. I think it would even be recognizable for urban passenger rail, although it looks like a lot of your urban maps switch to a more route-based line depiction, with little dots for stations.

**Comment by matkoniecz** [comment]
It is likely very low priority for this style, but display of `railway=tram` would be also nice.

https://zelonewolf.github.io/openstreetmap-americana/#18/50.064828/19.946744 - area with trams and railroad.

**Comment by wmisener** [comment]
Was looking at a city-scale AAA map I had (of San Francisco), and thought their railway rendering choice was interesting for this project: the Caltrain commuter rail line (to the east) is rendered with the "railroad ties" style, befitting its ROW along the former SP main-line and locomotive character. The heavy-rail BART subway and the light-rail Muni Metro are, in contrast, depicted as semi-transparent blue and gray lines (which in this case matches the vehicle colors of the two systems), which are thicker than the streets they run under. Stations get big dots for Muni and Caltrain, but boxes for BART. Where the stations combine (e.g. at Civic Center in the NE of the photo), the symbols are overlaid.
![IMG_7555](https://user-images.githubusercontent.com/58491489/172095207-258a5e80-5d2a-43e0-a978-90383e06fc9b.jpg)
![IMG_7560](https://user-images.githubusercontent.com/58491489/172095327-e35b4a20-8304-4dbf-b47c-cd2871105f32.jpg)
 
This would seem to support the idea that `railway=subway` and `railway=light_rail` might need their own rendering style down the line, though I think adding all railways with the same 'ties' style as a first step would be appropriate, though it might be hard to see if the line runs along or under a street.

**Comment by jeisenbe** [comment]
It will be important to distinuish railway tunnels especially, but also bridges or elevated rail lines, in urban areas.

**Comment by 1ec5** [comment]
The faint lines in https://github.com/ZeLonewolf/openstreetmap-americana/issues/101#issuecomment-1147038226 would be consistent with how we’re already depicting road tunnels with washed-out colors. I see the same effect in this 1991 Rand McNally tourist map of New York City, specifically in the Manhattan inset and Greenwich Village sub-inset, which distinguish between surface and overhead rail in black and subways in gray:

![Greenwich](https://user-images.githubusercontent.com/1231218/172717080-f9f79b90-af79-4c04-9da4-2dab40e8d855.jpg)

**Comment by 1ec5** [comment]
[Railroad tracks under construction](https://www.openstreetmap.org/way/1002727171) are fairly common in OSM. I wonder how the dotted line treatment in #502 would interact with the railroad ties if we were take the same approach with railroad tracks.
