### ISSUE TITLE
Restore z4 park layer

### ISSUE THREAD

**Issue by ZeLonewolf** [ZeLonewolf/openstreetmap-americana#1021]
#1020 removed the park layer from z4 because an upstream change in OpenMapTiles conflated parks and aboriginal lands in a way that prevented us from being able to render them separately (oops).

Once this is fixed upstream, we'll want to add the z4 park layer back.

**Comment by 1ec5** [comment]
The issue was fixed upstream in openmaptiles/openmaptiles#1489 phanecak-maptiler/planetiler-openmaptiles#12.
