### ISSUE TITLE
Obscure bays shown at very low zoom levels due to their famous names

### ISSUE THREAD

**Issue by 1ec5** [ZeLonewolf/openstreetmap-americana#1025]
[Baffin Bay](https://www.openstreetmap.org/relation/13832205) is a 266,000-square-mile bay between Canada and Greenland that most people are used to seeing on a world-scale map. But we don’t show it on the map at low zoom levels. Instead, we show [Baffin Bay](https://www.openstreetmap.org/node/369120359) – a much smaller, [much less significant](https://www.wikidata.org/wiki/Q2905199) bay in Texas – at zoom level 4.

In fact, famous bays are appearing all over the map in places where there happens to be a bay that shares its name:

[![Baffin Bay, Porpoise Bay, Hudson Bay, Porpoise Bay, Cumberland Sound](https://github.com/ZeLonewolf/openstreetmap-americana/assets/1231218/8fa10baf-697a-4284-980a-d75668034f11)](https://zelonewolf.github.io/openstreetmap-americana/#map=5/28.6/-89.38)

I didn’t know there were so many James Bays in the Great Lakes:

![James Bay, James Bay, James Bay, Melville Bay](https://github.com/ZeLonewolf/openstreetmap-americana/assets/1231218/3d704365-1248-4a5a-8683-62b61eef5ee1)

This issue might have the same root cause as #1024, but I opened a separate issue just in case.

**Comment by phanecak-maptiler** [comment]
Relates to https://github.com/openmaptiles/openmaptiles/issues/1595

**Comment by 1ec5** [comment]
This should be fixed once we migrate to the tileset that has the fix for openmaptiles/openmaptiles#1595.

**Comment by 1ec5** [comment]
This appears to be fixed now along with #1024.
