### ISSUE TITLE
Rock County MN doesn't distinguish between CR's and CSAH's

### ISSUE THREAD

**Issue by the-spui-ninja** [ZeLonewolf/openstreetmap-americana#1041]
So per https://www.dot.state.mn.us/maps/gdma/data/maps/county/rock.pdf, there's a nice, defined difference between the CSAH system (normal pentagon) and the CR system (white square). However, in the field, Rock County doesn't distinguish between them (https://www.bing.com/maps?osid=fac4b26f-6bf9-453f-ad51-bf949a2a7d76&cp=43.615358~-96.093568&lvl=15.814454&dir=26.544998&pi=-9.240571&style=x&v=2&sV=2&form=S00027, CSAH to the left, CR to the right).

As such, the US:MN:Rock:CSAH shield should be changed to the white square to match what's in the field. 

This might not be the only county in MN that does this (based on what I remember driving through rural MN), but I don't have a definite answer right now.

**Comment by claysmalley** [comment]
This is a pretty small fix. I'm on vacation right now, but I can get to it later this week.

If you find out about any more Minnesota counties that use the same shields for both networks, let us know.

**Comment by the-spui-ninja** [comment]
Looks like Lincoln uses the pentagons for both: https://www.bing.com/maps/?cp=44.386036%7E-96.425102&lvl=16.1&pi=-2.7&style=x&dir=300.6
https://www.dot.state.mn.us/maps/gdma/data/maps/county/lincoln.pdf
