### ISSUE TITLE
Identify all counties of Minnesota whose shields don't distinguish CSAH and CR

### ISSUE THREAD

**Issue by claysmalley** [ZeLonewolf/openstreetmap-americana#1043]
Tail work from #1041.

All Minnesota counties have a distinction between County State Aid Highways (CSAH; tagged `network=US:MN:<county>:CSAH`) and County Roads (CR; tagged `network=US:MN:<county>:CR`). Typically, CSAHs have blue pentagonal shields and CRs have white square shields. But some counties opt to sign CSAHs and CRs the same, using one of these two designs.

We need to compile a list of counties in Minnesota that have chosen to use solely one shield, and which one. Likewise, if any counties deviate from the typical Minnesota county shield design (e.g. yellow text instead of white), this should be documented as well.

cc @the-spui-ninja

**Comment by 1ec5** [comment]
For reference, the AARoads Wiki recognizes CSAH shields in [these counties](https://wiki.aaroads.com/wiki/Special:PermanentLink/2155#L-123); see the referenced Commons images.

**Comment by the-spui-ninja** [comment]
So looking at that, we're missing
**Faribault
Itasca
Jackson
Kandiyohi
Koochiching
Lake of the Woods
Lyon
Mahnomen
Meeker
Norman
Roseau
Stevens
Swift
Traverse
Wabasha
Wadena
Wilkin**

Need verification:
**Clearwater**
County state-aid highways use the pentagonal shield, others unknown.
**Grant**
County state-aid highways use the pentagonal shield, others unknown.
**Nobles**
County state-aid highways use the pentagonal shield, others unknown.
**Pope**
County state-aid highways use the pentagonal shield, others unknown.
**Red Lake**
County state-aid highways use the pentagonal shield, others unknown.
**Redwood**
County state-aid highways use the pentagonal shield, others unknown. 
**Stearns**
County state-aid highways use the blue pentagonal shield, others use the square one. **Not verified**

I checked from that list:
**Lincoln**
County state-aid highways use the pentagonal shield. Others probably use the square but not sure.
**Yellow Medicine** 
YM uses the pentagons for CSAHs, squares for CRs.

Might be wrong;
**Lac qui Parle**
All county roads use the square shield. - I saw pentagons in LQP while I was looking along the MN/SD border.

**Comment by jumbanho** [comment]
**Fairbault** uses white square for all
**Jackson** uses pentagonal shield for CSAH, white square otherwise
**Lyon** uses white square for all
**Wabasha** uses pentagonal shield for CSAH, white square otherwise

**Comment by claysmalley** [comment]
I've made a [draft PR](https://github.com/ZeLonewolf/openstreetmap-americana/pull/1046/files#diff-21d2ca32bb400fce6149c2ca25ed3366df195a198f357764d46f7ae811835f29) based on the information compiled here. Hoping we can get 100% completion before merging it.

**Comment by jumbanho** [comment]
**Kandiyohi** uses pentagonal shield for all
**Koochiching** uses white square for all
**Lake of the Woods** uses white square for all
**Mahnomen** white square for all
**Meeker** Blue pentagonal for CSAH, white square otherwise
**Norman** Blue pentagonal for CSAH, white square otherwise
**Roseau** Blue pentagonal for CSAH, white square otherwise
**Stephens** Blue pentagonal for CSAH, white square otherwise
**Swift** white square for all
**Traverse** Blue pentagonal for CSAH, white square otherwise
**Wadena** Blue pentagonal for CSAH, don't know for others
**Wilkin** Blue pentagonal for all

**Comment by the-spui-ninja** [comment]
**Lac qui Parle** I believe uses blue pentagons for CSAH (https://www.bing.com/maps/?cp=44.935626%7E-96.414956&lvl=14.4&pi=-7&style=x&dir=224.9)

**Comment by claysmalley** [comment]
**Clearwater**: Blue pentagon CSAH, white square CR
**Fillmore**: Blue pentagon for all
**Grant**: White square for all
**Itasca**: White square for all
**Kittson**: Blue pentagon CSAH, white square CR
**Nobles**: Blue pentagon CSAH, white square CR
**Pope**: Blue pentagon for all
**Red Lake**: Blue pentagon CSAH, white square CR
**Redwood**: Blue pentagon CSAH, white square CR
**Stearns**: Blue pentagon CSAH, white square CR
**Wadena**: Blue pentagon CSAH, white square CR

That covers all the counties. I also identified `network=US:MN:Intercounty` which appears to use a simple blue square with white text and a yellow outline.
