### ISSUE TITLE
Icons for points of interest

### ISSUE THREAD

**Issue by TheAdventurer64** [ZeLonewolf/openstreetmap-americana#128]
Would it be possible to add POI data for the map (restaurants, shops, etc.)?

**Comment by ZeLonewolf** [comment]
Of course.  PRs are welcome for POIs.  Any POIs present in the OpenMapTiles [POI layer](https://openmaptiles.org/schema/#poi) are fair game.

**Comment by zekefarwell** [comment]
We should probably add the rest of the roads too so POIs aren't just hanging out in a random spot on the map 😄

**Comment by ZeLonewolf** [comment]
Yeah, and a half-dozen other incomplete features while we're at it 😂

**Comment by 1ec5** [comment]
One possible next step would be to define a color system for categorizing POIs. Lots of print maps, such as those by the National Park Service and Rand McNally, just use black silhouettes to ensure contrast against a variety of backgrounds. On the other hand, many online maps reserve a handful of colors for different kinds of POIs, roughly along the lines of the `amenity`/`healthcare`/`office`/`shop`/`tourism` distinctions OSM makes.

Honorable mention to #17, which adopted the MUTCD symbol signs, which are green for transportation-related POIs, blue for services, and brown for recreational POIs.

**Comment by jleedev** [comment]
From 1974:

![IMG_20220518_131052](https://user-images.githubusercontent.com/23022/169110726-33320b34-f695-4eed-9c3a-4150314546b2.jpg)
![IMG_20220518_130942](https://user-images.githubusercontent.com/23022/169110751-234f71f7-30e2-4827-8180-6870d3667175.jpg)

Main takeaway is you don't have to go back very far at all before the color choices are magenta and cyan.

**Comment by bgo-eiu** [comment]
https://colorbrewer2.org/#type=sequential&scheme=BuGn&n=3

Going to post this color blindness color scheme checker here, partly for myself so I don't suggest something that doesn't work great unintentionally. (There's quite a lot of color blind mappers out there)

**Comment by bgo-eiu** [comment]
Thinking in terms of contrasts and what backdrop a POI is likely to be set against does narrow things down quite a bit. The best POI maps seem to keep things pretty simple; the black silhouettes for various symbols works well but when covering a broader range of potential POIs some differentiation would be helpful. A lot of maps use red, yellow, and green for POIs but looking at the color blindness palettes and reading a bit about that topic make it clear that those particular colors are not very good for contrast. The possibility for a POI to by surrounded by or adjacent to green or blue areas of park or water also seems like an issue for those colors.

Some of the more well designed park and trail maps out there use a combination of black and purple for anything that could potentially contrast against green, which seems to work quite well. 

![image](https://user-images.githubusercontent.com/100172442/169171458-c5dd6996-4ed9-4b2b-a20a-c7c719eeeb5e.png)

Contrast in saturation and darkness seems to come up on a lot of color scheme guides / recommendations - I like the dark navy blue color in this palette a lot; seems like it could work well for icons that are likely to be over a light grey building. (The green and red in this image also look similar to the green and red already in Americana.)
![image](https://user-images.githubusercontent.com/100172442/169174584-59d5dd77-cc77-49d9-a3d3-6a9a1868fc3c.png)

One of the first common color schemes on American maps that comes to mind is blue = Parking.
![image](https://user-images.githubusercontent.com/100172442/169176046-59962d5c-35ae-4300-a3d0-5e890650ea18.png)

The red icons in the maps jleedev posted also are a very recognizable American map feature - something closer to orange might work better keeping contrasting palettes in mind. (Orange / blue is a commonly recommended combo; brown is also functionally kind of similar to orange.) It seems almost alarming though. I think it works well when alarming colors are reserved for things like hospitals and fire stations...
![image](https://user-images.githubusercontent.com/100172442/169179329-452d2701-6310-49b8-b3dc-1a6f3a5ea752.png)

Yellow can work well with black around the edges and for silhouettes inside. Not a map, but for some times of retail or other business POIs, the yellow pages phone books come to mind:
![image](https://user-images.githubusercontent.com/100172442/169188358-298e1f59-2555-4998-9c5d-4b04dfa88929.png)

---
If I were to pick a scheme off hand at the moment:
* burnt orange = fire station/hospital/clinic/healthcare type POIs
* navy blue = transportation + road side/road related services (could be things like parking icons, gas station icons that might be on buildings, as well as bus stops)
* black box with white silhouette inside = recreation/park/outdoor related POIs. could also work for things like toilets at rest stops or picnic tables which are not strictly recreation/park related but tend to be rendered like this in lots of map contexts
* black silhouette with no outline = broad range of "civic amenities" - things like schools and college campuses, government buildings, museums. this seems to be commonly done on a lot of american downtown POI maps and these items can often be surrounded by some kind of grounds that present a similar contrast issue to parks
* yellow bubble with black outline + silhouettes - retail POIs
* not strictly a POI, but the purple/magenta for paths and trails used on a lot of park maps looks nice

there's still a lot that doesn't cover, not sure where churches or communications towers or warehouses might fit in with that. probably better not to use too many colors and vary things like shapes, inversions of color combinations, textures to mix things up among broad groupings

**Comment by 1ec5** [comment]
Thanks for these examples from the world of infographics – they may or may not match the aesthetic we’ve been chasing after with print road maps, but they’re recognizable, and we probably won’t be able to hew to that aesthetic at POI-rich high zoom levels anyways.

**Comment by bgo-eiu** [comment]
It's surprisingly hard to find a good example of a print map with things like fast food places or clothing stores

**Comment by ZeLonewolf** [comment]
I tend to thing that monocolor is somewhat slavishly copying maps from the era of limited print colors, and yet I don't think we want the full bag of Skittles either.  I'm thinking broad color categories might look something like this (and I'm purely making this up to kick off the conversation):

1. Consumer (shops, restaurants, etc) (color - orangish? so we can leave purple for transit)
2. Tourism, Historic, recreation (probably brown)
3. Government, education, infrastructure, health care (black?)
4. Natural/outdoor (probably green)

**Comment by 1ec5** [comment]
> Natural/outdoor (probably green)

Note that the landuse areas around these icons will also be green, so we’d need to ensure contrast. I figure the black icons all over NPS maps are an optimization to ensure contrast, not to save on colored ink.

**Comment by ZeLonewolf** [comment]
As far as color contrast, I'm thinking of the approach I used in the draft cemetery PR in #329.  However, if we move to multiple green backgrounds for different types of greenspace, this will need to be carefully considered for icon/background contrast in all cases.

![image](https://user-images.githubusercontent.com/3254090/174498932-d01e6631-4592-480d-abc0-09fb4d3aad4c.png)

**Comment by 1ec5** [comment]
> Government, education, infrastructure, health care (black?)

Some print maps use blue for education and/or health care. There are some examples in https://github.com/ZeLonewolf/openstreetmap-americana/issues/78#issue-1096817312, by no means exhaustive. Would black emphasize or deemphasize this category’s icons?

**Comment by ZeLonewolf** [comment]
> > Government, education, infrastructure, health care (black?)
> 
> Some print maps use blue for education and/or health care. There are some examples in [#78 (comment)](https://github.com/ZeLonewolf/openstreetmap-americana/issues/78#issue-1096817312), by no means exhaustive. Would black emphasize or deemphasize this category’s icons?

The happy accident, were we to go with blue for this category, is that parking would also be blue.

**Comment by adamfranco** [comment]
>     Consumer (shops, restaurants, etc) (color - orangish? so we can leave purple for transit)
I kind of like the idea of separating shops from restaurants as I like to scan maps for food options, but would be OK leaving those together if that is needed to keep the number of categories down.

>     Tourism, Historic, recreation (probably brown)
👍 

>     Government, education, infrastructure, health care (black?)
Healthcare in red in your example seemed really nice, but this seems right if we're going for just 4 categories.

>     Natural/outdoor (probably green)
👍 Matching protected area label color would make sense. Contrast with green land-covers will be the same for the protected area labels as well as any POI icons.

**Comment by 1ec5** [comment]
> Tourism, Historic, recreation (probably brown)

Out of curiosity, which recreation did you have in mind in opposition to “natural/outdoor”? Is this entertainment like movie theaters and stadiums, or outdoor recreation like campgrounds and trailheads?

**Comment by kennykb** [comment]
From a different ticket: I like blue for healthcare - the international white H on blue matches it.  Blue for police also makes sense in the US.  Red for fire stations, maybe. But if you want to make it all black or whatever, go for it.

(I may be just being silly here. I'm perfectly fine with a limited palette.  We're likely to want to do interesting things with landcover/landuse colors, fills, inner margins eventually.)

  And paint the bike shed Sherwin-WIlliams #7591 "Red Barn".

**Comment by ZeLonewolf** [comment]
Completed in #387
