### ISSUE TITLE
West Virginia "fractional" route symbols

### ISSUE THREAD

**Issue by ZeLonewolf** [ZeLonewolf/openstreetmap-americana#13]
West Virginia has unusual 2-part "fractional" route designations as indicated here:
https://www.flickr.com/photos/andrew-turnbull/5904974507

How should these be rendered in the style?

~Blocked by #6~

**Comment by 1ec5** [comment]
> How should these be rendered in the style?

We could render it either horizontally or vertically in a rounded rectangle. A horizontal layout would use a solidus, like `(35/12)`. Either way, we’d have to stretch it beyond a circle to keep the numerals legible.
