### ISSUE TITLE
Replace Make targets with NPM scripts

### ISSUE THREAD

**Issue by 1ec5** [ZeLonewolf/openstreetmap-americana#134]
We’re already using NPM for package management, so using it also for the build system would simplify the development environment, especially for Windows users who may not have `make` installed. Each of the Make targets can be replaced by a `script` in the package.json file, so developers can run for instance `npm run code_format`.

**Comment by ZeLonewolf** [comment]
I've found `make` to be always there on WSL, whereas I always seem to have to fight with the npm environment to put it in the right version.  I'm not opposed to switching as long as the usage is documented and works consistently.

**Comment by 1ec5** [comment]
Here’s the [`script` documentation](https://docs.npmjs.com/cli/v8/using-npm/scripts#life-cycle-operation-order). In particular, the `npm start` and `npm test` idioms are very familiar to developers who use NPM.
