### ISSUE TITLE
Intermittent resizing errors on SVG imported graphics

### ISSUE THREAD

**Issue by ZeLonewolf** [ZeLonewolf/openstreetmap-americana#15]
In some cases, SVG resizing has not worked completely, resulting in partially-resized images, such as:
![image](https://user-images.githubusercontent.com/3254090/120217847-e905dd00-c206-11eb-8b5b-760e3d0ca29f.png)

Image resizing is done using a `sed` command to set the transform attribute, however, this seems to be not working the same way on all platforms.  Instead, this should be converted to an xmlstarlet command to more reliably edit the XML.

**Comment by akadouri** [comment]
The issue was with the `import_rebusurance.sh` script was the Mac `sed` command missing the file type after -i `'.svg'` per [this fix](https://mkyong.com/mac/sed-command-hits-undefined-label-error-on-mac-os-x/) and not running properly.
