### ISSUE TITLE
Future-bannered US Routes

### ISSUE THREAD

**Issue by ZeLonewolf** [ZeLonewolf/openstreetmap-americana#157]
This may be a bit outside the scope of #153 but it's at least closely related. Should a `FUTURE` banner be added for US Routes? I just happened to encounter this signage in Spokane, WA:
![image](https://user-images.githubusercontent.com/1845290/153680423-caaee515-ca22-47d0-a86c-e3fa86d433c5.png)
[image source](https://www.mapillary.com/app/?pKey=2347391622071374)

It looks like this particular section of road is tagged `ref=US 395 Fut` but I noticed [this highway tagging page on the wiki](https://wiki.openstreetmap.org/wiki/United_States_roads_tagging/Routes#Banners) suggests using `ref=* Future` rather than `Fut` so I may retag it if the banner is added to Americana.

_Originally posted by @Pengor in https://github.com/ZeLonewolf/openstreetmap-americana/issues/153#issuecomment-1036707290_

**Comment by ZeLonewolf** [comment]
Blocked by #153

I would personally support this, with a similar style to the signage - FUT above a US highway shield.  Though we would need compatible tagging -- I would recommend `network=US:US:Future` ref=`395` for this specific case.

**Comment by claysmalley** [comment]
Fixed in #1057.
