### ISSUE TITLE
Mangled graphics when drawing banner on canvas-drawn shields

### ISSUE THREAD

**Issue by ZeLonewolf** [ZeLonewolf/openstreetmap-americana#163]
When reviewing #161, I discovered a bug in the banner drawing code:

![image](https://user-images.githubusercontent.com/3254090/153986072-eaeda8a0-2c18-4006-bd7c-745ba9891f14.png)

I suspect this only occurs for canvas-drawn shields vice shields drawn on sprite backgrounds.

**Comment by zekefarwell** [comment]
I think I kind of know why this happens.  While working on better understanding the shield rendering code I realized that for shields with a raster image background the canvas size takes the number of banners into account, but this doesn't happen for shields with a canvas drawn background.  Before this PR I don't think we had any canvas drawn shields with banners so it never caused an issue.
