### ISSUE TITLE
Investigation/mapping of US:US:Connector routes

### ISSUE THREAD

**Issue by ZeLonewolf** [ZeLonewolf/openstreetmap-americana#164]
In discussion for #161, it appears that there may be several US:US:Connector routes that exist but are not currently mapped.

> I looked through all connector routes from [this Wikipedia list](https://en.wikipedia.org/wiki/List_of_special_routes_of_the_United_States_Numbered_Highway_System) and while most of them are unsigned, connector routes for [US 19](https://en.wikipedia.org/wiki/Special_routes_of_U.S._Route_19#Bryson_City_connector), [US 29 (Williamston)](https://en.wikipedia.org/wiki/Special_routes_of_U.S._Route_29#Williamston_connector), and [US 117](https://en.wikipedia.org/wiki/U.S._Route_117#Calypso_Connector) are signed. These don't have relations yet but I'll add them when I find time to

_Originally posted by @arch0345 in https://github.com/ZeLonewolf/openstreetmap-americana/pull/161#discussion_r807363989_

**Comment by claysmalley** [comment]
All Connector US routes are now mapped.
