### ISSUE TITLE
Investigation of route networks with modifier tag

### ISSUE THREAD

**Issue by ZeLonewolf** [ZeLonewolf/openstreetmap-americana#168]
There are 2100 routes with the `modifer` tag, which may be indicators of a missing route network suffix.  Example, `network=US:US` + `modifier=Business` should likely be `network=US:US:Business`.

These routes need to be investigated for incorrect network tagging which may be suppressing bannered routes.

https://taginfo.openstreetmap.org/keys/modifier#overview

* [ ] Generate overpass queries to identify networks associated with modifier tags on US networks
* [ ] Update tagging

**Comment by claysmalley** [comment]
Closing; assuming this has been addressed by #1057.
