### ISSUE TITLE
Airports and airfields

### ISSUE THREAD

**Issue by 1ec5** [ZeLonewolf/openstreetmap-americana#188]
Airports and airfields are a prominent feature in the built environment, taking up a lot of space even at middle zoom levels. They would be represented on a conventional map as:

* A label and/or icon for the overall airfield that indicates whether it’s a commercial, general aviation, or military field
* Simple lines for the runways at low zoom levels
* Outlines or fills for runways, taxiways, and possibly aprons at high zoom levels

<img width="392" alt="INDOT" src="https://user-images.githubusercontent.com/1231218/155105333-f3b1c2eb-6fb7-44d0-9f3e-a27c6a902812.png"> <img width="397" alt="San Mateo County 2006, Compass Maps" src="https://user-images.githubusercontent.com/1231218/155105816-3114ae67-6c67-46d0-ae70-4f78f48acc20.png">
<img width="607" alt="Univeral Cincinnati" src="https://user-images.githubusercontent.com/1231218/155106378-71c543eb-5373-434f-8a05-96b4dfc680cc.png">
<img width="272" alt="OklaDOT" src="https://user-images.githubusercontent.com/1231218/155107044-8cb6904d-8ab1-4762-94d3-3b513364de4c.png">

**Comment by ZeLonewolf** [comment]
There is a class attribute in OpenMapTiles that allows us to distinguish between significant and insignificant airports.

**Comment by 1ec5** [comment]
OpenMapTiles exposes runways and taxiways only as linear features based on `aeroway=*`, not polygons based on `area:aeroway=*`, so we’ll only be able to reliably achieve the simpler line treatment seen in the map of the Cincinnati/Northern Kentucky airport above, not necessarily the more detailed appearance of the Indianapolis or San Francisco airports.

**Comment by 1ec5** [comment]
Fixed in #318. Bon voyage!
