### ISSUE TITLE
Waterway labels underlap bridges

### ISSUE THREAD

**Issue by 1ec5** [ZeLonewolf/openstreetmap-americana#198]
#197 introduced waterway labels that tend to underlap bridges. While it is an interesting skeuomorphic effect to have the text running beneath bridges, it comes at the cost of readability, since we don’t have a very robust casing around bridges. These conflicts look like a bug, however well intentioned. On the other hand, a waterway label overlapping bridges looks unsophisticated too. We would have to add a robust halo around the waterway label to keep the text from becoming indiscernible above the red motorways and trunk roads.

[<img src="https://user-images.githubusercontent.com/1231218/155827297-b1fc55f1-800a-43fc-bb62-e5a7de26728b.png" width="400" alt="Brent Spence Bridge">](https://zelonewolf.github.io/openstreetmap-americana/#13/39.0909/-84.52257)

I think we should explore options for keeping the labels away from bridges. The fewer conflicts between layers, the fewer edge case we need to consider for additional contrast.

**Comment by ZeLonewolf** [comment]
Ideally, we would have a little map gremlin that nudges the labels around into non-conflicting locations.  Is there any possiblity to do that kind of thing in the front-end style?

**Comment by 1ec5** [comment]
Funny you should ask: #199.
