### ISSUE TITLE
User-switchable languages

### ISSUE THREAD

**Issue by ZeLonewolf** [ZeLonewolf/openstreetmap-americana#21]
Depends on #20

Functionality description:

A user should be able to open a tray or menu that allows them to set a language and 1 to N fallback languages.  Upon change of this setting, the map should change to use the selected languages.

**Comment by ZeLonewolf** [comment]
An example of language switching can be found here:
https://openmaptiles.org/languages/native/#0.56/0/0

**Comment by ZeLonewolf** [comment]
Perhaps we could use something like Electron to create a tray: https://stackoverflow.com/questions/40485102/rich-html-tray-menu-in-a-desktop-web-application

**Comment by 1ec5** [comment]
As of #581, the user can switch the label language by adding `&language=`, followed by an IETF BCP&nbsp;47 language tag, to the hash part of the URL. This issue tracks an in-page control for switching the language.

As far as I know, [this OpenMapTiles YAML file](https://github.com/openmaptiles/openmaptiles/blob/4cb65b0a4f95ba2ad8ea8084003b51f604435ef0/openmaptiles.yaml#L30-L99) enumerates the ISO&nbsp;639 language codes for which Planetiler adds `name:*` fields to the vector tiles. [`Intl.DisplayNames`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DisplayNames) can turn these language codes into human-readable language names in either the original language or the user’s preferred language.

**Comment by 1ec5** [comment]
#609 adds a read-only display of the label language fallback list.

**Comment by ZeLonewolf** [comment]
Here is a proposed workflow for using simplistic text links:

![image](https://user-images.githubusercontent.com/3254090/206789575-787f1d67-2ae5-4a94-962d-ded4ab612946.png)

**Comment by ZeLonewolf** [comment]
Here is a proposed workflow for using simplistic text links:

![image](https://user-images.githubusercontent.com/3254090/206789575-787f1d67-2ae5-4a94-962d-ded4ab612946.png)
