### ISSUE TITLE
Roads under construction

### ISSUE THREAD

**Issue by 1ec5** [ZeLonewolf/openstreetmap-americana#212]
The style should show roads that are under construction and possibly some major proposed roads. Otherwise, there can be prominent, otherwise inexplicable gaps or dangling roads.

[<img src="https://user-images.githubusercontent.com/1231218/156686423-ca34042d-2008-43a7-8a50-cc5002a18519.png" width="400" alt="A-35">](https://zelonewolf.github.io/openstreetmap-americana/#13/45.11697/-73.12638)<br>_Québec Autoroute 35 is being built in phases._

[<img src="https://user-images.githubusercontent.com/1231218/156687721-a9e55c59-d773-4ad9-b7de-556c87ea2447.png" width="400" alt="Roebling">](https://zelonewolf.github.io/openstreetmap-americana/#15/39.09246/-84.50986)<br>_This bridge across the Ohio River has been closed for repairs long enough to be tagged as being under construction too._

## Precedents

The predominant convention among North American maps is to depict a road under construction as a broken line:

<img width="331" alt="OklaDOT" src="https://user-images.githubusercontent.com/1231218/156690957-156e1669-9c43-4a8f-a017-292910e0184c.png">

This convention extends to maps published in Canada or for tourists from continental Europe:

<img width="625" alt="Ontario Ministry of Transportation 1994" src="https://user-images.githubusercontent.com/1231218/156688323-1e6af7c7-0ce3-4bfb-914f-33ed7370c243.png"> <img width="625" alt="Hallwag California" src="https://user-images.githubusercontent.com/1231218/156688509-3e747a2d-5aa2-441e-81ed-ec5dede2dcd8.png">

The essence of this treatment is that the casing is also broken, not just the fill, and the fill has alternating transparent segments, not white segments. I prefer this treatment to what openstreetmap-carto does, which evokes a barber pole or candy cane:

[<img src="https://user-images.githubusercontent.com/1231218/156693157-5a757e16-2c21-4331-aabd-1debdda9c1e9.png" width="400" alt="candy cane">](https://www.openstreetmap.org/#map=16/45.0935/-73.0849)

In many cases, inaccessible or unpaved roads get almost the same treatment. It seems the general idea is for a broken or dashed line to warn of a bad day:

<img width="343" alt="MnDOT 2019–20" src="https://user-images.githubusercontent.com/1231218/156687954-67563ddd-71e4-425b-a20f-a063fb6d70a5.png"> <img width="296" alt="Utah DOT 2011" src="https://user-images.githubusercontent.com/1231218/156688153-34cd73eb-b00d-4e49-a69d-ce8ff3aca39f.png">

Some maps call them “future” roads and include roads still in aspirational planning stages, while others distinguish between proposed roads and roads under construction:

<img width="508" alt="Rand McNally Dallas Metro 1994" src="https://user-images.githubusercontent.com/1231218/156690160-32e60cbe-c202-47a5-927f-841827f93eba.png"> <img width="534" alt="American Map New York City Eastern Long Island" src="https://user-images.githubusercontent.com/1231218/156690398-c53dce92-8ed4-458b-b0c8-3e41dd6e95d7.png"> <img width="353" alt="INDOT" src="https://user-images.githubusercontent.com/1231218/156692428-ab390837-9b3f-43b4-9f64-53f0dc44ebac.png"> <img width="282" alt="LaDOTD 2014" src="https://user-images.githubusercontent.com/1231218/156690779-6c531c95-23a0-47e8-8c6d-7705814cc5ad.png">

The Ohio Department of Transportation at one point used a translucent red dotted overlay to indicate future roads, just like openstreetmap-carto’s `access=no` treatment:

<img width="495" alt="ODOT 1993" src="https://user-images.githubusercontent.com/1231218/156692902-dba66afb-2394-46a6-abdb-9b48dc89fce4.png">

Most maps in my collection, even city-scale maps only show limited-access highways under construction but omit less important roads under construction:

<img width="364" alt="Best Western Nevada" src="https://user-images.githubusercontent.com/1231218/156691201-7259486b-29b5-4827-9ed1-9bc03cd45503.png"> <img width="398" alt="West Virginia DOT" src="https://user-images.githubusercontent.com/1231218/156691877-c9ed07f7-b3d9-4395-a088-dc1287dde383.png"> <img width="332" alt="AAA Hawaii 2016" src="https://user-images.githubusercontent.com/1231218/156692339-8874c4aa-22ac-47c2-a13d-31dcfba1a53c.png"> <img width="517" alt="Georgia DOT 2005–06" src="https://user-images.githubusercontent.com/1231218/156692744-a04ad96f-b4c4-4809-bcd4-7a462ddad705.png"> <img width="502" alt="Mississippi DOT 1996–97" src="https://user-images.githubusercontent.com/1231218/156694516-7307d7d6-6431-4fea-ab1b-49f96a53286c.png">

This could be because they only depict freeways for which a right of way has already been cleared, leaving a major gap. But it could also be because smaller roads tend to get completed more rapidly than paper maps can reliably keep up with.

Some maps do show multiple levels of roads under construction; these maps generally don’t already use dashes to convey surface conditions:

<img width="455" alt="South Carolina DOT 2005" src="https://user-images.githubusercontent.com/1231218/156692240-cab40a57-f118-45d6-a933-536f36d70400.png"> <img width="347" alt="North Carolina DOT 2005" src="https://user-images.githubusercontent.com/1231218/156692535-46d5515e-99f2-4762-a0c6-b068361edd4a.png"> <img width="370" alt="ODOT" src="https://user-images.githubusercontent.com/1231218/156692036-8c9c2220-52cb-4c8e-8c3e-21924094100c.png"> <img width="388" alt="Alabama DOT 2007–08" src="https://user-images.githubusercontent.com/1231218/156692637-45c260ac-5090-4e8c-b151-c88961af3216.png"> <img width="432" alt="Mobil (Rand McNally) New York" src="https://user-images.githubusercontent.com/1231218/156694436-b74d5a26-c45c-4169-b9af-6b3e031b2e70.png"> <img width="523" alt="Shell (Gousha) East Central States" src="https://user-images.githubusercontent.com/1231218/156688053-12861524-2b70-4256-824c-d38e957048db.png"> <img width="423" alt="PennDOT 2003" src="https://user-images.githubusercontent.com/1231218/156694578-d84f19d0-f47c-485a-9bd1-98133cca7e39.png">

I think it would benefit mappers if Americana shows any road under construction, regardless of classification, but if the complexity of supporting yet another facet of road classification proves too complex, at least there would be precedent for only showing the most major construction projects.

Since not-yet-completed freeways are relatively rare, most maps annotate them with a special label explicitly stating that they’re planned or under construction, even giving an expected date of completion if the DOT is confident enough about it:

<img width="407" alt="KYTC" src="https://user-images.githubusercontent.com/1231218/156691640-e7698374-0f3b-4ec4-a51f-dd90f9453b99.png"> <img width="807" alt="Universal Map Cincinnati Area" src="https://user-images.githubusercontent.com/1231218/156694911-389602d4-7eeb-466e-a081-44dd10534377.png"> <img src="https://user-images.githubusercontent.com/1231218/156697384-4a31308f-8a37-47fe-9442-ae686c3d26f1.jpg" width="400" alt="Mapsco DFW SH 170"> <img src="https://user-images.githubusercontent.com/1231218/156697488-f969a424-93f8-4e7b-a833-1dcdfdda6546.jpg" width="400" alt="Mapsco DFW IH 30/820"> <img src="https://user-images.githubusercontent.com/1231218/156697588-4d24e431-b18c-4d90-84a9-4a08b6666fde.jpg" width="400" alt="Mapsco DFW SH 360">

**Comment by matkoniecz** [comment]
I would suggest avoiding display of roads that are just proposed - it encourages mapping them and it is often filled with overenthusiastic plans, blatant campaign promises, mapping several variants, mapping personal fantasies and so on.

Completely absurd projects are being mapped.

**Comment by ZeLonewolf** [comment]
Let's scope this issue to under-construction roads, which are non-controversial and supported by OpenMapTiles.  Any discussion of proposed roads should be a separate ticket.  I tend to agree that proposed roads have a pretty serious curation issue that would need to be explored if there is ever a serious initiative to render them.

**Comment by 1ec5** [comment]
> it encourages mapping them and it is often filled with overenthusiastic plans, blatant campaign promises, mapping several variants, mapping personal fantasies and so on.

Incentives can flow in either direction – what if we hide proposed roads or make them look obnoxious unless they have some additional tags like `source` and `opening_date`? Maps typically annotate proposals with “(Expected Completion 2030)” or somesuch. That’s not to say that the date will be an accurate reflection of anything, but it would raise the bar a bit. That said, if there’s a sense that _no_ proposed highway is ever valid, then that’s a different story.

In any case, #215 only deals with roads under construction.

**Comment by matkoniecz** [comment]
> no proposed highway is ever valid

I would be actually in this camp, but I am aware that it is not a consensus position.

But "highway=proposed should be limited to serious proposals, not all official proposals are serious and all `highway=proposed` should have source in `source` tag or changeset data" seems matching consensus position

**Comment by jeisenbe** [comment]
In Openstreetmap Carto, the current railway and subway tunnel rendering is similar to the USA map examples for under-construction or proposed roads. 

Do you have thoughts about how this would work with subways and other rail tunnels? I understand they are not yet rendered here yet. 

Would under-construction railways be eventually rendered?

**Comment by 1ec5** [comment]
Good question. In #101, we were considering rendering railroad tracks with ties rather than an alternating fill, at least for freight and commuter rail. Ties seem to be an uncommon treatment for light rail and subways, but they probably wouldn’t be depicted with an alternating fill in any case. We’re currently rendering tunnels with [a faint but solid fill and casing](https://zelonewolf.github.io/openstreetmap-americana/?omss=highway-attributes&omsv=15#15/0/0), so it should be possible to combine that with the broken line treatment for tunnels. However, so far in https://github.com/ZeLonewolf/openstreetmap-americana/pull/215#issuecomment-1140313010, I’ve shied away from indicating tunnels or bridges on roads under construction. I had roads in mind, but I suppose the presence of a tunnel would be more notable for a subway under construction.

In the event of a conflict in line treatments, we can also lean on the “(Under Construction)” gloss as seen in #215, since large construction projects tend to be the exception rather than the rule.
