### ISSUE TITLE
Render expressways with a different style than standard highways

### ISSUE THREAD

**Issue by zekefarwell** [ZeLonewolf/openstreetmap-americana#22]
Highway maps commonly show expressways–also known as limited-access, controlled-access, or divided highways–with a distinct line style from standard two lane highways.  Beyond simply using a different color, expressway lines are usually thicker and have higher contrast casing.  Some examples:

![conn mass legend](https://user-images.githubusercontent.com/281482/124787223-5697de00-df16-11eb-8141-bfd616d06902.jpg)
![Kansas DOT 2009–2010 legend](https://user-images.githubusercontent.com/281482/124787225-57307480-df16-11eb-868f-6425dad8eb2b.jpg)
![legend-image](https://user-images.githubusercontent.com/281482/124787227-57307480-df16-11eb-8bc5-122aea2d0119.jpg)
![Oklahoma DOT legend](https://user-images.githubusercontent.com/281482/124787229-57307480-df16-11eb-824e-aecbb71bcacb.jpg)
![PennDOT legend](https://user-images.githubusercontent.com/281482/124787243-5992ce80-df16-11eb-9809-ab731f25733d.png)
![PennDOT highway map](https://user-images.githubusercontent.com/281482/124787280-5e578280-df16-11eb-95b9-3b63b0ae9bd1.jpg)

Other than `highway=motorway` OSM `highway` classifications are functional, not physical, so there are both `trunk` and `primary` expressways (I don't think `secondary` expressways exist but I suppose it's possible).  So to indicate the physical characteristics of an expressway we have [a separate tag, `expressway=yes`](https://wiki.openstreetmap.org/wiki/Key:expressway).  It would be great for this style to be the first to render expressways distinctly based on this tag.  Below are some rendering ideas for how this could look.

<br>

### Low zoom where individually mapped carriageways merge together as one line

![expressway-highway-low-zoom](https://user-images.githubusercontent.com/281482/124790963-a1ffbb80-df19-11eb-9ee8-d82f94bb730c.png)

<br>

### Higher zoom where individually mapped carriageways are visible

![expressway-highway-high-zoom](https://user-images.githubusercontent.com/281482/124792411-fce5e280-df1a-11eb-9b81-05eba59a8d18.png)

All motorways are expressways, so `highway=motorway` implies `expressway=yes` and would always be rendered with the expressway line style.  trunk` and `primary` would have a standard highway line style and an expressway line style that would be used when `expressway=yes` is set.  

Currently the `expressway` tag is primarily used in North America, but the concept is applicable elsewhere as well.  In other parts of the world [the `motorroad` tag](https://wiki.openstreetmap.org/wiki/Key:motorroad) is far more common.  While `expressway` defines the physical construction of a highway, `motorroad` defines legal access restrictions (i.e. a road where only for motor vehicles are allowed).  Although the definitions are different, in practice `motorroad=yes` is often applied to the same or very similar kinds of limited access, divided highways as `expressway=yes`.  So for this map style we _**may**_ want to interpret `motorroad=yes` as implying `expressway=yes` when the tag is absent and render these highways with the expressway line style.  In the case of an explicit `expressway=no` the standard highway line style would be used.

**Update 2021-11-04:**
My thinking on the above has changed and I'm not sure if it is actually a good idea to assume that `motorroad=yes` implies `expressway=yes` when `expressway=no` is not present.  I more clearly understand now that the reason for the `motorroad=yes` tag is that in countries where it is used, access restrictions are not explicitly signed on these roads.  Instead there is a blue sign with an icon of a car which means "motor vehicles only".  Since the sign doesn't say exactly what modes of transport are prohibited it's hard for mappers to set all the right access tags (`horse=no`, `bicycle=no`, etc).  In North America on the other hand, access restrictions generally are explicitly signed (No pedestrians, No bicycles, etc) so it is easy for mappers to tag them explicitly and there is no need for the `motorroad` tag.  All this is to say that while `motorroad=yes` is tagged on many roads that physically qualify as expressways, it also is tagged on some that do not so I'm not sure we should use it for this rendering distinction.

**Comment by adamfranco** [comment]
I just want to note that `highway=secondary` + `expressway=yes` is a valid combo that should be supported. I just downgraded an expressway in Rochester, NY to secondary based on its State ACC classification and use as an intra-urban feeder:  [Way: Mount Read Boulevard (20116226)](https://www.openstreetmap.org/way/20116226#map=15/43.1963/-77.6577). I downgraded to `highway=secondary` in [Changeset 112773714](https://www.openstreetmap.org/changeset/112773714). 

Here's another example that is currently `highway=secondary` + `expressway=yes`, the access road to the Syracuse Airport: https://www.openstreetmap.org/way/38606400#map=15/43.1149/-76.1228

In even larger urban areas I could imagine a use for tertiary expressways, such as feeders for airports, theme parks, industrial parks, and other major traffic sources.

**Comment by ZeLonewolf** [comment]
> I just want to note that highway=secondary + expressway=yes is a valid combo that should be supported

I agree with this assessment.  In openmaptiles/openmaptiles#1148 I propose to add data support for expressway tagging on trunk through tertiary plus unclassified.  `tertiary`/`unclassified` + `exressway=yes` seem like...highly questionable combination, but if it's tagged I see no reason not to support it.  Perhaps we might find cases where a previously planned larger freeway was not completed, leaving behind expressway road sections that have limited connectivity value in the broader road network.

**Comment by ZeLonewolf** [comment]
Expressway tagging was added to OpenMapTiles in openmaptiles/openmaptile#1313.  Thus, this issue can be worked on once OpenMapTiles 3.13 is released.

**Comment by Pengor** [comment]
@ZeLonewolf is this issue ready for closure due to merging of #82 or are further enhancements needed?

**Comment by zekefarwell** [comment]
Further enhancements are needed, but that is true of the whole road network, not just expressways.  Could close to the issue to show that the initial implementation is done, or leave it open for further work.  At the very least it's certainly not blocked anymore.

**Comment by adamfranco** [comment]
What enhancements do you see as still needed on expressways? 

With #165 and #150 the general-purpose road network is now at least drafted ([sample](https://zelonewolf.github.io/openstreetmap-americana/?omss=highway-attributes&omsv=13#13/0/0)).
![Screen Shot 2022-02-17 at 3 22 00 PM](https://user-images.githubusercontent.com/25242/154564380-c9848d72-9f0c-4b97-8784-4445d13d3a6a.png)
 
 We still need to tweak the relative importance of primary and down as described in #84. Those changes could demand tweaks to expressways, but maybe not.

**Comment by ZeLonewolf** [comment]
The purpose of this ticket is certainly satisfied.  Thanks @adamfranco for your hard work on getting expressways rendered.  Closed by #82, #150, #165
