### ISSUE TITLE
Manitoba highway shields

### ISSUE THREAD

**Issue by TagaSanPedroAko** [ZeLonewolf/openstreetmap-americana#229]
Similar to Alberta:

- Trans-Canada Highway routes (Highways 1 and 16, network=CA:transcanada): Maple leaf (PR at #226)
- Provincial trunk highways (numbers 1-199, save Highways 1 and 16, network=CA:MB:PTH): squared-off shield (see also #218)
- Provincial roads (numbers 200-632, network=CA:MB:PR): oblong.
- Winnipeg city routes (network=CA:MB:Winnipeg): trapezoid (see example: [Route 105 shield](https://commons.m.wikimedia.org/wiki/File:Winnipeg_city_route_105.svg))

Similar with Alberta (see #218), the regular Manitoba provincial highway marker contains the shield within a rectangle with the provincial wordmark on top (see [this shield for Highway 10](https://commons.m.wikimedia.org/wiki/File:Manitoba_Highway_10.svg)), but the shield itself only (also used in interchange guide signs) has been preferred for simplicity, and also in line with practice by most commercial road maps (GMaps, most print maps). The official Manitoba highway map (see https://www.gov.mb.ca/mit/map/pdf/mapside.pdf ) also does the same, but uses a maple leaf completely filled with green for TCH routes.

**Comment by TagaSanPedroAko** [comment]
@1ec5 It's been a week now. Have a PR made for this.

**Comment by 1ec5** [comment]
Sorry, I’ve been busy, but you’re welcome to take a look at CONTRIBUTING.md and contribute these shields, as many others have done. This is a volunteer project after all. 🙂
