### ISSUE TITLE
Unfork GL JS

### ISSUE THREAD

**Issue by 1ec5** [ZeLonewolf/openstreetmap-americana#230]
#72 forces shields to stay upright using the `text-rotate-to-line` layout property from the original version of maplibre/maplibre-gl-js#716. We’ve been depending on [a fork of MapLibre GL JS](https://github.com/ZeLonewolf/maplibre-gl-js/) for this functionality. Now that maplibre/maplibre-gl-js#716 has landed in main, we’ll be able to unfork the MapLibre GL JS dependency by the next release.

https://github.com/ZeLonewolf/openstreetmap-americana/blob/fa380ac2654820963763af2d173da34aae0f3712/style/package.json#L25 https://github.com/ZeLonewolf/openstreetmap-americana/blob/fa380ac2654820963763af2d173da34aae0f3712/style/layer/highway_shield.js#L34

After rounds of code review, @wipfli settled on a different API design. We’ll need to migrate to `"text-rotation-alignment": "viewport-glyph"` instead of `"text-rotate-to-line": false`.

**Comment by wipfli** [comment]
Looking forward to your feedback. You can use `v2.1.8-pre.1` which has the new feature.
