### ISSUE TITLE
Puerto Rico shields

### ISSUE THREAD

**Issue by claysmalley** [ZeLonewolf/openstreetmap-americana#240]
**(EN)**

Puerto Rico has only one network of signposted routes, though signage can shift between any of 4 shields depending on a segment's importance in the road hierarchy. Route numbers can have up to 4 digits.

Current coverage of `route=road` relations in Puerto Rico is incomplete, and existing relations are tagged with `network=US:PR`, conflating all shields into one network. There has been no discussion yet towards new `network` values that correspond to shield appearance.

**(ES)**

Puerto Rico tiene una sola red de rutas rotuladas, aunque la rotulación puede cambiar entre cualquiera de los 4 diseños según la importancia de un segmento en la jerarquía vial. Los números de las rutas pueden tener hasta 4 dígitos.

La cobertura actual de las relaciones `route=road` es incompleta, y las relaciones existentes tienen la etiqueta `network=US:PR`, combinando todos los diseños en una red. Todavía no ha habido discusión hacia nuevos valores de la clave `network` que correspondan a diseños de identificadores de rutas. 

----

Primary shield / identificador primario:

![Puerto Rico primary shield](https://upload.wikimedia.org/wikipedia/commons/b/b7/PR_primary_1.svg)

Urban primary shield / identificador primario urbano:

![Puerto Rico urban primary shield](https://upload.wikimedia.org/wikipedia/commons/e/e6/PR_urban_primary_1.svg)

Secondary shield / identificador secundario:

![Puerto Rico secondary shield](https://upload.wikimedia.org/wikipedia/commons/f/fb/PR_secondary_1.svg)

Tertiary shield / identificador terciario:

![Puerto Rico tertiary shield](https://upload.wikimedia.org/wikipedia/commons/5/53/Ellipse_sign_1.svg)

**Comment by 1ec5** [comment]
> La cobertura actual de las relaciones `route=road` es incompleta, y las relaciones existentes tienen la etiqueta `network=US:PR`, combinando todos los diseños en una red.

Además, [unas relaciones de autopistas](https://www.openstreetmap.org/relation/4431286) no tienen las etiquetas `network` e incluyen el prefijo “PR-” en `ref` como en las vías.

**Comment by 1ec5** [comment]
I [asked the talk-pr mailing list](https://lists.openstreetmap.org/pipermail/talk-pr/2022-July/000391.html) about making `network` more specific, as in Tennessee (#303), and removing the prefixes from the route relations’ `ref` tags.
