### ISSUE TITLE
Newfoundland and Labrador shields

### ISSUE THREAD

**Issue by claysmalley** [ZeLonewolf/openstreetmap-americana#280]
Newfoundland and Labrador has a simple black-on-white rectangular shield.

Newfoundland and Labrador has only one route network (other than the Trans-Canada Highway), tagged `network=CA:NL:R`. The `:R` at the end is unnecessary and inconsistent with other provinces that only have one route network. A suggested tagging scheme that follows guidelines would be `network=CA:NL`. We should hold off on supporting NL shields until this tagging issue is resolved one way or another.

![](https://www.alpsroads.net/roads/nl/nl_90/s1.jpg)
![](https://www.alpsroads.net/roads/nl/tch_1/e408.jpg)

**Comment by 1ec5** [comment]
> Newfoundland and Labrador has a simple black-on-white rectangular shield. This is coincidentally the same as the default shield, making this trivially easy to support.

The default shield changed in #426 so that it no longer resembles the shields used in Newfoundland and Labrador.

**Comment by claysmalley** [comment]
I messaged two active mappers from the province. One responded in favor; the other didn't respond at all. I went ahead and retagged the routes to `network=CA:NL`: https://www.openstreetmap.org/changeset/133463671
