### ISSUE TITLE
Toronto expressway shields

### ISSUE THREAD

**Issue by claysmalley** [ZeLonewolf/openstreetmap-americana#281]
The city of Toronto, Ontario has its own expressway shields.

Shields for Toronto expressways (`network=CA:ON:Toronto:Expressway`) are an orange bullseye inside of a green circle, with white text in the green part encircling the bullseye. Shown below is the Don Valley Parkway, currently tagged with `ref=DVP`, not visible on the shield. The Gardiner Expressway is likewise tagged with `ref=Gardiner`, which is visible on the shield (identical to the Don Valley Parkway shield except for text), though probably too long to display.

![DVP_Shield](https://user-images.githubusercontent.com/1732117/163627200-c0ecc9a6-475f-4398-8736-0b8da6e2d2c0.svg)

**Comment by zekefarwell** [comment]
I researched the Don Valley Parkway and Gardiner Expressway shields a while back and I think the yellow image may not match the real world signs.  Hopefully we could get some on the ground evidence from someone who knows the area, but it looks like the both DVP and Gardiner may have the same green/orange design in reality.
<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/4/41/Gard-trailblazer.jpg/482px-Gard-trailblazer.jpg">

**Comment by andrepoiy** [comment]
They should have the same colour combo. If you check the version history on Wikimedia for the DVP sign, it was changed to the current version and claims to have the accurate colours - which is probably correct, since a lot of the signs are old and the colours may have faded, which prompted whoever made the lighter coloured design

**Comment by claysmalley** [comment]
> They should have the same colour combo. If you check the version history on Wikimedia for the DVP sign, it was changed to the current version and claims to have the accurate colours - which is probably correct, since a lot of the signs are old and the colours may have faded, which prompted whoever made the lighter coloured design

Updated issue to correct info and remove inaccurate shield image.

**Comment by claysmalley** [comment]
Separated Hamilton expressways into a new issue: #377
