### ISSUE TITLE
Arkansas Highway 980 (airport) shields

### ISSUE THREAD

**Issue by claysmalley** [ZeLonewolf/openstreetmap-americana#287]
Arkansas Highway 980 is a number used many times around the state on short roads leading to airports. All instances are currently tagged `network=US:AR`. A decision would need to be made on tagging of the `network=*` value, and whether this would add any special cases, before support can be added to this project.

Compared to the standard Arkansas state route shield, the Arkansas shield is color-swapped, the ref of the road is shrunk and moved to the bottom of the state outline, additional text is added along the top, and line art is placed in the middle. Highway 980 has "AIRPORT" as its top text, an airplane as the line art, and a white-on-blue color scheme.

![Arkansas_980(Airport)](https://user-images.githubusercontent.com/1732117/163723358-f2c93691-009d-4927-bdac-3a818ac3799c.svg)

**Comment by 1ec5** [comment]
Two Highway 980s are currently mapped as route relations:

* [Desha County, section 1](https://www.openstreetmap.org/relation/6195191)
* [Pope County](https://www.openstreetmap.org/relation/10535603)

Both are tagged `network=US:AR` `ref=980`.

**Comment by claysmalley** [comment]
Separated Marine Fuel Tax shields into a new issue: #375
