### ISSUE TITLE
Florida's Turnpike shield

### ISSUE THREAD

**Issue by claysmalley** [ZeLonewolf/openstreetmap-americana#289]
The unique shield for Florida's Turnpike (currently tagged `network=US:FL:Turnpike`, no `ref=*`) is a white-bordered green rectangle with white text "FLORIDA'S TURNPIKE" at the top and a white silhouette of Florida with a green line indicating the route of the Turnpike on the bottom.

Text could probably be removed, as the shield and the shape of Florida are recognizable without it.

![Florida's_Turnpike_shield](https://user-images.githubusercontent.com/1732117/163743363-8d7e34a3-5a32-4f32-87a7-a95267cb7352.svg)

**Comment by 1ec5** [comment]
This is actually a different system of routes than the usual Toll-bannered numbered state routes. I think there should be a distinct `network`, which would have at least two routes in it (counting the Homestead Extension).

**Comment by 1ec5** [comment]
> at least two routes in it

* [Florida’s Turnpike](https://www.openstreetmap.org/relation/282102)
* [Homestead Extension of Florida’s Turnpike](https://www.openstreetmap.org/relation/188063)

([Florida’s Turnpike Enterprise](https://en.wikipedia.org/wiki/Florida's_Turnpike_Enterprise) operates several more toll roads under FDOT’s normal state toll road brand identity. Those routes would remain tagged `network=US:FL:Toll`.)

**Comment by 1ec5** [comment]
[Changeset 120,065,242](https://www.openstreetmap.org/changeset/120065242) migrates these two relations to `network=US:FL:Turnpike` after no objections were raised in [this OSMUS Slack discussion](https://osmus.slack.com/archives/CB7NU9007/p1650438050895919). If there’s a need to disambiguate Florida’s Turnpike from other turnpikes around the state, this tag can be revised.
