### ISSUE TITLE
Kansas Turnpike shield

### ISSUE THREAD

**Issue by claysmalley** [ZeLonewolf/openstreetmap-americana#290]
The Kansas Turnpike (currently tagged `network=US:KS:Turnpike`, no `ref=*`) has a similar shield to Kansas state highways. Differences include:

* The flower has 20 petals instead of 16
* The background is blue instead of black
* In place of the route number is a white-on-blue logo of the Kansas Turnpike Authority, with blue text "KANSAS TURNPIKE" encircling it in the yellow part

The shield is probably recognizable without the text "KANSAS TURNPIKE". Since the extra 4 petals are not a noticeable detail, the geometry can be copied from the existing Kansas shield. If necessary, the KTA logo could be enlarged slightly, or the K and A could be removed to leave the T.

![Kansas_Turnpike](https://user-images.githubusercontent.com/1732117/163744035-6b426480-d4aa-473b-bfd8-70fa09efd4e5.svg)

K-4 (`network=US:KS`, `ref=4`) for reference:
![K-4](https://user-images.githubusercontent.com/1732117/163744140-3f54d14a-eaaa-4cb5-be37-30b21c374308.svg)

**Comment by 1ec5** [comment]
Despite the visual similarity to the K-road shield, it would be nice if the turnpike were to use a distinct `network` value. Ohio mappers originally took the same approach as in Kansas, with the Ohio Turnpike being tagged `network=US:OH` with a `name` but no `ref`, but later switched to `US:OH:Turnpike` to be more explicit.

**Comment by claysmalley** [comment]
> Despite the visual similarity to the K-road shield, it would be nice if the turnpike were to use a distinct `network` value. Ohio mappers originally took the same approach as in Kansas, with the Ohio Turnpike being tagged `network=US:OH` with a `name` but no `ref`, but later switched to `US:OH:Turnpike` to be more explicit.

Are you sure? I'm seeing `network=US:OH` in the [Ohio Turnpike relation,](https://www.openstreetmap.org/relation/1661720) and that's how it seems to be supported in this project.

**Comment by 1ec5** [comment]
Oh, I misremembered. We had discussed changing the network value for it but wound up doing the expedient thing, figuring that a less shield-savvy renderer would end up with a blank Ohio state shape. Call it tagging for the renderer. 🙈

**Comment by claysmalley** [comment]
Tagging has been changed to `network=US:KS:Turnpike`.
