### ISSUE TITLE
Update shield contribution guidelines to describe 2px rounded corners on right angles

### ISSUE THREAD

**Issue by ZeLonewolf** [ZeLonewolf/openstreetmap-americana#315]
Based on discussion on Slack, shields with right angles should use a 2px rounded corners when drawing right angles.  This makes the shields a bit less harsh and mirrors how they're typically drawn in the real work.  The documentation should be updated to indicate this and also provide hints to graphics designers as to how to achieve this in Inkscape.

**Comment by claysmalley** [comment]
I can take a crack at this. Now that #314 is merged, I can go through and review our existing library of shields, and I'll try to write down some tips and tricks as I go along.
