### ISSUE TITLE
Consider changing Vermont shield to better match real world design

### ISSUE THREAD

**Issue by zekefarwell** [ZeLonewolf/openstreetmap-americana#322]
When the VT shield graphic was originally added early on in the project, the design goal was for shields to be significantly simplified symbols, representative of the real shield signs.  Since then a lot of shields have been added that are much more detailed and closer to their real world counterparts.  The current VT shield graphic (below) looks a bit oversimplied in comparison now.

<img width="185" alt="Screen Shot 2022-05-14 at 1 36 48 AM" src="https://user-images.githubusercontent.com/281482/168412296-fdb8a77a-e295-4612-94da-2c93d9db5113.png">

I think it would be appropriate to add some more detail to bring it closer to the real world design (below).

<img width="70" src="https://user-images.githubusercontent.com/281482/168410194-e218f47e-80b3-424b-98b0-db83b4a28e58.png">  <img width="88" src="https://user-images.githubusercontent.com/281482/168410257-80ab1a4c-0dea-4b63-a7a8-e5a6b8c3bfd6.png">

<img width="25" height="25" src="https://user-images.githubusercontent.com/281482/168410172-321db0fd-b790-45ba-9718-6e237ed83e81.png">  <img width="32" height="25" src="https://user-images.githubusercontent.com/281482/168410254-39119a49-a1e8-4b84-b9b9-6de580e820a9.png">

## Paper highway map examples

Here are some examples of how various paper highway maps symbolize VT route shields.

AAA, 2021
<img width="300" src="https://user-images.githubusercontent.com/281482/168410921-5a68925a-d171-4360-95e5-660059aa8acd.jpg">

Delorme, 2007
<img width="400" src="https://user-images.githubusercontent.com/281482/168410922-8a5d7bd9-43a2-4135-b54a-b7545285946c.jpg">

Jimapco, 2014
<img width="500" src="https://user-images.githubusercontent.com/281482/168410923-9e163239-774f-4ab7-9c0d-e41ddbc51efb.jpg"> 

Michelin, 2022
<img width="450" src="https://user-images.githubusercontent.com/281482/168410924-436660d4-d43b-4464-8e9d-92e43dbb0558.jpg">  

Rand McNally, 2022
<img width="450" src="https://user-images.githubusercontent.com/281482/168410925-b1a756a2-f0a1-4b99-9ed5-0f36e3f4ef6a.jpg">

Vermont Department of Tourism, 2021
<img width="400" src="https://user-images.githubusercontent.com/281482/168410926-13b16214-ef16-484c-828e-2b5f4e26c6bb.jpg">

Most of these maps just use plain ovals. The VT tourism map does use the chopped oval/bulging rectangle shape, although with red or black instead of green.  Jimapco is the only one with a similar style of real world shield representation to what we are going for in this project.  Here's another Jimapco clip from the VT/NY border showing a very similar NY shield to ours.  

<img width="350" src="https://user-images.githubusercontent.com/281482/168411468-b83d5f23-4ca7-4451-83b6-ce071c88b2a3.jpg">

## Ideas for this style

Thanks to @claysmalley for creating these test renders of some different options!  Each option is shown @1x and @2x.

One of our design guidelines is to remove the background when a shield design is non-rectangular shape inscibed within a rectangular sign.  Following this guideline gives us something like this.  It captures the essence, but feels a bit awkward.

![Screenshot from 2022-05-13 08-55-30](https://user-images.githubusercontent.com/281482/168411988-8e3f5d44-a669-4268-89f6-1b3b61c96e08.png) <img width="237" src="https://user-images.githubusercontent.com/281482/168411989-dcbd20c6-3ff7-446e-ad9e-269516351544.png">

Reducing the width of the top bar slightly is an improvement.

![Screenshot from 2022-05-13 08-58-03](https://user-images.githubusercontent.com/281482/168409611-fa335909-4349-4b40-8b15-f63e38dc99c5.png)    <img width="250" src="https://user-images.githubusercontent.com/281482/168409446-7765b77b-6023-4092-97bd-47cac6edf524.png">  

Including the full green rectangle behind the white shapes looks very much like the Jimapco style.

![Screenshot from 2022-05-13 08-58-03](https://user-images.githubusercontent.com/281482/168412048-aef61f05-4aab-422f-a5a7-910420a33199.png)  <img width="254" src="https://user-images.githubusercontent.com/281482/168412047-8f8e81ef-8a0f-4cb4-8829-056d1f9955dd.png">

An in-between approach.

![Screenshot from 2022-05-13 10-05-01](https://user-images.githubusercontent.com/281482/168412095-4a6be2b5-58be-4007-942e-eb933868ae21.png)  <img width="286" src="https://user-images.githubusercontent.com/281482/168412096-8323ae3f-ce79-4c19-91a7-331dce82c61d.png">

And for comparison the current shield.

![Screen Shot 2022-05-14 at 12 03 16 AM](https://user-images.githubusercontent.com/281482/168410078-a504b2b4-9da4-4a01-b630-4eef4ebab195.png)  <img width="265" alt="Screen Shot 2022-05-13 at 11 57 58 PM" src="https://user-images.githubusercontent.com/281482/168410081-0cb8e58b-08d7-4eed-a6fd-b28af3b30392.png">

There has been some [discussion on Slack](https://osmus.slack.com/archives/C01V02K52UX/p1652446152362849?thread_ts=1652327308.600869&cid=C01V02K52UX) of these options, but a consensus has not yet emerged on whether we should make a change and if so which design to use.

**Comment by 1ec5** [comment]
The choice to remove the black backgrounds from MUTCD-style shields isn’t absolute. If adding the background in this case yields a better aesthetic, I don’t think it would detract from the overall approach nationally. At a small enough size, the full shield (minus the word “VERMONT”) doesn’t look all that different than what we’ve come up with for Maryland, just with a little more internal rounding of corners.

**Comment by ahallification** [comment]
How old are the map examples? VT didn’t roll out their shield until the mid 90s. If the maps are on the older side than whether or not they include the shield could be moot.

**Comment by zekefarwell** [comment]
I updated the map example captions to include the year published.  They are all quite recent except for Delorme (2007) and Jimapco (2014).  All published well after the mid 90s though.

**Comment by ZeLonewolf** [comment]
My concern of course is a slippery slop to other types of backgrounds that we've otherwise omitted in other shields.  Not that this is a good or bad thing, but let's make sure whatever is decided here is consistent with other shields in other places that face a similar question.

**Comment by zekefarwell** [comment]
I certainly appreciate the slipper slope concern.  Originally I was very much in favor of making shields very simplified, symbolic representations, and the earliest shields were very simple.  Over time more detail has crept in that I felt went against the original simplified idea.  However, I've come to appreciate this extra detail as it is clearly something highway mappers are quite passionate about.  For example, the Minnesota, South Carolina, Nova Scotia, and British Columbia shields could certainly be simplified, but the tiny details add personality to the map.

![MN](https://raw.githubusercontent.com/ZeLonewolf/openstreetmap-americana/main/style/icons/shield40_us_mn_2.svg) ![SC](https://raw.githubusercontent.com/ZeLonewolf/openstreetmap-americana/main/style/icons/shield40_us_sc.svg) ![NS](https://raw.githubusercontent.com/ZeLonewolf/openstreetmap-americana/main/style/icons/shield40_ca_ns_h.svg) ![BC](https://raw.githubusercontent.com/ZeLonewolf/openstreetmap-americana/main/style/icons/shield40_ca_bc_2.svg) 

Since we are clearly open to evolving the design aesthetic over time, I see no problem with reconsidering an early decision we made to always cut out backgrounds.  For shields with simple shapes inscribed in a rectangle I think cutting out the background looks great.  For more complex shapes, or those that almost entirely fill the rectangle, it's possible that including some or all of the background may look better.  I think we should be open to trying out some variation while keeping the general cutout guidline.  You know what they say: rules are made to be broken.

For the Vermont shield, I propose to use a reduced bulge on the lower white section making it much closer to the Maryland shield ![MD](https://raw.githubusercontent.com/ZeLonewolf/openstreetmap-americana/main/style/icons/shield40_us_md_2.svg), while still keeping the suggestion of roundness.  This minimizes the "background", making it more of a variable width border.  1x on the left, 2x on the right.

![Vermont_30_1x](https://user-images.githubusercontent.com/281482/169434733-95544a2e-e33d-4bb3-9863-d873bed56237.png) <img width="20" src="https://user-images.githubusercontent.com/281482/169434739-24ed1e7a-52c2-43a4-a640-8e3a201475a8.png">




For comparison here is the same graphic but using the bulge curve from the real world shield design:

![Vermont_30_full_curve_1x](https://user-images.githubusercontent.com/281482/169442168-a9323a62-f1f7-46bc-b7e5-108c0a029664.png) <img width="20" src="https://user-images.githubusercontent.com/281482/169442174-a81022a4-779b-40f0-982e-f27189d3ca7e.png">
