### ISSUE TITLE
Water labels are under roads

### ISSUE THREAD

**Issue by ZeLonewolf** [ZeLonewolf/openstreetmap-americana#338]
Draw ordering should be adjusted so that this doesn't happen to water labels:

![image](https://user-images.githubusercontent.com/3254090/169631576-5c1de290-bd33-4b3d-a4a3-4aec93632315.png)

**Comment by 1ec5** [comment]
Specifically, this affects point features (ponds, swimming pools), but not linear features like rivers, which were addressed in #199. Ideally, there would be a way to distinguish such small bodies of water to avoid labeling them or to set their labels in really small font.

**Comment by jleedev** [comment]
Duplicated by #507 and fixed by #509
