### ISSUE TITLE
NH Turnpike Shields

### ISSUE THREAD

**Issue by weech** [ZeLonewolf/openstreetmap-americana#343]
There are two turnpikes in New Hampshire that should get shields in this project. The Central Turnpike is called the [Everett Turnpike](https://www.openstreetmap.org/relation/13037911) and is signed with 
![image](https://user-images.githubusercontent.com/21208007/169904169-b995d9c4-ee5a-41a1-8ab4-ea27dc0a36b3.png)
It is partially concurrent with US 3, I-293, and I-93, and it partially stands on its own. It also includes several spurs that are signed with the same shield on mile markers, though they aren't mapped in OSM yet.

The northern portion of the Eastern Turnpike is called the [Spaulding Turnpike](https://www.openstreetmap.org/relation/114529) and is signed with 
![image](https://user-images.githubusercontent.com/21208007/169904489-f9cf1298-07d7-42ff-bc64-600bebe89563.png)
It's fully concurrent with NH 16, though if you call it Route 16 people will look at it you funny. 
(Images from Wikipedia)

The southern portion of the Eastern Turnpike is called the Blue Star Turnpike, but this name only exists on paper, so I don't think it should be rendered here. It's only signed as I-95. 

I currently have the 3 turnpikes tagged in the [one relation per-direction scheme](https://wiki.openstreetmap.org/wiki/Route_directions#One_relation_per_direction) scheme with the `network` tagged as "US:NH:Turnpike", the `ref` tag unset, and the `name` tag set to the common name (as it appears on the shield for the signed ones). There's no special tagging for the unsigned Blue Star Turnpike yet. Now that I think about it, it probably shouldn't be in OSM at all. Are there other named routes that are totally unsigned that we know about?

And what steps do we have to take to get the shields for the Spaulding and Everett Turnpikes included?

**Comment by claysmalley** [comment]
The tagging would indeed need to be changed to `network=US:NH:Turnpike:Everett` and `network=US:NH:Turnpike:Spaulding` to support these shields in this project. Currently, our limited support for color-swapping on shields of the same `network=*` is based on the `ref=*` of the route. Considering these Turnpikes have `ref=*` blank, we have no way to differentiate them without using different `network=*` values.

@ZeLonewolf usually runs manual data updates, because we don't have a pipeline for automatic updates yet. Unfortunately he's on vacation for the next couple of weeks.

If the ideal renderings of these two shields have the exact same geometry with different colors, a single black-and-white shield SVG is sufficient, and `colorLighten` can be used in the shield definitions to swap the black for another color.

**Comment by quincylvania** [comment]
Here are some icons that closer-mirror the layout of the original shields. The TP is the same as for #756, which will render nearby.

![shield_us_nh_turnpike_blue](https://user-images.githubusercontent.com/2046746/216729950-a2359f01-ae24-449d-855d-12030a77edb7.svg)
![shield_us_nh_turnpike_green](https://user-images.githubusercontent.com/2046746/216729952-cf3f4f29-c075-4a98-a63a-43abe4a9349d.svg)

**Comment by quincylvania** [comment]
> The tagging would indeed need to be changed to network=US:NH:Turnpike:Everett and network=US:NH:Turnpike:Spaulding to support these shields in this project. 

Can we key off the `name` tag? Or have an alpha `ref` tag like for #569? It doesn't make sense that the state's turnpikes would all be in different networks, especially since the shields are so similar.

**Comment by ZeLonewolf** [comment]
Yes we can.  See the approach used for Kentucky's turnpikes.

**Comment by jleedev** [comment]
Although, with the current legend system there's only one data item shown per network:

![Screenshot_20230203-195953](https://user-images.githubusercontent.com/23022/216736810-ee253b08-8c01-4b00-9237-7550375d0054.png)
![Screenshot_20230203-195846](https://user-images.githubusercontent.com/23022/216736812-ae2ec188-67a2-4f80-aa78-0f5524b0a1ae.png)
![Screenshot_20230203-195502](https://user-images.githubusercontent.com/23022/216736813-7cf18cdb-a122-4103-a409-2d923bf2e023.png)

**Comment by 1ec5** [comment]
If that’s a problem, we could tweak the legend to do whatever it does in Pittsburgh:

<img src="https://user-images.githubusercontent.com/1231218/216739916-60547421-6f32-4584-98ee-c993da3ccf28.png" width="360" alt="Allegheny">

**Comment by AntiCompositeNumber** [comment]
I've put together an implementation in #918 using overrideByName. I used the shields from https://github.com/ZeLonewolf/openstreetmap-americana/issues/343#issuecomment-1416529985 but with the top corners squared off to more closely match the original shield.

![Everett_square](https://github.com/ZeLonewolf/openstreetmap-americana/assets/10331574/b1ea054c-2ef1-4326-8d40-768ceaaf1929)
![Spaulding_square](https://github.com/ZeLonewolf/openstreetmap-americana/assets/10331574/35deafef-61e6-4a94-a361-905943d3105f)
