### ISSUE TITLE
Unclear what kind of feedback is welcome

### ISSUE THREAD

**Issue by matkoniecz** [ZeLonewolf/openstreetmap-americana#344]
https://github.com/ZeLonewolf/openstreetmap-americana#coverage - should it be treated as "we support this areas, do not bother us about other"?

Or "we support this areas, feel free to make PR adding support for other"?

Or "we support this area, feel free to make issue about missing shields elsewhere"?

Asking as I was unsure whether making issue about shields missing in Poland, with no intention of making PR I would provide links to SVG shields. Would it be welcome and useful contribution or not?

BTW, CONTRIBUTING.MD file is also missing.

**Comment by adamfranco** [comment]
Definitely **not** "we support this areas, do not bother us about other". Of the latter two I will leave further commentary to those who are actually working on shields and can state whether links to SVGs is a sufficient starting point.

One thought: We could create an issue template for new shields that also includes prompts for the other information we need, like which `network=*` tag[s] are covered, other local quirks, and photo examples in the wild.

**Comment by claysmalley** [comment]
The style contribution guidelines are at [style/CONTRIBUTE.md](https://github.com/ZeLonewolf/openstreetmap-americana/blob/main/style/CONTRIBUTE.md).

I considered making issue templates a while back, one of which would be for requesting support for missing highway shields. I think this would be valuable, though we should think it through and have templates for every kind of issue.

In short, feel free to write up an issue describing the the current tagging of the route network in question, with example images. PRs are also welcome, though obviously they're a little more work.

**Comment by matkoniecz** [comment]
> The style contribution guidelines are at [style/CONTRIBUTE.md](https://github.com/ZeLonewolf/openstreetmap-americana/blob/main/style/CONTRIBUTE.md).

Ops. #345 attempts to eliminate source of confusion

**Comment by ZeLonewolf** [comment]
I'm fine centralizing the contrib stuff in root.  The intent of the separate style folder was to have a sibling folder that would have custom layer generation code.  Since we'd need to revision control them together, I think it makes sense for them to share a repo.  However, there's no reason we can't move project-wide stuff up a folder.

**Comment by zekefarwell** [comment]
I support moving the following files into the project root.  That's where they typically live in most projects.  Having them in a subfolder is atypical.

```
style/.gitignore
style/.npmrc
style/.prettierignore
style/.prettierrc.json
style/ACKNOWLEDGEMENTS.md
style/CONTRIBUTE.md
style/package.json
style/package-lock.json
```

**Comment by ZeLonewolf** [comment]
@matkoniecz is the concern expressed in this ticket satisfactorily resolved?  If so, I'd propose to close this ticket and start a new one describing the collapsing of the style subfolder into the repository root.

If not, what more is needed beyond #345?

**Comment by matkoniecz** [comment]
yes, this one is solved

feel free to create one tracking

> collapsing of the style subfolder into the repository root
