### ISSUE TITLE
Shields in Poland

### ISSUE THREAD

**Issue by matkoniecz** [ZeLonewolf/openstreetmap-americana#347]
```
name 	Autostrada A4
network 	pl:motorways
ref 	A4
route 	road
type 	route
wikidata 	Q429672
wikipedia 	pl:Autostrada A4 (Polska)
```

https://www.openstreetmap.org/relation/114014

Shield: https://commons.wikimedia.org/wiki/File:A4-PL.svg

other motorways: https://commons.wikimedia.org/wiki/Category:Diagrams_of_motorway_number_signs_of_Poland

other shields: https://commons.wikimedia.org/wiki/Category:Diagrams_of_route_signs_of_Poland (expressways, national roads, voivodeship roads). 

https://www.openstreetmap.org/relation/334164 - national road

```
name 	Droga krajowa nr 7
name:de 	Landesstraße 7
name:pl 	Droga krajowa nr 7
network 	pl:national
ref 	7
route 	road
type 	route
wikidata 	Q1090066
wikipedia 	pl:Droga krajowa nr 7 (Polska)
```
https://commons.wikimedia.org/wiki/File:DK7-PL.svg

https://www.openstreetmap.org/relation/2342207 - voivodeship road

```
name 	Droga wojewódzka nr 780
network 	pl:regional
ref 	780
route 	road
type 	route
wikidata 	Q10920649
wikipedia 	pl:Droga wojewódzka nr 780
```
https://commons.wikimedia.org/wiki/File:DW780-PL.svg

https://www.openstreetmap.org/relation/112778 - expressway road

```
name 	Droga ekspresowa S7
network 	pl:expressways
ref 	S7
route 	road
type 	route
wikidata 	Q1259569
wikipedia 	pl:Droga ekspresowa S7 (Polska)
```
https://commons.wikimedia.org/wiki/File:Droga_ekspresowa_S7.png

BTW, voivodeship has funny etymology (Polish name is województwo, from wojewoda which meant "[warlord](https://en.wikipedia.org/wiki/Voivode)". Nowadays it remains a name for a public function, but civilian one.

shields in action (from https://40ton.net/autostrada-a4-rozpadla-sie-pod-samochodami-kiedy-droga-zostanie-przebudowana/ ):

![screen03](https://user-images.githubusercontent.com/899988/170277013-f473324e-d5c6-4880-b68d-d308472da1d1.png)

**Comment by matkoniecz** [comment]
hmm, motorways and national roads appear to have the same shield though motorways are associated with blue styling - but it is not appearing directly on shield (except as an icon)

**Comment by jleedev** [comment]
I would interpret the motorway icon as being similar to a D13-3 FREEWAY ENTRANCE and not part of the shield proper. Guide signs from one motorway to another don't seem to use the icon, e.g.: https://goo.gl/maps/GziMDMHEZJN3n9sW8

The blue/green styling might be relevant for turn-by-turn navigation, a hypothetical router could show the "A4" direction as a red shield against a blue background and the "7" direction as a red shield against a green background, if I'm reading this correctly.
