### ISSUE TITLE
Indian Routes (United States)

### ISSUE THREAD

**Issue by claysmalley** [ZeLonewolf/openstreetmap-americana#351]
The Bureau of Indian Affairs (BIA) signposts routes in and around Indian Reservations in the United States. Tagging consensus for these routes seems to have formed around `network=US:BIA`.

Route shields may have up to 3 digits, though 4-digit routes might exist. The Eastern Cherokee Reservation certainly has 4-digit BIA routes, though they aren't signposted with the Indian Route shield (instead, they're next to the street name, as North Carolina's secondary state routes are often signed).

Indian Route shield:

![](https://upload.wikimedia.org/wikipedia/commons/7/75/Indian_Route_591.svg)

**Comment by 1ec5** [comment]
This was a difficult shape to add to Rebusurance. I contorted the shield so much to accommodate the text that it ended up looking like a vessel of some sort, rather than a spear tip.

**Comment by 1ec5** [comment]
[Wikipedia says](https://en.wikipedia.org/wiki/Special:PermanentLink/1060400961#Description) Indian routes use a variety of projectile point shapes depending on the jurisdiction. The diagrams of Indian route shields on Wikimedia Commons [come from](https://commons.wikimedia.org/wiki/Special:PermanentLink/550077550) an [ADOT specification](https://apps.azdot.gov/files/traffic/moas/pdf/m/m01-101.pdf). [Oklahoma](https://oklahoma.gov/odot/about/contact-us/divisions/information-technology/gismgmgmutcdcosesandstandardsigns/route-signs.html) appears to use an identical design. But I don’t have any information about how tribal authorities mark Indian routes.

NMDOT maps take some liberties with the shield shape:

<img width="249" alt="NMDOT 2010 compact" src="https://user-images.githubusercontent.com/1231218/171072064-fedb43f7-31fe-4a8d-a487-908eae07e6b3.png">
<img width="158" alt="NMDOT 2010 full" src="https://user-images.githubusercontent.com/1231218/171072067-cd254f8f-8cd5-4eb1-b54f-feab9548cac6.png">

**Comment by 1ec5** [comment]
The design seen in the Dakotas is from [a 1980 national standard](https://www.bia.gov/sites/default/files/dup/assets/public/pdf/idc-000461.pdf#page=18).
