### ISSUE TITLE
Colored Banners

### ISSUE THREAD

**Issue by ahallification** [ZeLonewolf/openstreetmap-americana#357]
**Colored Banners**
In Vermont, banners match the text color of the shield they modify. From what I can tell, americana has made no such distinction on this so far, and I'm not sure if it has been discussed. Dependent on the color of the shields and the modifier (which doesn't get a background), I think it would be cool to match the texts. Some colors might not work visually.

Action Item: Can we modify the banneredShield text color for banners in Vermont to match the shield color?
I did a quick review of other states and the only one that jumped out to me that could also be a candidate was South Carolina, which matches their banners to the blue shields. Most other banners seem to be paired with black shields.
![Capture](https://user-images.githubusercontent.com/5446730/171685304-c43ae7f3-cea9-459a-a3a0-d1b560954b93.PNG)
![Capture](https://user-images.githubusercontent.com/5446730/171685656-74c40719-9598-4580-894f-4c2f9f05f24c.PNG)

Outside of state shields, it looks like US:I could be explored as well, although I don't know how it would look with the multiple colored shield.

**Comment by claysmalley** [comment]
Currently, we do this with business state routes in Maryland, by using `colorLighten` on a black-and-white design.

The text halo looks a little more dramatic than I remember when I first added these (#295). @ZeLonewolf changed the text halo in #337.

![Screenshot from 2022-06-02 13-18-29](https://user-images.githubusercontent.com/1732117/171687168-c0867657-c285-4c70-b17d-036a193c4428.png)

**Comment by claysmalley** [comment]
Yeah, it's getting chopped off on the sides and top. Here's 200% zoom:

![Screenshot from 2022-06-02 13-37-04](https://user-images.githubusercontent.com/1732117/171691149-3f581fa0-0bbd-4e21-9974-80468002b18a.png)

**Comment by ZeLonewolf** [comment]
Yuck okay.

So my _intent_ in fixing the halo code was for all banners to be standard black with a white/light halo.  I didn't anticipate introducing the behavior which made banners render in the colorLighten color.  So we need to decide:

1. Do we want colored text banners or all black?
2. If they're colored, how do we handle the halo?  Can it always be white or does it need to differ based on the text color?

Separate from all these, the clipping needs to be addressed, at least on the top.

**Comment by claysmalley** [comment]
> I didn't anticipate introducing the behavior which made banners render in the colorLighten color.

You're good; it did that previously. What I was primarily talking about wrt #337 was the wonky halo.

> 1. Do we want colored text banners or all black?

I think it's reasonable to have banner text match the shield color if it only uses white and another color. This can easily be accomplished by changing the SVG to black-and-white and using `colorLighten` to recolor the whole sprite.

> 2. If they're colored, how do we handle the halo?  Can it always be white or does it need to differ based on the text color?

Always white. I think the existing green halo around the above example looks awful.

**Comment by 1ec5** [comment]
Other states like California and Minnesota also use colored banners to match their shields, but the black banner text never bothered me because it’s floating out by itself.

> JS canvas drawing functions have an actual halo-like function, which I switched to instead of the former hack of rendering multiple copies of the text offset by a few pixels in multiple directions.

It’s tricky to ensure contrast when using a blur. A solid halo (what you’re describing as a hack) looks less sophisticated but can be more legible.

> Always white. I think the existing green halo around the above example looks awful.

#203 uses the map’s background color around road name labels to soften the appearance.

**Comment by claysmalley** [comment]
> > Always white. I think the existing green halo around the above example looks awful.
> 
> #203 uses the map’s background color around road name labels to soften the appearance.

I like that approach, though we'd need to make sure `colorLighten` doesn't interfere with it.

**Comment by ZeLonewolf** [comment]
I would suggest that we default all of the banners to black by default, and only set a different color by configured exception in the shield definition.

**Comment by zekefarwell** [comment]
> A solid halo (what you’re describing as a hack) looks less sophisticated but can be more legible.

Honestly the solid halo introduced in #203 look.more sophiaticated to me than blurred halos with partial transparency.  It produces a (faux) knockout affect that looks great and is very legible.  I think using this technique for banners (and probably most other text too) text would work very well.

**Comment by ZeLonewolf** [comment]
> Honestly the solid halo introduced in #203 looks more sophiaticated to me than a blurred halo with partial transparency. It produces a (faux) knockout effect that looks great and is very legible. I think using this technique for banners (and probably most other text too) would work very well.

This should be achievable by editing the following lines:
https://github.com/ZeLonewolf/openstreetmap-americana/blob/d0c1ef17ccf37a7b15748ae6f61250639c37cd1c/style/js/shield_text.js#L244-L245

**Comment by ZeLonewolf** [comment]
With fixes to shield coloration code complete, the next step is to provide a list of network values that should be colored something other than black.

**Comment by 1ec5** [comment]
Historic U.S. Routes could also benefit from a colored banner: #922.

**Comment by 1ec5** [comment]
> Other states like California and Minnesota also post colored banners matching their shields, but the black banner text in this style never bothered me because it’s floating out by itself.

I think the difference is that California and Minnesota have _white_ text against a different-colored background. Since we don’t show the background anyways, it isn’t as jarring. But that doesn’t explain why a black “HIST” above a Historic U.S. Route shield seems off to me. Maybe the unified sign layout is also a factor in that case.
