### ISSUE TITLE
New Zealand State Highway Shields

### ISSUE THREAD

**Issue by ZeLonewolf** [ZeLonewolf/openstreetmap-americana#379]
Proposed is to add support for New Zealand State Highways:
tagging: `network=NZ:SH`
wikipedia: https://en.wikipedia.org/wiki/New_Zealand_state_highway_network
graphics: ![image](https://user-images.githubusercontent.com/3254090/172666533-f5d14220-f60e-42ad-9463-63375e9dd771.png)

**Comment by 1ec5** [comment]
Additionally, New Zealand’s [_Traffic Control Devices Manual_](https://www.nzta.govt.nz/assets/resources/traffic-control-devices-manual/docs/part-2-draft-direction-service-and-general.pdf#page=21) provides for [urban routes](https://www.nzta.govt.nz/resources/traffic-control-devices-manual/sign-specifications/view/961) (marked by a black-on-white pentagon) and [named touring routes](https://www.nzta.govt.nz/resources/traffic-control-devices-manual/sign-specifications/view/964) (marked by one-off shields).

[![urban](https://user-images.githubusercontent.com/1231218/173923844-78d2e6ff-d030-4cf5-b37b-af47b77ed122.png)](https://www.nzta.govt.nz/resources/traffic-control-devices-manual/sign-specifications/view/961)

[![named](https://user-images.githubusercontent.com/1231218/173923902-6cf29757-5e4d-4479-b17a-165690b38624.png)](https://www.nzta.govt.nz/resources/traffic-control-devices-manual/sign-specifications/view/964)

So far, no urban routes have been mapped as route relations, but two touring routes have been tagged [`network=NZ:Touring`](https://www.openstreetmap.org/relation/14143895) and [`network=NZ:Tourist`](https://www.openstreetmap.org/relation/14143156).

**Comment by 1ec5** [comment]
I split out #450 and #451 for the urban and touring route shields, leaving this issue to track only the state highways, which are already properly tagged.
