### ISSUE TITLE
Baldwin Beach Express shield

### ISSUE THREAD

**Issue by claysmalley** [ZeLonewolf/openstreetmap-americana#380]
The Baldwin Beach Express is a highway in Baldwin County, Alabama. It has a shield with simple white text on a green background.

This route is tagged `network=US:AL:Baldwin:Baldwin_Beach_Express`.

![Baldwin_Beach_Express](https://user-images.githubusercontent.com/1732117/162110317-35373979-ae7a-47c5-a8e5-465e578ee984.svg)

**Comment by ZeLonewolf** [comment]
Thanks, I hate it.  What are we going to do with this?

**Comment by claysmalley** [comment]
A green rectangle with the abbreviation "BBX"? I honestly don't know :shrug:

**Comment by ZeLonewolf** [comment]
I tend to agree that an abbreviation is probably more useful on the map than just squeezing down the text to unreadable.
