### ISSUE TITLE
Distinguish county seats from other cities

### ISSUE THREAD

**Issue by 1ec5** [ZeLonewolf/openstreetmap-americana#384]
Currently, state capitals are marked by a star, but many of the same maps that denote state capitals this way also have a special icon for county seats. We should also use a distinct icon, especially at zoom levels where county boundaries aren’t visible yet. County seats are tagged `capital=6`.

<img src="https://user-images.githubusercontent.com/1231218/173008696-fdba34c0-7191-4f8d-9fc7-10fd4585453f.png" width="300" alt="Benchmark Arizona">

**Comment by 1ec5** [comment]
This is blocked by OpenMapTiles, which only includes [`capital`](https://openmaptiles.org/schema/#capital) when it’s set to [`2` or `4`](https://github.com/openmaptiles/openmaptiles/blob/76d5d753d8fae35e4d316f5532461835a3acf36b/layers/place/capital.sql#L4-L7).

**Comment by bgo-eiu** [comment]
capital=6 also seems to be underutilized in a number of places, so this is a good reminder to add it to more county seats (and county seat equivalents, as far as I know there are various non-county entities here and there that can get a capital=6)

**Comment by 1ec5** [comment]
County seats tagged with `capital=6` ([example](https://www.openstreetmap.org/node/154114470)) now have `capital` set to `6` in the tiles:

<img src="https://github.com/ZeLonewolf/openstreetmap-americana/assets/1231218/8841bbfb-7462-4088-896a-8c7d0f2fe493" width="240" alt="Georgetown: capital: 6">

However, generally speaking, this tagging scheme is only reliable in Alabama. Elsewhere, most county seats [lack `capital=6`](https://qlever.cs.uni-freiburg.de/osm-planet/RGNbuH) ([example](https://www.openstreetmap.org/node/153995961)):

<img src="https://github.com/ZeLonewolf/openstreetmap-americana/assets/1231218/baef6caf-fb79-46d5-b230-6cb7ea99dae3" width="1728" alt="A map of 2,660 county seats, virtually all of the county seats in the contiguous United States minus those of Alabama.">

There’s an alternative tagging scheme that’s much more common: virtually every county seat is [an `admin_centre` member of a county boundary relation](https://qlever.cs.uni-freiburg.de/osm-planet/qcih7V):

<img src="https://github.com/ZeLonewolf/openstreetmap-americana/assets/1231218/9bea17b2-3042-4a0f-9af0-473fc2e9ccd5" width="1728" alt="A map of 84 county seats, mostly in Connecticut and Wisconsin.">

However, OpenMapTiles doesn’t support this alternative tagging scheme. Either tagging scheme could be considered correct, depending on your point of view. After all, the place is the seat of a government, not a boundary, but we don’t map governments.

Either way, it would be great to be able to finally distinguish county seats somehow. Not only should they get a different icon, but they could also appear at lower zoom levels than other places of similar population.

**Comment by quincylvania** [comment]
[Here](https://overpass-turbo.eu/s/1Lm6) is an overpass query to find `admin_centre` nodes for counties that are missing a `capital` tag. It looks like Alabama isn't mapped this way yet, but I think its county seat place nodes are just missing wikidata tags.

**Comment by 1ec5** [comment]
Forgot to link to where we’re chipping away at this problem:

https://community.openstreetmap.org/t/tagging-county-seats-on-boundary-relations-versus-place-points/112952

**Comment by 1ec5** [comment]
Thanks to @quincylvania, all the county seats and equivalents have been tagged with `capital=*`, so this issue is unblocked.
