### ISSUE TITLE
Add attribution notice

### ISSUE THREAD

**Issue by ZeLonewolf** [ZeLonewolf/openstreetmap-americana#39]
Somewhere on index.html, we need to add a visible:

© OpenMapTiles © OpenStreetMap contributors

**Comment by zekefarwell** [comment]
We also need to add MapTiler attribution while we're relying on their cloud service.
https://www.maptiler.com/cloud/terms/

> It is required to indicate: “© MapTiler" with a link to https://maptiler.com/copyright, on all maps. 

> **Free plan maps require the logo.** It is required to place the MapTiler logo, with a link to https://maptiler.com/, on all maps in case you are not subscribed to any of the commercial plans of the Service.
