### ISSUE TITLE
Shields of Australia

### ISSUE THREAD

**Issue by claysmalley** [ZeLonewolf/openstreetmap-americana#397]
[Routes in Australia](https://en.wikipedia.org/wiki/Highways_in_Australia#Route_numbering_systems) were originally given a hierarchical numbering scheme with different shields for National Highways, National Routes and State Routes, though there has been an organized effort to nationally standardize on an alphanumeric scheme and replace signage with rectangular shields. Notably, Western Australia (the largest state by area, taking up one third of the continent) has not adopted this scheme and retains the old hierarchical system. There are a few odds and ends, like an Alternate National Route and a color-swapped alphanumeric rectangle for toll roads, but the following shields should be enough for basic support.

Most numbered routes in Australia are covered by `route=road` relations, but `network=*` tagging is not country-prefixed. There are a number of `network=*` values in Australia, including `MR`, `NH`, `NR`, `S` and `T`. Documentation is limited on this tagging scheme. A decision would need to be made on whether this tagging scheme is sufficient, and whether it is appropriate mapper feedback to support it.

New alphanumeric shield (nationwide except for Western Australia):
![AUS_Alphanumeric_Route_B83](https://user-images.githubusercontent.com/1732117/173210618-d643401c-8db8-40bb-a328-54a960571fb7.svg)

National Highway shield (Western Australia, Tasmania):
![Australian_national_highway_1](https://user-images.githubusercontent.com/1732117/173210622-46b03c71-7fdf-47b9-b109-0e82be461312.svg)

National Route shield (Western Australia, Queensland):
![Australian_national_route_13](https://user-images.githubusercontent.com/1732117/173210621-93bbdef0-9851-41fe-a4df-c6987327d52d.svg)

State Route shield (Western Australia, Queensland, Victoria):
![Australian_state_route_66](https://user-images.githubusercontent.com/1732117/173210620-89fd5fcf-74e3-4cf2-b574-07b95033a4fd.svg)

Metroad shield (Queensland):
![AUS_Metroad_5](https://user-images.githubusercontent.com/1732117/173210617-f675633e-d92b-481f-b2ca-33334c36ba9b.svg)

Tourist Drive shield (most states):
![Australian_Tourist_Drive_357](https://user-images.githubusercontent.com/1732117/173211146-14de4a22-dcbe-46af-912d-fbaa371ac55d.svg)

**Comment by claysmalley** [comment]
Here's some shield SVGs: ![shield_pent_brown_2](https://user-images.githubusercontent.com/1732117/178388402-d18573dd-1375-44c0-964e-df5c45f6013d.svg) ![shield_pent_brown_3](https://user-images.githubusercontent.com/1732117/178388400-e7644b02-0cd5-411e-9295-ab1c66b0e736.svg) ![shield_home_green_yellow_2](https://user-images.githubusercontent.com/1732117/178388405-be12a601-7312-4e96-b631-83508a9d15d0.svg) ![shield_home_green_yellow_3](https://user-images.githubusercontent.com/1732117/178388404-f1384f7f-2e93-4671-9fab-4727ba5b92cb.svg) ![shield_au_s](https://user-images.githubusercontent.com/1732117/178388406-1fffa91a-e50c-4f18-ae47-d7d81c620c4a.svg) ![shield_au_mr](https://user-images.githubusercontent.com/1732117/178388408-2a626e7e-933e-4753-88c6-5279a40b0c85.svg)

**Comment by DianAgesson** [comment]
Hello,

The previous Australian tagging guidelines for route networks did not implement an AU: prefix. The guidelines have since been updated and agreed to by the community, but have not yet been implemented. https://wiki.openstreetmap.org/wiki/Australian_Tagging_Guidelines/Roads#Routes

It may take some time for this change to propagate through the country, but will hopefully provide some context for this issue when implemented.

Dian

**Comment by ZeLonewolf** [comment]
Thanks @DianAgesson for the update.  Once the tagging changes are in place, please let us know so that the tileserver can be updated.

**Comment by claysmalley** [comment]
Wikipedia lists a few more route networks in Australia that might be missing from the new guidelines:

* the two remaining Metroads in Brisbane
* alphanumeric toll roads in Queensland and Victoria, which have a blue background
* Route ALT A2 in Queensland, an alphanumeric route with an "ALT" banner above

@DianAgesson Do you have more context on these routes and whether they deserve shield support?

**Comment by DianAgesson** [comment]
Hey @claysmalley !

Wikipedia is a bit of a mixed bag at the moment with Australian routes; the editors there seem to have made edits based on future plans for route numbers and ended up outpacing the reality on the ground!

Unfortunately there are some shields that, despite appearing on a couple of routes, are prominent enough that people would notice. This includes the Metroutes, the National Alternate Highway Shield, and the ALT A2.

The blue/yellow toll road shield would be quite nice to have, but locals would still recognise the road with the standard green shield if it was used.

**Comment by claysmalley** [comment]
Thanks for the reply @DianAgesson.

> Unfortunately there are some shields that, despite appearing on a couple of routes, are prominent enough that people would notice. This includes the Metroutes, the National Alternate Highway Shield, and the ALT A2.

It looks like only the National Alternate Highway is listed in the new guidelines. As long as there aren't tagging guidelines for the other one-off routes, we won't know how to support them.

> The blue/yellow toll road shield would be quite nice to have, but locals would still recognise the road with the standard green shield if it was used.

It's a judgment call for the Australian OSM community whether tolled segments of roads deserve a different `network` value. As for OSM-Americana, roads are color-coded based on the value of `toll`, so there's less of a need to style the route shields differently. But if the Australian community wants the flexibility to style toll road shields differently in other renderers, it would be better to assign them their own `network` value.

**Comment by DianAgesson** [comment]
Thanks Clay. I’ll bring the issue up on the discord and fix the gaps in the guidelines accordingly. :)
