### ISSUE TITLE
Road line styles

### ISSUE THREAD

**Issue by ZeLonewolf** [ZeLonewolf/openstreetmap-americana#4]
This ticket is a central point to capture discussion on how road lines at various levels should be styled.  Common elements of road styles in American road maps included:
1. Separate colors for toll vs free motorways
2. A sequence of decreasing styles for roads of decreasing importance.  For example: Cased Red->Red->Black->Gray is a common theme in AAA road maps.
3. Road styles based on importance rather than by network.  We may want to use a scheme that is a hybrid approach between highway classification and road network.
4. Road labels on the sides of road lines, rather than squeezed inside the casing.
5. Cased white inners for divided carriageways.

A baseline structure at a medium zoom might look something like this:
- `highway=motorway` -> Cased red
- `highway=trunk` + US highways -> thick red
- `highway=primary` + state highways -> red
- `highway=secondary` + county highways -> black
- `highway=tertiary` -> thin black
- `highway=unclassified`, `highway=residential` -> thin gray

**Comment by Mashin6** [comment]
Note: tunnels on motorways should render the same as non-tunnel on low zoom <7
![image](https://user-images.githubusercontent.com/5265707/125530476-b16f023c-4ba2-409c-8e7e-cd387abbd6e6.png)

**Comment by ZeLonewolf** [comment]
This issue is resolved now that #62 has created an initial implementation of road styles down to tertiary.  Additional work is still needed to add the lesser classes of road, such as track, service, residental, unclassified, and so forth, however, the basic pattern of American-style road rendering is in place.
