### ISSUE TITLE
Shields of Mexico

### ISSUE THREAD

**Issue by claysmalley** [ZeLonewolf/openstreetmap-americana#404]
**(EN)**

Federal Highways of Mexico have a unique black-on-white shield design. Almost all states of Mexico use a similar design with a square top for their State Highways.

Many numbered routes in Mexico are covered by `route=road` relations, but `network=*` tagging is limited. Values of `network=*` in Mexico are country-prefixed, but it is unclear which values correspond to Federal Highways, highways of Mexico City, and highways of the State of Mexico. A decision would need to be made on whether this tagging scheme is sufficient, and whether it is appropriate mapper feedback to support it.

**(ES)**

Las Carreteras Federales de México tienen un diseño único de escudo en blanco y negro. Casi todos los estados de México utilizan un diseño similar con una parte superior cuadrada para sus Carreteras Estatales.

Muchas rutas numeradas en México están cubiertas por las relaciones `route=road`, pero el etiquetado `network=*` es limitado. Los valores de `network=*` en México tienen el prefijo del país, pero no está claro qué valores corresponden a Carreteras Federales, carreteras de la Ciudad de México y carreteras del Estado de México. Sería necesario tomar una decisión sobre si este esquema de etiquetado es suficiente y si este soporte brindará una buena retroalimentación a los mapeadores.

----

Federal Highway shield:
Rótulo de las carreteras federales:
<img src="https://user-images.githubusercontent.com/1732117/173255177-bd4317cc-f0ff-49c1-b64d-2c093dad6e5f.svg" alt="Carretera_federal_45" width="200" /> <img src="https://user-images.githubusercontent.com/1732117/173255178-2c2d26d4-5292-4ddf-8186-4738d8b2fc0d.svg" alt="Carretera_federal_2D" width="200" />

State Highway shield:
Rótulo de las carreteras estatales:
<img src="https://user-images.githubusercontent.com/1732117/173255176-a17c8141-720c-4d89-acb5-e66d92c82948.svg" alt="Carretera_estatal_176_(Sonora)" width="200" />

**Comment by 1ec5** [comment]
#411 tracks Jalisco’s state and rural highway shields.

**Comment by 1ec5** [comment]
> it is unclear which values correspond to Federal Highways, highways of Mexico City, and highways of the State of Mexico

Currently, `MX:`-prefixed `network` values are a mix of [two-letter and three-letter state codes](https://es.wikipedia.org/wiki/Especial:EnlacePermanente/142457363). Various inconsistent tagging schemes are in use for federal toll highways and México State highways:

* [`MX:MX`](https://taginfo.openstreetmap.org/tags/network=MX%3AMX) – carreteras federales, incluyendo las autopistas
* [`MX:MX:Cuota`](https://taginfo.openstreetmap.org/tags/network=MX%3AMX%3ACuota) – autopistas de peaje
* [`MX:MX:D`](https://taginfo.openstreetmap.org/tags/network=MX%3AMX%3AD) – el mismo (“D” = directo, según el escudo)
* [`MX:MEX`](https://taginfo.openstreetmap.org/tags/network=MX%3AMEX) carreteras estatales del Estado de México (según ISO&nbsp;3166-2 y el escudo)
* [`MX:EM`](https://taginfo.openstreetmap.org/tags/network=MX%3AEM) – el mismo (“EM” = Estado de México)
* [`MX:MEX-EM`](https://taginfo.openstreetmap.org/tags/network=MX%3AMEX-EM) – el mismo

No `network` value currently represents Mexico City’s _eje_ routes (#405).

**Comment by 1ec5** [comment]
A user in the Latin American Telegram chat suggested @mdelatorre‘s [Mexico road signs plugin for JOSM](https://github.com/mdelatorre/RoadSignsMX/) as a resource. We should make sure this style and that plugin align on any tagging for these routes.

**Comment by mdelatorre** [comment]
Mexico road signs preset for RoadSigns JOSM plugin uses the specifications
mandated by the "Secretaria de Comunicaciones y Transportes [SCT]" which is
the authority in these matters in México.
