### ISSUE TITLE
Shields of Mexico City

### ISSUE THREAD

**Issue by claysmalley** [ZeLonewolf/openstreetmap-americana#405]
**(EN)**

Mexico City has a unique grid of one-way boulevards, called _ejes viales_ (road axes). The Central Axis runs north-south, and all other axes are numbered sequentially away from the center of the city.

Currently, none of the axes are in `route=road` relations. These would need to be mapped before support can be added to this project.

**(ES)**

La Ciudad de México tiene una cuadrícula única de bulevares de un solo sentido, llamados ejes viales. El eje central corre de norte a sur, y todos los demás ejes están numerados secuencialmente desde el centro de la ciudad.

Actualmente, ninguno de los ejes está en relaciones `route=road`. Estos deberían mapearse antes de que se pueda agregar soporte a este proyecto.

----

Central Axis shield:
Rótulo del eje central:
<img src="https://user-images.githubusercontent.com/1732117/173255180-aa3f6c87-9117-4df7-afe7-8faa13c2e2c9.jpg" alt="EJE_CENTRAL" width="200" />

Shields of North, South, West and East axes:
Rótulos de los ejes del norte, del sur, del oeste y del este:
<img src="https://user-images.githubusercontent.com/1732117/173255181-916b4020-ab21-445c-9aa8-0e452bd06978.png" alt="Eje1Norte" width="200" /> <img src="https://user-images.githubusercontent.com/1732117/173255182-505e2fd7-52da-4654-aafe-192b7cc85e66.png" alt="Eje2ASur" width="200" /> <img src="https://user-images.githubusercontent.com/1732117/173255183-bc4ff575-2ce2-44e0-bb52-45587381133f.png" alt="Eje4Poniente" width="200" /> <img src="https://user-images.githubusercontent.com/1732117/173255184-28e2ca26-b486-4a9b-8c95-5a06f032cc33.png" alt="Eje6Oriente" width="200" />

**Comment by michaelblyons** [comment]
Don't and colors make me think "video game" 😅

**Comment by claysmalley** [comment]
I'm not convinced the shields actually look like that in real life. All evidence I can find of them shows them all as white-on-green.

Mapillary: [Eje central](https://www.mapillary.com/app/?lat=19.395280838013&lng=-99.145927429199&z=17&pKey=478300330106396&focus=photo&x=0.49343636816134145&y=0.3550656831295401&zoom=1.8994510475162394), [Eje 6 sur](https://www.mapillary.com/app/?lat=19.378108978271044&lng=-99.14841461181601&z=18.604618612467252&pKey=769178713709945&focus=photo&x=0.5988986931198816&y=0.23827503519163523&zoom=1.470303975983167)

**Comment by 1ec5** [comment]
I’ve only ever seen them in green as well. What do they look like on other maps, such as print maps?

**Comment by 1ec5** [comment]
There are some photos online of Eje Central having [a colored shield](https://twitter.com/andreslajous/status/1203354112063991809/photo/1) and Eje 2 Sur having [a black-on-white shield](https://cletofilia.com/inauguran-carril-trolebici-en-eje-2-sur-de-la-cdmx/). Maybe it’s newer?

**Comment by claysmalley** [comment]
I'm not sure. Most of the info I can find online indicates that the colorful designs with the unique typeface are what they looked like when they were first introduced, but today's signage is monochrome with Highway Gothic.

If any Chilangos out there could give more context on how these route shields look in real life and on maps, we'd appreciate it :smile:
