### ISSUE TITLE
Systematic organization of map legend sources

### ISSUE THREAD

**Issue by michaelblyons** [ZeLonewolf/openstreetmap-americana#412]
I see a lot of photos in this repo's issues and PRs that are of the form "Here's a picture of Utah's official state map legend" (or Cincinnati, or wherever).

Is it worth organizing them into some massive chart (or data structure from whence multiple charts can be derived) such that it's easy to see what each stroke or fill style is empirically used for? This would be a reference for asserting that "80% of states use a pink line to mean a motorway."

**Comment by 1ec5** [comment]
Many of these photos come from [my map collection](http://notes.1ec5.org/archives/2015/02/14/maps.html). I’ve posted [most of these legends](https://drive.google.com/drive/folders/16vGgCNErSecXUMwzFFyu16Q3nyOzCZN8?usp=sharing) to Google Drive, but I’m reluctant to formally make them into part of this repository’s codebase, since most are still under copyright.

**Comment by ZeLonewolf** [comment]
While our use of pictures of bits of maps for scholarly analysis almost certainly qualifies as fair use, I'm similarly uncomfortable with putting pieces of copyrighted maps into the repository code base and calling it public domain.  Creating some sort of archive of these clips for cartographic analysis would certainly be useful but it would need to exist somewhere outside of this github repo (and for the same reason, outside of the OSM wiki).

**Comment by michaelblyons** [comment]
I am fine with this outcome, but I did want to clarify, RE

> I'm similarly uncomfortable with putting pieces of copyrighted maps into the repository code base and calling it public domain.

I did not expect to put photos in the data source. Not even necessarily an SVG. Something that would let one build a chart like this:

| Shape  | Fill | Border | Zoom | Most used as | Most % | Next Most | Next % |
| ------------- | ------------- | - | - | - | - | - | - |
| Line | 3px pink | 1px red | 12 | motorway | 68% | primary | 12% |
| Rounded Square | 5px white | 2px black | 12 | junction | 83 % | city 4 |  7% | 

Say from data like this:

```jsonc
{
    "sources": [
        {
            "id": 12345,
            "name": "City of ____ DOT",
            "url": null,  // maybe?
            "zoom": 12,
        },
    ],
    "features": [
        {
            "source": 12345,
            "name_source": "primary highway",
            "name_osm": "motorway",
            "shape": {
                "type": "line",
                "description": "3x center with 1x casing",
            },
            "colors": {
                "fill": {
                    "original": "#RRGGBB",
                    "simple": "pink",  // Some simplified palette
                    "width": 3,
                },
                "outline": {
                    "original": "#RRGGBB",
                    "simple": "red",   // Some simplified palette
                    "width": 1,
                },
            },
        },
        {
            "source": 12345,
            "name_source": "junction",
            "name_osm": null,
            "shape": {
                "type": "rounded square",
                "description": "5x center with 2x border",
            },
            "colors": {
                "fill": {
                    "original": "#FFFFFF",
                    "simple": "white",  // Some simplified palette
                    "width": 5,
                },
                "outline": {
                    "original": "#040404",
                    "simple": "black",   // Some simplified palette
                    "width": 2,
                },
            },
        }
    ]
}
```
