### ISSUE TITLE
Blank shields are 20x20

### ISSUE THREAD

**Issue by jleedev** [ZeLonewolf/openstreetmap-americana#440]
This looks weird, there's a lot of empty space:

![Screenshot 2022-06-19 21 47 07](https://user-images.githubusercontent.com/23022/174511597-d5f65243-c6c4-4384-8a3e-89a527783dd9.png)

Reason is the road has two empty routes on it, which render as 20x20 transparent:

![Screenshot 2022-06-19 21 51 15](https://user-images.githubusercontent.com/23022/174511780-277a7038-f8f5-4905-937f-e7f66523d3f4.png)

And because US:NY:STE ranks lower in the tile generation.

Would be preferable to not generate these entirely blank shields:

![Screenshot 2022-06-19 21 47 12](https://user-images.githubusercontent.com/23022/174511850-a2cb9866-6adf-45aa-97f1-265a0d419533.png)

(Note that this logs a warning, once, when we silently refuse to load an image.)

Or generate a 1x1 transparent, which only adds a little bit of unnecessary space:

![Screenshot 2022-06-19 21 49 43](https://user-images.githubusercontent.com/23022/174511860-9f787e35-8d8a-4267-a96f-7941ab6142ca.png)

**Comment by claysmalley** [comment]
I think it's better to not generate the shields, even if it logs a warning. The spacing with the 1x1 blank shield just looks like a rendering error, and doesn't give much in the way of mapper feedback.
