### ISSUE TITLE
New Zealand urban route shields

### ISSUE THREAD

**Issue by 1ec5** [ZeLonewolf/openstreetmap-americana#450]
New Zealand’s [_Traffic Control Devices Manual_](https://www.nzta.govt.nz/assets/resources/traffic-control-devices-manual/docs/part-2-draft-direction-service-and-general.pdf#page=21) provides for [urban routes](https://www.nzta.govt.nz/resources/traffic-control-devices-manual/sign-specifications/view/961) marked by a black-on-white pentagon.

[![urban](https://user-images.githubusercontent.com/1231218/173923844-78d2e6ff-d030-4cf5-b37b-af47b77ed122.png)](https://www.nzta.govt.nz/resources/traffic-control-devices-manual/sign-specifications/view/961)

So far, no urban routes have been mapped as route relations.

_Originally posted by @1ec5 in https://github.com/ZeLonewolf/openstreetmap-americana/issues/379#issuecomment-1156915732_

**Comment by 1ec5** [comment]
> So far, no urban routes have been mapped as route relations

Actually, [29 urban routes](https://overpass-turbo.eu/s/1jEi) in [Auckland](https://en.wikipedia.org/wiki/Auckland_urban_route_network), Hamilton, and New Plymouth have been mapped as relations, but without a `network` tag. In order for us to render these shields, we need them to be tagged with something like `network=NZ:urban` or `network=NZ:UR`.

**Comment by k-yle** [comment]
Hi, New Zealander here 👋 As @1ec5 noted, all urban routes are mapped, just without a `network` tag. (there's also [one in Christchurch](https://osm.org/relation/87729)) 

> we need them to be tagged with something like `network=NZ:urban` or `network=NZ:UR`

I'm happy to make this change if no one else does. Does anyone here have a suggestion for the best tag value, to be consistent with other countries?

---

Side note: There are a few routes that use the white urban-route shield, but are not in "urban" areas. (e.g. [Route 70](https://osm.org/relation/13708177), [Route 72](https://osm.org/relation/5381607), [Route 40](https://osm.org/relation/13705226), [Route 67](https://osm.org/relation/11337976)). This is beacuse they were downgraded from (red) [state highway shields](https://github.com/ZeLonewolf/openstreetmap-americana/issues/379).

I'm not sure whether these weird routes should also get tagged as `network=NZ:Ur[ban]`, or whther we need another network tag with identical rendering.

**Comment by 1ec5** [comment]
> I'm happy to make this change if no one else does. Does anyone here have a suggestion for the best tag value, to be consistent with other countries?

Thank you! There are two predominant styles:

* `network=NZ:urban` would be consistent with countries that have relatively simple route designations that are homogenous across the country. The part at the end is a keyword that describes the kind of route according to typical OSM naming conventions.
* `network=NZ:UR` would be consistent with countries that have more complex route designations needing disambiguation, for example provinces with their own unique shield designs, or [bannered routes](https://en.wikipedia.org/wiki/Special_route).

It isn’t a big deal either way as long as it’s consistent. With the existing tags like `network=NZ:SH`, it looks like New Zealand has been taking the latter approach, so `network=NZ:UR` would be more consistent, if not as self-documenting.

> Side note: There are a few routes that use the white urban-route shield, but are not in "urban" areas. (e.g. [Route 70](https://osm.org/relation/13708177), [Route 72](https://osm.org/relation/5381607), [Route 40](https://osm.org/relation/13705226), [Route 67](https://osm.org/relation/11337976)). This is beacuse they were downgraded from (red) [state highway shields](https://github.com/ZeLonewolf/openstreetmap-americana/issues/379).
> 
> I'm not sure whether these weird routes should also get tagged as `network=NZ:Ur[ban]`, or whther we need another network tag with identical rendering.

Good to know. If I’m reading the TCD manual correctly, these are [urban route indicators](https://www.nzta.govt.nz/resources/traffic-control-devices-manual/sign-specifications/view/961) for [urban routes](https://www.nzta.govt.nz/assets/resources/traffic-control-devices-manual/docs/part-2-draft-direction-service-and-general.pdf#page=21), which are designated by [road controlling authorities](https://www.nzta.govt.nz/assets/Roads-and-Rail/amds/amds-road-controlling-authorities-list-v2.pdf). It doesn’t look like it particularly matters whether the route traverses an urban area.

**Comment by k-yle** [comment]
All 42 urban routes now have `network=NZ:UR` :)

**Comment by 1ec5** [comment]
Fixed in #473.
