### ISSUE TITLE
Turkish state highway shields

### ISSUE THREAD

**Issue by claysmalley** [ZeLonewolf/openstreetmap-americana#494]
State highways of Turkey have a simple white-on-blue rectangular shield.

These highways are currently tagged with `network=TR-roads`, which is not in the expected format. `network` must begin with `TR:` for highway networks that belong to Turkey. Support can be added for these shields if the Turkish OSM community devises a better value of `network` to represent state highways.

<img width="200" alt="D010-TR" src="https://user-images.githubusercontent.com/1732117/178856304-cd8b4841-2ee1-4f4a-9adc-39a5259fb66d.svg" />

**Comment by ZeLonewolf** [comment]
The tagging of highways in Türkiye nationwide is currently being discussed on their mailing list:
https://lists.openstreetmap.org/pipermail/talk-tr/2024-January/000570.html
