### ISSUE TITLE
Broken in Safari MacOS/iOS

### ISSUE THREAD

**Issue by ctkjose** [ZeLonewolf/openstreetmap-americana#499]
1. "use strict" causes americana not to load in Safari due to non-standard class functions in "road.js". The following  functions "fill", "casing", and "surface" use an assignment. (either way everything loaded with import will be under strict mode).

2. americana.js is using import statements that are supported by Chrome but not standard compliance ([MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import)) 

Right now [the spec](https://html.spec.whatwg.org/multipage/webappapis.html#resolve-a-module-specifier) requires that a module resource specifier start with either `/` or `./`.  Extension less module names are a Node thing and not ES6.

Also loading no JS content in particular "css" (per mime/type).

```js
import * as maplibregl from "maplibre-gl";
import "maplibre-gl/dist/maplibre-gl.css";
```

Also references to the SampleControl that is not included in the project are a bummer...

3.  search.js  has a similar issue:

```js
import * as maplibregl from "maplibre-gl";
import "./search.css";
```

4. CSS content should be loaded by other means (maplibre-gl.css, search.css)

**Comment by zekefarwell** [comment]
I just tested in Safari 15.5 and found the map working as expected (there are some known issues).  What version of Safari are you using?

**Comment by jleedev** [comment]
> 1. "use strict" causes americana not to load in Safari due to non-standard class functions in "road.js". The following functions "fill", "casing", and "surface" use an assignment. (either way everything loaded with import will be under strict mode).

I feel like that's probably not the actual cause; in a module script I expect that `"use strict";` would be a no-op. They can be removed as a clean up though.

Says here that class fields should be supported as of Safari 14.1: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/Public_class_fields#browser_compatibility

Could adjust esbuild's target if we need.

> 2. americana.js is using import statements that are supported by Chrome but not standard compliance ([MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import))

Chrome does not support these either. They are used by bundlers.

Did you do `npm run build`?

> Also references to the SampleControl that is not included in the project are a bummer...

Correct, `npm install` fetches this.

> CSS content should be loaded by other means (maplibre-gl.css, search.css)

You'll also notice that there is no file named `americana.css`, referenced from `index.html`. The bundler creates this when you do `npm run build`.

**Comment by ctkjose** [comment]
Im using Safari, Version 13.1.3 

Im in effect ran build and install
