### ISSUE TITLE
Aerialways

### ISSUE THREAD

**Issue by claysmalley** [ZeLonewolf/openstreetmap-americana#500]
In the US, the average person might associate aerialways with ski resorts or scenic mountain lookouts, but aerial gondolas are increasingly becoming integral parts of public transit networks in mountainous cities around the world. In South America alone, aerial gondolas function as feeders for the rail-based transit networks in Medellín and Caracas, and the backbone of the transit network in La Paz, Bolivia. At least one aerial gondola in the US is oriented towards public transit: the Portland Aerial Tram, in Oregon.

Most US ski resort maps show aerialways as thick red lines with square caps. TriMet's official map shows the Portland Aerial Tram as a dark gray dashed line:

![Screenshot from 2022-07-17 21-49-08](https://user-images.githubusercontent.com/1732117/179434714-ed40c604-8d8d-4ac5-bff4-d080237dd64f.png)

**Comment by ZeLonewolf** [comment]
+1 for the idea of drawing aerialways in the James Niehues style.  Are there aerialways that cross a motorway?

**Comment by 1ec5** [comment]
To state the obvious, aerial tramways should not look like railroad tracks: https://github.com/ZeLonewolf/openstreetmap-americana/issues/101#issue-1115515924.

**Comment by quincylvania** [comment]
> Are there aerialways that cross a motorway?

- Crossing motorway in NYC: https://www.openstreetmap.org/way/22886820
- Crossing motorway in Mexico City: https://www.openstreetmap.org/way/732032987
- Crossing motorway in La Paz: https://www.openstreetmap.org/way/303448772
- Crossing trunk in Medellín: https://www.openstreetmap.org/way/481867178
