### ISSUE TITLE
Fix motorway link connectivity in zoom 10-12

### ISSUE THREAD

**Issue by ZeLonewolf** [ZeLonewolf/openstreetmap-americana#53]
Currently, motorway links gap in the zoom 10-12 range.  Instead, we should render them thin a little lower in zoom and then transition to rendering them thick so it all blends in at junctions.

Example below:

Location: https://zelonewolf.github.io/openstreetmap-americana/#11.82/50.91347/7.05276
![image](https://user-images.githubusercontent.com/3254090/126917755-5dbd4340-859e-44e1-9ad2-d49456b7d133.png)

**Comment by zekefarwell** [comment]
It looks like to fully fix all instances of this we'd need to render motorway links down to zoom 7 or 8.  It seems that zoom 9 is the lowest they are included in OpenMapTiles.  My attempted fix for this still shows some small gaps at zoom 8 and lower even though the minzoom is set to 7 for motorway links.

Gaps at zoom 8.95:
![zoom-8 95-gaps](https://user-images.githubusercontent.com/281482/127034435-000327de-f8a1-48a6-94fb-0bdcf66287e6.png)

No gaps at zoom 9.01:
![zoom-9 01-no-gaps](https://user-images.githubusercontent.com/281482/127034477-a78ef20e-8388-4f14-ab0c-053ac09babcb.png)
