### ISSUE TITLE
Map routes of Tennessee

### ISSUE THREAD

**Issue by claysmalley** [ZeLonewolf/openstreetmap-americana#540]
Relation coverage of Tennessee state routes is largely complete, but the majority of routes follow the outdated tagging scheme `network=US:TN`. These route relations need to be split and retagged to `US:TN:primary` or `US:TN:secondary`, according to their signage.

This [Overpass query](https://overpass-turbo.eu/s/1lqF) highlights `route=road` relations in Tennessee, color-coded by the value of `network=*`:
* gray: missing `network=*`
* red: `network=US:TN`
* blue: `network=US:TN:primary` or subnetwork
* green: `network=US:TN:secondary` or subnetwork
* purple: `network=US:TN:McMinn` (county roads)

This [wiki page](https://wiki.openstreetmap.org/wiki/Tennessee/State_Route_Relations) tracks the mapping of the individual relations.

**Comment by michaelblyons** [comment]
> highlights `route=road` relations in Puerto Rico, 

You mean Tennessee?

**Comment by claysmalley** [comment]
fixed

**Comment by 1ec5** [comment]
By the way, I’m still using `network=US:TN` for route superrelations that incorporate a mix of primary and secondary route segments. Would that be a problem? It should be possible to exclude superrelations from the query by recursing down and subtracting the properly tagged members from the original set.

**Comment by claysmalley** [comment]
> It should be possible to exclude superrelations from the query by recursing down and subtracting the properly tagged members from the original set.

I'm gonna need you to translate that to Overpass QL for me...

**Comment by jleedev** [comment]
Looks like you're already ignoring superrelations here:

```
{{geocodeArea:Tennessee}}->.searchArea;

(
  relation[route=road][ref][network~"^US:TN"](area.searchArea);
  relation[route=road][ref][!network](area.searchArea);
);

out body;
>;
out skel qt;
```

**Comment by 1ec5** [comment]
Oh, I just misunderstood the purpose of the query, without being able to really tell on my phone at the time. It highlights all the routes, so including the `route=road` `network=US:TN` superrelations isn’t a problem because they get covered up by the blue and green `route=road` `network=US:TN:primary`/`secondary` relations anyways.

**Comment by claysmalley** [comment]
Mapping is finished, until TNDOT opens a new highway.
