### ISSUE TITLE
Parks rendering with outdated name tags?

### ISSUE THREAD

**Issue by m-hue** [ZeLonewolf/openstreetmap-americana#566]
It appears that parks may be rendering with incorrect/outdated names.
The example I stumbled across is Pritzker Park in Chicago IL (way 73687739):
https://zelonewolf.github.io/openstreetmap-americana/#18.79/41.8774072/-87.6279512

The correct spelling is Pritzker Park with a K. It renders as Pritzger Park with a G. Looking at the object history, it appears that it was misspelled when the park had been originally added to OSM back in 2010, but the name was fixed in 2011 and remained correct ever since, yet the old name is still rendering in Americana.

**Comment by m-hue** [comment]
<img width="299" alt="PritzkerPark_Map" src="https://user-images.githubusercontent.com/20384411/203899637-f43d0bb8-a02d-4d84-9732-ccfd6f7bba26.png">

**Comment by m-hue** [comment]
<img width="770" alt="PritzkerPark_History" src="https://user-images.githubusercontent.com/20384411/203899686-4581b083-ade1-49c0-a695-0b09aa13e132.png">

**Comment by zekefarwell** [comment]
When objects have a `wikidata` tag, OpenMapTiles pulls in the Wikidata name and unfortunately gives it a higher priority than the name from OSM.   That's probably the issue here.
https://www.wikidata.org/wiki/Q49546246

**Comment by 1ec5** [comment]
The vector tiles are getting this name from [this Wikidata item](https://www.wikidata.org/wiki/Q49546246), which got the name from the [Cebuano Wikipedia](https://ceb.wikipedia.org/wiki/Pritzger_Park), which got the name from GNIS. (The GNIS entry has been archived, but the feature ID is still valid.) I’ve updated both Wikidata and Wikipedia with the correct spelling, but it won’t be reflected on the map until the next time the vector tiles are updated.

**Comment by m-hue** [comment]
Great, thank you!
