### ISSUE TITLE
Install right-to-left plugin for Arabic and Hebrew

### ISSUE THREAD

**Issue by 1ec5** [ZeLonewolf/openstreetmap-americana#580]
When the user’s preferred language is Arabic or Hebrew, no labels appear on the map:

![😶](https://user-images.githubusercontent.com/1231218/204120577-c59bef22-fa7a-4cd3-8806-a148fbde1a40.png)

GL JS refuses to render Arabic and Hebrew text unless the [mapbox-gl-rtl-text](https://github.com/mapbox/mapbox-gl-rtl-text/) plugin is installed. This is a pretty hefty plugin, so it might only make sense to load it if the user preference includes either of these languages.

/ref https://github.com/ZeLonewolf/openstreetmap-americana/pull/578#discussion_r1032850494

**Comment by 1ec5** [comment]
Even loading the plugin non-lazily according to [this example](https://maplibre.org/maplibre-gl-js-docs/example/mapbox-gl-rtl-text) doesn’t seem to change anything. It’s probably because none of the fonts in this style’s fontstack includes Arabic or Hebrew glyphs: #393.

**Comment by claysmalley** [comment]
This affects more than just RTL scripts. Cyrillic, Greek, Thai, Indic scripts, Cherokee, and Canadian Aboriginal Syllabics are also missing font support.

**Comment by 1ec5** [comment]
Yes, agreed. There is a compounding issue for Arabic and Hebrew that the right-to-left text will be unreadable even once the fontstack is fixed, but the fontstack is the bigger issue for the time being.

**Comment by ZeLonewolf** [comment]
I tried swapping in `https://openhistoricalmap.github.io/map-styles/fonts/{fontstack}/{range}.pbf`, which is the [gylph string used in OpenHistoricalMap](https://github.com/OpenHistoricalMap/map-styles/blob/9852487227cf7be434121a776b1c1473328f80cb/ohm_timeslider_tegola/tegola-ohm.json#L12), however, the two I tested - Cyrillic and Arabic - still don't show up, even though this glyph string works in OHM.

**Comment by 1ec5** [comment]
The fontstack dictates which fonts you can specify in each layer, so you’d need to modify the layers to stop referring to Metropolis.

**Comment by ZeLonewolf** [comment]
Yep, that was the issue:

![image](https://user-images.githubusercontent.com/3254090/204152729-2d082bbb-3b43-42e2-8f92-bdf9b67d5178.png)

**Comment by ZeLonewolf** [comment]
Arabic / Hebrew now appear, however, they aren't shown RTL.
