### ISSUE TITLE
Improved window.map debugging

### ISSUE THREAD

**Issue by ZeLonewolf** [ZeLonewolf/openstreetmap-americana#60]
For debugging I might like `let map = window.map = new …`. The downside of modules is you don't implicitly get global variables, naturally.

(Technically this can be accomplished by making it an export but you'd need to write the correct import at the console.)

_Originally posted by @jleedev in https://github.com/ZeLonewolf/openstreetmap-americana/pull/57#discussion_r762564664_

**Comment by 1ec5** [comment]
Fixed in 9ccc0502bd29f0a94aaf93834eabf6b8e081caac for #72.
