### ISSUE TITLE
Outline waterbodies

### ISSUE THREAD

**Issue by 1ec5** [ZeLonewolf/openstreetmap-americana#608]
This style currently gives bodies of water a relatively dark fill. On land, the water layer overpowers the land in areas with many lakes and streams, undercutting the illusion that the land is a layer atop the water (which is really just an illusion). At sea, the dark color contrasts too much with the boundaries of marine parks.

[<img src="https://user-images.githubusercontent.com/1231218/206313067-0f90339f-3ca3-49e2-b96a-2787ecca675b.png" width="600" alt="Panama">](https://zelonewolf.github.io/openstreetmap-americana/#map=5/7.7/-81.53)

[<img src="https://user-images.githubusercontent.com/1231218/206312759-a9bf0d90-3475-4d8b-818c-b9e6f4499950.png" width="600" alt="New Orleans">](https://zelonewolf.github.io/openstreetmap-americana/#map=8/29.742/-89.715)

[<img src="https://user-images.githubusercontent.com/1231218/206313323-4207eb19-6b9d-4230-9cf1-3c6bec456a3f.png" width="600" alt="Fairfield">](https://zelonewolf.github.io/openstreetmap-americana/#map=13/39.33227/-84.60103)

Print maps use a variety of blues for water. Maps aiming for a more rustic look tend to choose darker shades, but most choose lighter shades, probably to cut down on the cost of ink. A light fill almost always has a hairline stroke around the coastline or shoreline to give it more definition.

<img width="400" alt="Rand McNally Hallwag California" src="https://user-images.githubusercontent.com/1231218/206314535-145b8dbe-1402-47db-bfa3-5e482cf86370.png"> <img width="400" alt="San Mateo County 2006 by Compass Maps" src="https://user-images.githubusercontent.com/1231218/206314836-14e7ebb0-2907-4dbd-a4a8-a20d5f527674.png">

I think we should lighten the water fill and add a darker outline that matches the waterway line color. To keep seams in the water layer from appearing at the edges of harbors and along rivers, the line layer should be underneath the fill layer. I think a lighter color will make the marine parks look much less awkward and also dull the effect of faux knockout halos around place labels over sea (#606).

/ref gravitystorm/openstreetmap-carto#3895 gravitystorm/openstreetmap-carto#3896 gravitystorm/openstreetmap-carto#3926

**Comment by ZeLonewolf** [comment]
Can we get an estimate on how much we can expect to save on ink?

I can't remember why we made it so dark, but I suspect you'll find out shortly what the issue was :joy:
