### ISSUE TITLE
Link languages in use to a website that describes the language

### ISSUE THREAD

**Issue by ZeLonewolf** [ZeLonewolf/openstreetmap-americana#611]
#609 added a display to show which languages are in use. Even better would be to link them to a descriptive web page.

If you want to link each language to its Wikidata item:

```js
`https://www.wikidata.org/wiki/Special:ItemByTitle/enwiki/ISO%20639:${languageCode}`
```

or to its English Wikipedia article:

```js
`https://en.wikipedia.org/wiki/Special:Search/ISO%20639:${languageCode}`
```

or to its Wikipedia article in the user’s preferred language, respecting the language fallback in browser preferences or the URL hash:

```js
`https://hub.toolforge.org/P305:${locale}?lang=${locales}`
```

or its article on the OSM Wiki:

```js
`https://wiki.openstreetmap.org/wiki/Key:name:${languageCode}`
```

_Originally posted by @1ec5 in https://github.com/ZeLonewolf/openstreetmap-americana/pull/609#discussion_r1044763752_

**Comment by 1ec5** [comment]
Maybe once we have a map legend (#332), it’ll serve as a more natural place to send users to documentation about the source of each kind of feature on the map.

**Comment by 1ec5** [comment]
Closing in favor of #332. There isn’t a realistic use case for sending a user to an encyclopedia article about their preferred languages.
