### ISSUE TITLE
shield shown for trail that is invisible

### ISSUE THREAD

**Issue by talllguy** [ZeLonewolf/openstreetmap-americana#631]
The MMT shown on the screenshot, taken [at this location](https://zelonewolf.github.io/openstreetmap-americana/#map=15.33/39.469642/-76.588534) on 2022-12-22 is what I presume [a shield for this Merryman's Mill Trail on OSM](https://www.openstreetmap.org/relation/11117036). I think that if we don't show paths and tracks on Americana, then the refs for them should be hidden too.
![image](https://user-images.githubusercontent.com/1827881/209216030-683fe0b0-03b6-4836-883b-ef28fde8959a.png)

**Comment by 1ec5** [comment]
Some previous discussion in #94. I agree that showing disembodied refs is particularly confusing. We could add a filter to the `highway_shield` layer that weeds out the `[inrl][cw]n` networks.
