### ISSUE TITLE
Convert URL and key to .env

### ISSUE THREAD

**Issue by ZeLonewolf** [ZeLonewolf/openstreetmap-americana#64]
Consider: https://www.npmjs.com/package/dotenv

So that you can put the localhost URL in your working directory `.env` file (and `.gitignore` it), and the deployment process can use the production URL.

_Originally posted by @jleedev in https://github.com/ZeLonewolf/openstreetmap-americana/pull/62#discussion_r772452753_

**Comment by zekefarwell** [comment]
I'm a fan of this approach.  We should use it for the [mapTilerKey](https://github.com/ZeLonewolf/openstreetmap-americana/blob/ed6f0beb259e7df2c110272c06ae29b86cf7f53f/style/key.js#L11) as well.

**Comment by ZeLonewolf** [comment]
I agree with those two values (URL and maptiler key).
I wasn't sure about the whole npm business and how we actually go about adding a package.

**Comment by ZeLonewolf** [comment]
Fixed in #67
