### ISSUE TITLE
Nebraska Byway Shield

### ISSUE THREAD

**Issue by StretchLongfellow** [ZeLonewolf/openstreetmap-americana#649]
The Nebraska Byways are marked by a single shield with a second sign below with the nameplate of the byway. At the size at which we display route shields, there’s no need for the name, so we can display just the logo. These turnpikes are tagged network=US:NE:Scenic (although most have not been mapped yet, so that will be an upcoming project for me!).
![220px-Nebraska_Byway_Sign_M1-11 svg](https://user-images.githubusercontent.com/110199772/210282194-ff9a0832-4deb-41ca-9708-7fac25ea96c8.png)

**Comment by ZeLonewolf** [comment]
Thanks for opening this issue!

It looks like there is already one [relation](https://www.openstreetmap.org/relation/14283024) mapped with this network value, so we can use that one to test against.

I would normally simplify the artwork, probably by removing the text and letting the design shrink down to its pixels.

Do you happen to know if there is a public domain SVG of the shield artwork available anywhere?

**Comment by StretchLongfellow** [comment]
The SVG I attached was from
https://commons.wikimedia.org/wiki/File:Nebraska_Byway_Sign_M1-11.svg,
pulled from the MUTCD.

**Comment by ZeLonewolf** [comment]
I experimented with just the seal alone, but I'm not sure it works as well without the surrounding square:

![image](https://user-images.githubusercontent.com/3254090/210285051-d2c3a245-85e0-4c35-8649-e37da072209b.png)

**Comment by 1ec5** [comment]
If contrast is the issue, try surrounding the blue disc with a white outline.

**Comment by ZeLonewolf** [comment]
Nixed the windmill and the bird, and added that border:

![image](https://user-images.githubusercontent.com/3254090/210285536-68fb8125-54cd-4f7f-a2f5-73f680e14d4f.png)
