### ISSUE TITLE
European road network

### ISSUE THREAD

**Issue by attilakundev** [ZeLonewolf/openstreetmap-americana#69]
Referring to this conversation:
https://osmus.slack.com/archives/C01V02K52UX/p1640606101380400

**Comment by attilakundev** [comment]
https://www.openstreetmap.org/relation/2093784 an example European E-road (E75 in Hungary)
https://en.wikipedia.org/wiki/International_E-road_network
You can use the markers seen in Wikipedia because that is the most standard one

**Comment by Mashin6** [comment]
Also national highway shields. I can help drawing or locating pictures.
e.g. Germany https://upload.wikimedia.org/wikipedia/commons/6/6e/Bundesautobahn_38_number.svg
Slovakia https://upload.wikimedia.org/wikipedia/commons/6/6b/D1-SVK-2020.svg
Czechia https://upload.wikimedia.org/wikipedia/commons/9/9b/CZ_traffic_sign_IS16a_-_D0.svg

**Comment by ZeLonewolf** [comment]
If anyone is motivated to start working on adding these shields, #72 has instructions on how to do that prior to OMT 3.13 being available.  PRs can be posted to the branch https://github.com/ZeLonewolf/openstreetmap-americana/tree/openmaptilers-new-features-test.

SVG artwork should be generated with a max size of 40px along the shortest dimension, with a recommended stroke size of 2.5px.

**Comment by 1ec5** [comment]
Some of the U.S. shields in #72 are derived from public domain images on Commons, so the images linked in https://github.com/ZeLonewolf/openstreetmap-americana/issues/69#issuecomment-1005019777 could be a good starting point.

**Comment by Mashin6** [comment]
![image](https://user-images.githubusercontent.com/5265707/148725510-c064a11b-0199-4d4a-bf31-c44431f82641.png)

**Comment by attilakundev** [comment]
Looks nice!

**Comment by Mashin6** [comment]
Here is Hungary 
<img width="426"  src="https://user-images.githubusercontent.com/5265707/149635840-fc382a48-ba5b-4b8f-ae4e-968b4d877fde.png">

**Comment by attilakundev** [comment]
Awesome! I guess then the regional route shields will be similarly to this :D take a screenshot of route 3 - route 24 intersection in Gyöngyös please if the primary route shields are done

**Comment by ZeLonewolf** [comment]
With @Mashin6's code updates to #72, this issue will close once the highway shields branch can be merged.  Other shield networks that need to be rendered should open new issues with artwork samples.

**Comment by attilakundev** [comment]
Alright, I checked the code, so i saw the HU:national there but since the network is kindof weird, since those which start with M are motorways, which doesn't have the M are green colored and not blue, like here: https://en.wikipedia.org/wiki/Main_road_3_(Hungary)#/media/File:3_(Hu)_Otszogletu_zold_tabla.svg

**Comment by Mashin6** [comment]
Yeah, those minor once should have a separate network like `HU:primary` or something like that.

**Comment by attilakundev** [comment]
I don't know, I think Hungarians will stick to HU:national for those which are signed and HU:regional which are unsigned, so a filter like regex couldn't work for checking if the ref has the M or not?

**Comment by Mashin6** [comment]
@ZeLonewolf Maybe by hardcoding color replacement in `shieldLighten()` or some new function?

**Comment by Mashin6** [comment]
Switzerland
![image](https://user-images.githubusercontent.com/5265707/149852532-2e69d461-4880-44cb-8eee-164f5786a21b.png)

Italy 
![image](https://user-images.githubusercontent.com/5265707/149852087-f3b24558-b8dc-400a-b4f6-e4bc98e87630.png)

**Comment by Mashin6** [comment]
Czech Republic
![image](https://user-images.githubusercontent.com/5265707/149998704-8a49fe51-144d-403d-acab-f8469e37f155.png)

**Comment by ZeLonewolf** [comment]
> @ZeLonewolf Maybe by hardcoding color replacement in `shieldLighten()` or some new function?

That's the right idea.  If the shields are the same design but just different colors, we can use the `shieldLighten()` approach, otherwise we would need to implement new functionality for returning a shields as a function of ref for special cases.

**Comment by Mashin6** [comment]
Austria
![image](https://user-images.githubusercontent.com/5265707/150669380-88961b6c-eacf-4015-bc0b-f4d0f3eeea2f.png)

**Comment by Mashin6** [comment]
Croatia:
![image](https://user-images.githubusercontent.com/5265707/150868839-018e36aa-c80f-4b01-8531-0222069d8956.png)
