### ISSUE TITLE
Render universities/colleges distinctly from schools

### ISSUE THREAD

**Issue by wmisener** [ZeLonewolf/openstreetmap-americana#694]
Colleges (`amenity=college`) and universities (`amenity=university`) are tagged differently than schools, and they play different roles in the community fabric. They're often larger, sometimes with extensive campuses, and therefore serve both as major destinations themselves and as very important locations for city-wide orientation, sometimes defining the character of a city region or even a whole town.

As of https://github.com/ZeLonewolf/openstreetmap-americana/pull/689, colleges and universities are rendered the same as all other schools, including preschools, which may prove confusing. It would make sense to render them similarly to schools, but a distinct icon could also work. One idea could be to a "C" or "U" inside the school building, similarly to how some of the map samples in #78 differentiate elementary/middle/high schools. Other possibilities include a larger building with multiple flags (also shown in #78) or some sort of mortarboard cap icon (a common higher education signifier, e.g. in iD). Samples welcome!

I think it would also make sense for them to appear at much lower zoom than schools do (currently z15), since they are often major landmarks and thus deserve to be shown at a city-wide scale. Just from eyeballing, I think z11 or z12 would be appropriate. Due to their often-large extent, it might be appropriate to consider an area rendering as well.

**Comment by adamfranco** [comment]
I like the idea of the mortarboard. It's a pretty distinctive shape and a "C" or "U" in the building box may be harder to  translate for those who read different scripts. While mortarboards come out of a particular cultural context, doing image searches shows them to be pretty broadly applied around the world:

- [China](https://www.google.com/search?q=china+university+graduation&client=firefox-b-1-d&sxsrf=AJOqlzXBBWyKC7Bsb6yHe6oicflk96CXNg:1673983932984&source=lnms&tbm=isch&sa=X&ved=2ahUKEwiPmr2NrM_8AhX6jYkEHcJ5DIwQ_AUoAXoECAEQAw&biw=1304&bih=790&dpr=1)
- [Indonesia](https://www.google.com/search?q=indonesia+university+graduation&tbm=isch&ved=2ahUKEwj4rMOOrM_8AhXxEVkFHdbgB08Q2-cCegQIABAA&oq=indonesia+university+graduation&gs_lcp=CgNpbWcQAzoECCMQJzoFCAAQgAQ6BggAEAcQHjoICAAQBRAHEB46CAgAEAgQBxAeUNi0B1jM1Qdgq94HaABwAHgAgAGQAYgB3wiSAQM2LjWYAQCgAQGqAQtnd3Mtd2l6LWltZ8ABAQ&sclient=img&ei=v_fGY7jRCvGj5NoP1sGf-AQ&bih=790&biw=1304&client=firefox-b-1-d)
- [Iran](https://www.google.com/search?q=iran+university+graduation&tbm=isch&ved=2ahUKEwjd65DPrM_8AhVpGFkFHczdACoQ2-cCegQIABAA&oq=iran+university+graduation&gs_lcp=CgNpbWcQAzoECCMQJzoGCAAQBxAeOggIABAFEAcQHjoICAAQCBAHEB5QsxJY5RZgtCdoAHAAeACAAWiIAcgDkgEDNC4xmAEAoAEBqgELZ3dzLXdpei1pbWfAAQE&sclient=img&ei=RvjGY92wKOmw5NoPzLuD0AI&bih=790&biw=1304&client=firefox-b-1-d)
- [Bolivia](https://www.google.com/search?q=bolivian+university+graduation&tbm=isch&ved=2ahUKEwick_rcrM_8AhVOEGIAHW-_AS4Q2-cCegQIABAA&oq=bolivian+university+graduation&gs_lcp=CgNpbWcQAzoECCMQJzoGCAAQBxAeOggIABAIEAcQHlDiOVjDV2DCWmgEcAB4AIABaogBmAaSAQM2LjOYAQCgAQGqAQtnd3Mtd2l6LWltZ8ABAQ&sclient=img&ei=Y_jGY9zVJ86giLMP7_6G8AI&bih=790&biw=1304&client=firefox-b-1-d)
- [Egypt](https://www.google.com/search?q=egypt+university+graduation&tbm=isch&ved=2ahUKEwj7wKrrrM_8AhXMFmIAHUznBPgQ2-cCegQIABAA&oq=egypt+university+graduation&gs_lcp=CgNpbWcQAzoECCMQJzoGCAAQBxAeOgQIABBDOgUIABCABDoICAAQCBAHEB5QzQtYzJsBYI2jAWgRcAB4AIABcogBuw6SAQQxNi41mAEAoAEBqgELZ3dzLXdpei1pbWfAAQE&sclient=img&ei=gfjGY7v8MMytiLMPzM6TwA8&bih=790&biw=1304&client=firefox-b-1-d)
- [Mozambique](https://www.google.com/search?q=mozambique+university+graduation&tbm=isch&ved=2ahUKEwjhhuaBrc_8AhUMEGIAHRj7DKQQ2-cCegQIABAA&oq=mozambique+university+graduation&gs_lcp=CgNpbWcQAzoECCMQJzoGCAAQBxAeULftAVjcpwJgrasCaARwAHgAgAHAAYgBsQmSAQM4LjSYAQCgAQGqAQtnd3Mtd2l6LWltZ8ABAQ&sclient=img&ei=sPjGY-HuN4ygiLMPmPazoAo&bih=790&biw=1304&client=firefox-b-1-d)
- [Estonia](https://www.google.com/search?q=estonia+university+graduation&tbm=isch&ved=2ahUKEwinjrmdrc_8AhUcGVkFHSB9BjUQ2-cCegQIABAA&oq=estonia+university+graduation&gs_lcp=CgNpbWcQAzoECCMQJzoGCAAQBxAeOggIABAIEAcQHjoGCAAQCBAeUNgVWLUfYIshaABwAHgAgAFyiAHkBZIBAzUuM5gBAKABAaoBC2d3cy13aXotaW1nwAEB&sclient=img&ei=6vjGY6fxNpyy5NoPoPqZqAM&bih=790&biw=1304&client=firefox-b-1-d)

**Comment by adamfranco** [comment]
Also note the distinction between American usage of "college" (in particular "liberal arts colleges" --> `amenity=university` or "college of medicine" --> `faculty=*`) and the British usage of the term "college" which is a step between secondary and university -- sort of like if everyone going to university got an associates at a community college first before beginning their bachelor's degree at a university. See https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dcollege for more.

What I'm not sure about is if `amenity=college` would actually be better handled like `amenity=school`, but with a second flag, or if it should be more like a university. It's been about 20 years since I did a semester in Scotland and I'm not remembering the details friends related. Probably a good question for British folks in the community forums.

**Comment by wmisener** [comment]
In my area, I often see [community colleges](https://en.wikipedia.org/wiki/Community_colleges_in_the_United_States) tagged as `amenity=college`, and in fact as the predominant use of that tag. Is that usage common elsewhere in the US? If that's the case, my opinion would be that they're closer in function to universities than to high schools, and so rendering with a university-style symbol would be the less confusing choice of the two (and [hey, they get mortarboard graduation caps too](https://twitter.com/OfficialCCSF/status/868193928024956928)).
