### ISSUE TITLE
Ellipse shield-draw function vertical text alignment

### ISSUE THREAD

**Issue by michaelblyons** [ZeLonewolf/openstreetmap-americana#716]
The screenshots for #706 do not appear to vertically center the text. Ellipses are vertically symmetrical, so the padding should be even top and bottom. (Unlike, say, the triangle shields 😬 )

**Comment by claysmalley** [comment]
This seems to be the case for quite a lot of shields, not just ellipses. Something weird is going on with vertical alignment in `shield_text.js`.

**Comment by claysmalley** [comment]
Closing as fixed by #965.
