### ISSUE TITLE
Ohio Turnpike conflated with ordinary state route

### ISSUE THREAD

**Issue by 1ec5** [ZeLonewolf/openstreetmap-americana#718]
Like [the old shield renderer](https://bazaar.launchpad.net/~asciiphil/osm-shields/trunk/view/254/website/supported.html#L163), Americana treats any relation tagged `network=US:OH` without a `ref` as the Ohio Turnpike, which is [currently tagged as such](https://www.openstreetmap.org/relation/1661720):

https://github.com/ZeLonewolf/openstreetmap-americana/blob/d35b7e3629ad9cf57f65183eb7666c21d2aea134/src/js/shield_defs.js#L2354-L2356

This tagging dates back to when we didn’t distinguish any of Ohio’s special routes with their own `network` tags, not even the various Ohio Byways. But it’s incorrect to tag the Ohio Turnpike as if it’s part of the normal Ohio state route network. For one thing, it results in a curious legend entry that lacks the space to say what that green shield means:

<img src="https://user-images.githubusercontent.com/1231218/213832159-a1cf079b-fb23-4075-8a05-28452c05b7e4.png" width="302" alt="Ohio">

**Comment by 1ec5** [comment]
[Changeset 131,528,494](https://www.openstreetmap.org/changeset/131528494) retags the Ohio Turnpike as `network=US:OH:Byway`.

**Comment by jleedev** [comment]
Change is in the tiles now.
