### ISSUE TITLE
2023 Google Summer of Code projects

### ISSUE THREAD

**Issue by simonpoole** [ZeLonewolf/openstreetmap-americana#728]
The OSM GSOC organisation committee has issued a call for project ideas for this year see https://lists.openstreetmap.org/pipermail/dev/2023-January/031306.html

If you have suitable projects and capacity to mentor a  student, please feel free to add them to https://wiki.openstreetmap.org/wiki/Google_Summer_of_Code/2023/Project_ideas

Cheers

Simon

**Comment by 1ec5** [comment]
Unfortunately we weren’t able to come up with suitable projects in time, but hopefully we’ll have the capacity to mentor a student next year.
