### ISSUE TITLE
Great Lakes Seaway Trail shield

### ISSUE THREAD

**Issue by quincylvania** [ZeLonewolf/openstreetmap-americana#754]
The Great Lakes Seaway Trail is sort of the Lake Ontario equivalent of the Great Lakes Circle Tours. As a followup to #569, we should also add a shield for this route. The routes doesn't seem to appear in the data because there's no `network` tag.

https://en.wikipedia.org/wiki/Great_Lakes_Seaway_Trail
https://wiki.openstreetmap.org/wiki/Great_Lakes/Circle_Tour
https://www.openstreetmap.org/relation/13063934

I created a shield, but I'm now realizing there's a new sign. Not sure which design we should use.

![shield_glst](https://user-images.githubusercontent.com/2046746/216146115-980d0d64-8b2f-411e-89c5-a202c510d464.svg)

| Old | New |
|-|-|
| ![Seaway_Trail svg](https://user-images.githubusercontent.com/2046746/216146869-67f5e5a6-3f27-448a-8e80-6a886bfa8412.png) | ![Great_Lakes_Seaway_Trail_Logo](https://user-images.githubusercontent.com/2046746/216147057-f56f7cb2-0965-458d-b28c-9e3452336a48.jpg) |

**Comment by 1ec5** [comment]
Ah, I like your take on the old shield, but I guess we should find out which shield is actually more prevalent in the wild these days. Sometimes it can take a while for new shield designs to get installed. For the new shield, it might be possible to omit a text legend, relying on the sweeping S curve to be recognizable.

**Comment by 1ec5** [comment]
> The routes doesn't seem to appear in the data because there's no network tag.

[Changeset 132,661,739](https://www.openstreetmap.org/changeset/132661739) tags the relation as `network=US:GLST`.

**Comment by quincylvania** [comment]
Here's a design for the new shield.

![glst shield](https://user-images.githubusercontent.com/2046746/219696315-bed5d7c6-f95d-41c3-acad-634e351b4dda.svg)

**Comment by 1ec5** [comment]
No longer blocked:

<img src="https://user-images.githubusercontent.com/1231218/219814715-4b0c53d3-cf3d-4700-a243-6b5bae68d52e.png" width="162" alt="US:GLST">
