### ISSUE TITLE
Merritt Parkway shield

### ISSUE THREAD

**Issue by quincylvania** [ZeLonewolf/openstreetmap-americana#758]
Driving the Merritt today, I noticed these wonderfully ogre-shaped shields. This is the only Connecticut parkway with its own shield from what I can tell. I just added the route to OSM, so it'll have to wait for the next data refresh.

https://www.openstreetmap.org/relation/15425309
https://en.wikipedia.org/wiki/Merritt_Parkway
https://commons.wikimedia.org/wiki/File:Merritt_Pkwy_Shield.svg

![Merritt_Pkwy_Shield svg](https://user-images.githubusercontent.com/2046746/216472508-97418842-aa3b-427b-82d2-841f6f259663.png)
![Screenshot 2023-02-02 at 6 17 06 PM](https://user-images.githubusercontent.com/2046746/216472818-93efae6e-7c9d-4189-8be2-05a2a656c1ff.png)
![920x920](https://user-images.githubusercontent.com/2046746/216472827-03a25f4a-2712-4ae5-b5da-555f520efeda.jpg)

Old design: 
![CT19560154i1-2837067163](https://user-images.githubusercontent.com/2046746/216472834-81e504ba-261b-47ff-989e-df779668ab01.jpg)

**Comment by 1ec5** [comment]
Nice, this is one of the [unusual highway networks](https://wiki.openstreetmap.org/wiki/United_States/Unusual_highway_networks) documented on the wiki but without suggested tagging. Since this is a one-off route, it doesn’t hurt to use a specific `network` corresponding to the route’s name, but “Parkway” is OK as long as there isn’t going to be another parkway in the state with its own shield design.

**Comment by 1ec5** [comment]
@ZeLonewolf should the taginfo project file describe this shield as a “blue ogre”? 😛

**Comment by quincylvania** [comment]
@1ec5 Cool page! I'll probably end up making shields for most of those if no one beats me to it.

As for the CT parkway tagging, I used the same pattern as NY's, I just wasn't sure what to use for the `ref`. IMO there should really be route relations in OSM for all of CT's state-designated parkways under the same `network` even if they don't have shields.

**Comment by ZeLonewolf** [comment]
ref tags are normally blank when there's no route number. Of course there's also the concurrent CT-15 which would have the normal state network and ref.

**Comment by 1ec5** [comment]
No longer blocked:

<img src="https://user-images.githubusercontent.com/1231218/219814870-e66c1f0b-9117-4242-923c-9851e0d96c4c.png" width="175" alt="US:CT:Parkway">
