### ISSUE TITLE
Great River Road shield

### ISSUE THREAD

**Issue by 1ec5** [ZeLonewolf/openstreetmap-americana#769]
The [Great River Road](https://en.wikipedia.org/wiki/Great_River_Road) straddles the Mississippi River through ten states (and formerly two Canadian provinces). It has a distinctive shield featuring a steamboat inside a pilotwheel:

[<img src="https://upload.wikimedia.org/wikipedia/commons/f/fc/GreatRiverRoad.svg" width="200" alt="Shield">](https://commons.wikimedia.org/wiki/File:GreatRiverRoad.svg)

[![Wisconsin](https://upload.wikimedia.org/wikipedia/commons/thumb/1/11/GreatRiverRoadWI_Signs.jpg/509px-GreatRiverRoadWI_Signs.jpg)](https://commons.wikimedia.org/wiki/File:GreatRiverRoadWI_Signs.jpg)

The route is mapped as a series of route relations. The [route superrelation](https://www.openstreetmap.org/relation/456651) and the relations for the national route through [Iowa](https://www.openstreetmap.org/relation/1784814) and [Wisconsin](https://www.openstreetmap.org/relation/1783095) are tagged with `network=US:AB:NSB`, indicating that they’re part of the America’s Byways system. None of the other relations are tagged with a network.

I think these relations should be part of a network specifically about the well-signposted Great River Road, rather than America’s Byways, which is secondary. Something like `US:GRR` or `US:MRPC` would be appropriate.

The official transportation map of each state other than Iowa simplifies the shield to just the pilotwheel:

<img width="320" alt="Iowa DOT 2010" src="https://user-images.githubusercontent.com/1231218/217164553-57e695d9-6df8-4139-8c79-331287eb76ae.png">
<img width="272" alt="Illinois DOT 2005–06" src="https://user-images.githubusercontent.com/1231218/217164205-be1c8192-6ca2-4774-bcaf-5770e3869fa7.png">
<img width="305" alt="MoDOT 2009" src="https://user-images.githubusercontent.com/1231218/217164411-ac440ec6-fc1d-4535-b31e-e9244be1ff0c.png">
<img width="197" alt="Mississippi DOT 2008" src="https://user-images.githubusercontent.com/1231218/217164889-1df37aad-5303-4d9a-b6c9-8993f3e3e018.png">
<img width="227" alt="LaDOTD 2002" src="https://user-images.githubusercontent.com/1231218/217165026-fde4d92d-854f-4c05-b901-fd0b78850562.png">

**Comment by 1ec5** [comment]
> I think these relations should be part of a network specifically about the well-signposted Great River Road, rather than America’s Byways, which is secondary. Something like `US:GRR` or `US:MRPC` would be appropriate.

[Changeset 132,245,282](https://www.openstreetmap.org/changeset/132245282) adds `network=US:GRR` to all the route relations.

**Comment by 1ec5** [comment]
No longer blocked:

<img src="https://user-images.githubusercontent.com/1231218/219815096-4ba7a059-d92c-4c72-9d40-fa8fff742df6.png" width="240" alt="US:GRR">

**Comment by 1ec5** [comment]
Here’s the shield in context in those official state transportation maps:

<img width="147" alt="MNDOT" src="https://user-images.githubusercontent.com/1231218/219836917-84135bed-07cb-45cb-aac7-ab4d736872c8.png">
<img width="244" alt="MoDOT" src="https://user-images.githubusercontent.com/1231218/219840622-e8308409-3461-43b2-bf28-f0133947234c.png">
<img width="214" alt="LaDOTD" src="https://user-images.githubusercontent.com/1231218/219840510-1078f748-cdbf-4203-80a5-3524ce253c81.png">

**Comment by ZeLonewolf** [comment]
I don't like that last one where you can see the road through the center of the wheel.  Can't tell what that is at all.
