### ISSUE TITLE
Style statistics based on source layer

### ISSUE THREAD

**Issue by ZeLonewolf** [ZeLonewolf/openstreetmap-americana#777]
This is a follow-on from #747 to document additional work improve the stats generator.

> We could group the layers by source layer to get pretty similar statistics, modulo some layer organization weirdness in OpenMapTiles.

_Originally posted by @1ec5 in https://github.com/ZeLonewolf/openstreetmap-americana/pull/747#discussion_r1100926373_

**Comment by 1ec5** [comment]
Replace:

https://github.com/ZeLonewolf/openstreetmap-americana/blob/09cf915acb8597359894b94ed20eeabbbca525b3/scripts/stats.js#L45

with:

```js
let layerGroup = layer["source-layer"] || layer.source || layer.type;
```

**Comment by ZeLonewolf** [comment]
With the suggested change, it sounds like the layer IDs are irrelevant as long as they're distinct.
