### ISSUE TITLE
Missing shield for `US:I:Spur`

### ISSUE THREAD

**Issue by michaelblyons** [ZeLonewolf/openstreetmap-americana#792]
The west fork of I-270 [north of Washington, DC](https://zelonewolf.github.io/openstreetmap-americana/#map=14/39.02524/-77.13206) does not have a shield. I don't know whether `US:I:Spur` should just be `US:I` or whether an audit of Interstate spurs and their shields ought to happen.

Thank you to Minh and the map legend! Without it, I wouldn't have noticed the missing shield.

**Comment by ZeLonewolf** [comment]
How is it signed in real life?

**Comment by michaelblyons** [comment]
Great question, sorry! I only remember "To I-270" signs[^1] with the normal Interstate shield. Wikipedia [seems to think](https://en.wikipedia.org/wiki/Interstate_270_(Maryland)#Interstate_270_Spur) that it includes SPUR text above the shield since 1975, but they don't have a photo. I'll see if I can find a reassurance marker next time I'm out there.

[^1]: And corresponding "To I-495 West" going the other way.

**Comment by 1ec5** [comment]
It’s a modifier. Modifiers appear in the same place as cardinal directions on MUTCD guide signs.

**Comment by jleedev** [comment]
e.g. TRUCK NORTH https://www.mapillary.com/app/?pKey=307842207654933
