### ISSUE TITLE
Render town halls

### ISSUE THREAD

**Issue by wmisener** [ZeLonewolf/openstreetmap-americana#794]
Town halls are important city landmarks, so rendering them would make progress on Americana's representation of community institutions (#435) and POIs generally (#692). A fairly common representation of town halls are as Neoclassical columned buildings, topped by a rectangular flag, which represents their governmental purpose and distinguishes them from museums, which can be represented similarly in some maps. Two OSM-adjacent examples of this genre of icon are Carto and Temaki:
<img width="76" alt="Screen Shot 2023-02-16 at 9 21 42 PM" src="https://user-images.githubusercontent.com/58491489/219556869-f466426b-7f42-474b-8a4e-81d10dd40405.png"> <img width="130" alt="Screen Shot 2023-02-16 at 9 21 19 PM" src="https://user-images.githubusercontent.com/58491489/219556873-ca6174ae-fac9-4744-abdc-45eb1650cfa9.png">

Many American road maps use simple squares to denote these and other important places of interest, but I think we can take a richer approach, as we already have for other POI icons.
<img width="180" alt="Screen Shot 2023-02-16 at 9 21 19 PM" src="https://user-images.githubusercontent.com/1231218/174456035-c90a2298-b515-49dc-bca8-c663ca2078f4.png">

I personally actually quite like the temaki icon, so that or a similar design could work well.

**Comment by quincylvania** [comment]
> I personally actually quite like the temaki icon

Thanks! (I drew this.) Temaki icons are 15x15px, so they might need some tweaking for Americana. The flag component is consistent with icons for other government buildings, not sure if we want to use these too:

![Screenshot 2023-02-17 at 10 04 39 AM](https://user-images.githubusercontent.com/2046746/219690955-ae3a8249-400c-4f20-af18-421e3734764c.png)

**Comment by 1ec5** [comment]
We should consider how these flag-topped icons interact with the existing school icon, which is simpler and even more recognizable. Ranger stations are also typically marked by a similar icon on topographic maps.

**Comment by ZeLonewolf** [comment]
Typical Americans. Starts with bars and coffee, then quickly moves on to anywhere we can shove a flag :joy:

**Comment by 1ec5** [comment]
> We should consider how these flag-topped icons interact with the existing school icon, which is simpler and even more recognizable. Ranger stations are also typically marked by a similar icon on topographic maps.

Would it be enough to distinguish schools as the buildings with triangular flags and city halls as the buildings with rectangular flags? Or are the Doric columns necessary for gravitas? A future library or museum icon might end up with columns too. Maki distinguishes museums from other halls of seriousness by labeling the building with an “M”, but that feels like a last resort, even for speakers of languages where “museum” begins with an “M”.

**Comment by wmisener** [comment]
> We should consider how these flag-topped icons interact with the existing school icon, which is simpler and even more recognizable. Ranger stations are also typically marked by a similar icon on topographic maps.

Definitely worth putting some thought into this. I don't think it's bad for both schools and town halls to have flags, since in both the flag symbolizes the public nature of the location (and, to be more literal, both types of place often have flags flown atop/near them). The current icon for schools have triangle shaped pennants flying left off a square building, which was inspired by US paper maps. Meanwhile, the temaki icon has a rectangular, waving flag flying to the right from a neoclassical, columned building.

The first question is, do we want the flags to be different? I could imagine a useful symbology where government buildings always get such a square flag with different surroundings, linking them stylistically. Embassies, ranger stations, and maybe courthouses are a few candidates for a shared "governmental function" symbology that pop into my mind. Whereas schools are different and common enough that I think distinguishing them with their own flag shape is useful.

> Would it be enough to distinguish schools as the buildings with triangular flags and city halls as the buildings with rectangular flags? Or are the Doric columns necessary for gravitas?

Re: the building types, I think the building distinction visually conveys the difference between the two places: schools are often less adorned than government centers, due to an individual school usually being less important than an individual town hall. Even though government centers aren't always ornate architecturally, I think people would get the idea. In other words, I think I like the gravitas the columns lend, as you put it 😆.

> A future library or museum icon might end up with columns too.

I would find rendering museums similarly to town halls, maybe even the same building but without the flag, as a bonus rather than a drawback: I think it would add coherence and consistency to the map's visual language. But I can see how opinions might differ on that. I definitely don't like the idea of slapping a letter M on museums, as we don't want to assume a default language after all the work that went into language label switching. Museums could also end up a different color than town halls, though we haven't really sorted out an "attraction" color in the style yet. Libraries could be rendered a number of different ways, but we should probably leave that for their own issue.

> Another option for the building would be a clock, evoking Back to the Future.

Yes, this was on a map sample you posted in #435:
![image](https://user-images.githubusercontent.com/58491489/219756953-2bd7cf37-79ee-4e87-ae7e-e196c80e50ed.png)
Definitely an option. I personally don't like it quite as much, I feel like I would expect that to be the icon for an actual clock tower, and be disappointed if I showed up to the building and it didn't tell me what time it was. Though I guess if you're looking for a column to lean against you might be similarly misled by the classical building.

**Comment by 1ec5** [comment]
> The first question is, do we want the flags to be different? I could imagine a useful symbology where government buildings always get such a square flag with different surroundings, linking them stylistically. Embassies, ranger stations, and maybe courthouses are a few candidates for a shared "governmental function" symbology that pop into my mind. Whereas schools are different and common enough that I think distinguishing them with their own flag shape is useful.

I agree with keeping the pennant on schools and using a rectangular flag on anything else that has a flag. My question was only if the shape would be distinctive enough at the current POI icon size. But then again, the pennant is already larger and longer in Americana than it is on many maps that use this symbol.

Some maps give schools and churches a pitched roof. I don’t think we should copy that, though, because it reduces our options for other kinds of buildings, such as ranger stations.

> I feel like I would expect that to be the icon for an actual clock tower, and be disappointed if I showed up to the building and it didn't tell me what time it was. Though I guess if you're looking for a column to lean against you might be similarly misled by the classical building.

I agree, that particular icon looks too much like a tower. But if it’s a stubbier tower topping a wider building, it might get the point across.

I’m already quite disappointed by all the schools that don’t fly pennants during school hours. 😉

**Comment by 1ec5** [comment]
On a completely different note, I’ve seen maps (but unfortunately don’t have any in my collection) that mark the city hall by a five-pointed star. What’s nice about this approach is that the icon wouldn’t come in until a zoom level where we aren’t showing the capital city icon, so it would be sort of a followup to the capital city icon, indicating the city’s administrative center.

There would be a risk of confusion with a police station, which in some maps is depicted by a star. For example, the map in https://github.com/ZeLonewolf/openstreetmap-americana/issues/794#issuecomment-1435095032 uses a five-pointed star for police. Other maps out west use a seven-pointed star instead, based on the local custom for sheriff’s badges. However, for police stations, I’d probably go with something that looks more like a badge, like a slightly elongated version of the U.S. Route shield.

**Comment by 1ec5** [comment]
The [Green Map Icons](https://www.greenmap.org/make-map/green-map-icons) project also uses a clock tower for “governmental offices”. This project largely uses iconography that would be familiar to the same audience as Americana, though we can’t use the icons verbatim since they’re too restrictively licensed.

> But if it’s a stubbier tower topping a wider building, it might get the point across.

I was thinking of something along these lines, but it ends up kind of looking like a one-room schoolhouse… or a KinderCare. I guess that’s why existing maps focus on the clock tower.

![townhall-clock](https://user-images.githubusercontent.com/1231218/221385867-ba5a52a3-7477-48a6-a35e-288e11b3d820.svg)

Overall, I would prefer the elegance of just using a star, like on capital cities at lower zoom levels. But if others aren’t convinced this is intuitive enough, then we could go with something less abstract as long as it doesn’t force us to abandon other familiar icons due to abstractness.

**Comment by wmisener** [comment]
One thing that strikes me as tricky for town halls and similar features is that there are few American road maps that have a distinct icon for them. City-scale maps only need to show one or a few, and so lump them in with other rare POIs like courthouses and such, while regional-scale maps often omit such details. Compare that to schools, post offices, or fire stations, which are all common enough to typically need their own icons, giving us more to go off of. A zoomable web-based map is a different problem in that respect I suppose. I don't find a star that intuitive personally, but I'll try it out in the pull request.
