### ISSUE TITLE
John Hunt Morgan Heritage Trail shields

### ISSUE THREAD

**Issue by 1ec5** [ZeLonewolf/openstreetmap-americana#811]
The John Hunt Morgan Heritage Trail is a pair of historical tour routes documenting Morgan’s Raid through Indiana and Ohio during the American Civil War. The routes are marked with standard trailblazers and reassurance signs in Indiana and Ohio. The signs point out each turn in the route and occasionally point to an interpretive sign. (There’s a corresponding route in Kentucky too, but I can’t find any evidence of it being signposted beyond the interpretive signs themselves.)

The shields consist of the state shape in white, outlined in black, with the bottom half in black. Inscribed on the state outline are “John Hunt Morgan Heritage Trail”, “1863”, and the path Morgan’s raiders took through the state.

[![Harshaville Bridge](https://user-images.githubusercontent.com/1231218/224485054-27918856-9fa4-468f-8e13-84fd086b7e6c.png)](https://www.mapillary.com/app/?pKey=170481458324192)

So far, I’ve mapped only part of Ohio’s route as [a route relation](https://www.openstreetmap.org/relation/15504667) tagged `network=US:OH:JHMHT`, from the Indiana state line through Hamilton and Clermont counties. This is only a fraction of the route, which stretches almost to the Pennsylvania state line.

By highway route standards, this is a pretty unusual route. Like scenic routes, it’s very indirect in places. It’s signposted only in the general direction that Morgan’s raiders took, not in the other direction. Yet the route also backtracks and loops in some cases as it makes excursions off the main road to each historical site and interpretive sign. This requires the `signed_direction=yes` tag on the relation and a `forward` or `backward` role on each member. As of iD v2.25.1, any accidental gaps or forks in the relation cause iD to scramble the relation order, so extreme care must be taken when remodeling intersections or roundabouts along the route: openstreetmap/iD#8578 openstreetmap/iD#8415.

**Comment by 1ec5** [comment]
The route in Ohio has been mapped from the western terminus at Harrison to SR&nbsp;772 in central Pike County for a distance of 148&nbsp;miles (238&nbsp;km), about a quarter of the total statewide distance. It normally takes only 2&nbsp;hours, 17&nbsp;minutes to [travel between these points](https://www.openstreetmap.org/directions?engine=fossgis_osrm_car&route=39.25125%2C-84.82005%3B39.04474%2C-83.14476#map=9/39.0941/-83.9824), but closely following this portion of the route would take [4&nbsp;hours, 58&nbsp;minutes](https://routing.openstreetmap.de/routed-car/route/v1/driving/-84.82007,39.25128;-84.81987,39.26202;-84.80296,39.25789;-84.76451,39.26934;-84.67148,39.26496;-84.62507,39.23406;-84.54584,39.26189;-84.53985,39.29099;-84.48517,39.28695;-84.47793,39.27385;-84.45873,39.27204;-84.46179,39.26466;-84.45782,39.27201;-84.41310,39.26831;-84.42426,39.24584;-84.42985,39.23976;-84.39621,39.23787;-84.39382,39.22683;-84.39128,39.22980;-84.39202,39.21545;-84.39918,39.20680;-84.39600,39.20641;-84.39399,39.20583;-84.39366,39.20799;-84.33904,39.20086;-84.29513,39.21333;-84.29607,39.21315;-84.29578,39.21288;-84.26510,39.23702;-84.22075,39.20305;-84.16359,39.23038;-84.07489,39.06702;-83.98521,39.04055;-83.91974,39.02764;-83.90074,38.89669;-83.90440,38.86463;-83.85521,38.85529;-83.78720,38.86690;-83.72585,38.96886;-83.65146,38.94142;-83.65066,38.94247;-83.64892,38.94269;-83.60562,38.92181;-83.51121,38.88839;-83.44975,38.90037;-83.37635,38.98755;-83.33898,38.97502;-83.14458,39.04482?overview=false), not considering traffic congestion.

![Harrison to SR 772](https://user-images.githubusercontent.com/1231218/227419038-fda6864f-20eb-4060-b14f-bb0299f86754.png)

**Comment by ZeLonewolf** [comment]
There's no way that someone could possibly come up with a shield uglier than...

"Hold my beer"

**Comment by 1ec5** [comment]
Started [a route relation for the trail in Indiana](https://www.openstreetmap.org/relation/15638708).

**Comment by 1ec5** [comment]
The Indiana route shield is now unblocked too:

<img src="https://user-images.githubusercontent.com/1231218/230753421-a2fab76f-3cd4-4849-ab55-f1262d0eb215.png" width="183" alt="US:IN:JHMHT">
