### ISSUE TITLE
Render police stations

### ISSUE THREAD

**Issue by wmisener** [ZeLonewolf/openstreetmap-americana#819]
Police stations are common features in American cities and towns, so rendering them would make progress on Americana's representation of community institutions (https://github.com/ZeLonewolf/openstreetmap-americana/issues/435) and POIs generally (https://github.com/ZeLonewolf/openstreetmap-americana/issues/692).

Commonly in America, police are symbolized by their badges. These badges can be star-shaped (maybe more evocative of an Old West sheriff) or shield-shaped, sort of like the US route symbol.

<img width="200" alt="Typical sheriff badge" src="https://user-images.githubusercontent.com/58491489/224504338-c67a3fe6-ea44-413d-8728-d919b467f610.png"> <img width="200" alt="Typical police badge" src="https://user-images.githubusercontent.com/58491489/224504430-70e307bb-cd61-4fdb-959a-86105694bb1c.png">

Many American maps depict police stations as generic POIs, but some have stars.
 ![image](https://user-images.githubusercontent.com/58491489/219756953-2bd7cf37-79ee-4e87-ae7e-e196c80e50ed.png)

Other OSM-adjacent maps tend to use some sort of person with a sash (Carto and Maki below). But this symbology feels very European to me, so I don't think it fits with our theme.
<img width="172" alt="Screen Shot 2023-03-11 at 10 12 58 AM" src="https://user-images.githubusercontent.com/58491489/224504905-b0d27736-0636-4434-b80d-f2bb86d38a19.png"> <img width="172" alt="Screen Shot 2023-03-11 at 10 12 58 AM" src="https://user-images.githubusercontent.com/58491489/224504947-9b475627-79db-497c-8168-63ad992897ad.png"> 

I think a shield icon (as suggested in https://github.com/ZeLonewolf/openstreetmap-americana/issues/794#issuecomment-1435241890) would be appropriate and recognizable. "Infrastructure blue" would probably be the appropriate color for these due to their nature as public institutions.

**Comment by 1ec5** [comment]
A six- or seven-pointed star traditionally represents a county sheriff, depending on the state. Some maps distinguish between sheriff’s offices (star) and other police stations (badge). This distinction can also be found on highway signs in some states like California, but I don’t think we have reliable tagging for it.

Maps that use a star for police stations in general would choose a five-pointed star to avoid confusion.

**Comment by StretchLongfellow** [comment]
I think the shield is more encompassing than the star badge, as I believe that is traditionally sheriff's office only.

I don't like the five-pointed star as we are already using that for other things like state capitols. I know the color is different, but it's still a bit weird.

**Comment by wmisener** [comment]
Here's a test rendering of a modified US route symbol, I think it works pretty well! If others like this concept I'll open a PR with it.
<img width="290" alt="Screen Shot 2023-05-30 at 11 16 42 PM" src="https://github.com/ZeLonewolf/openstreetmap-americana/assets/58491489/bc3b827a-f3c8-4a68-be58-cb12984fae56">

**Comment by 1ec5** [comment]
The icon is using the available space, which makes it look a lot larger than the city hall icon and especially the school icon, both of which have faint elements that extend beyond the main body of the icon. We should either make those icons larger or shrink the police icon. Shrinking the police icon may require exaggerating the curves in the badge somewhat.

**Comment by ZeLonewolf** [comment]
The badge shape makes sense to me as the police icon.  I'm not sure that the six-shooter star is quite right as a monochrome icon and I also think it would look somewhat too close to the Star of David at icon scale.  I do agree that it should be a little curvier, I'd like to see the armpits of the shield curve inwards just a touch more.

**Comment by wmisener** [comment]
Since there seems to be support for the badge/shield concept, I created a PR (#866). Having the icon available might make it easier to hash out further details.
