### ISSUE TITLE
Render libraries

### ISSUE THREAD

**Issue by wmisener** [ZeLonewolf/openstreetmap-americana#821]
Libraries are anchor institutions in a community, providing a variety of services. Rendering them in the style would make progress on #435 and #692.

An obvious rendering choice would be some sort of book. Carto and maki both have open books:
<img width="161" alt="Screen Shot 2023-03-11 at 11 40 15 AM" src="https://user-images.githubusercontent.com/58491489/224508368-56996181-32d2-4ae3-a418-743ba0c1a6ba.png"> <img width="209" alt="Screen Shot 2023-03-11 at 11 34 56 AM" src="https://user-images.githubusercontent.com/58491489/224508371-7b22c4e6-cf18-4cab-b1b5-5c2fa8d9d122.png">

A side profile is also a common icon (NPS and Rontgen):
![image](https://user-images.githubusercontent.com/58491489/224508519-7e926232-80c5-4259-9f5b-7daa40db016b.png) <img width="100" alt="Screen Shot 2023-03-11 at 11 46 55 AM" src="https://user-images.githubusercontent.com/58491489/224508622-f9c6352f-382e-46fa-8982-1abaf750a668.png">

Alternatively, we could evoke the MUTCD, which depicts a person reading:
<img width="200" alt="Screen Shot 2023-03-11 at 11 46 55 AM" src="https://user-images.githubusercontent.com/58491489/224508698-681d9dd0-7491-4ae1-b06c-45906fa19a67.png"> ![image](https://user-images.githubusercontent.com/58491489/219756953-2bd7cf37-79ee-4e87-ae7e-e196c80e50ed.png)

Another option is a neoclassical columned building, as suggested for a museum (#820) or town hall (#794), maybe evoking a [Carnegie library](https://en.wikipedia.org/wiki/Carnegie_library#Gallery). But I fear that icon idea is too tied up in a specific detail of American history, and a book would be more distinctive and clear. We could even render bookstores with the same icon, but in a shop color. This is the approach Carto takes:
<img width="100" alt="Screen Shot 2023-03-11 at 11 54 35 AM" src="https://user-images.githubusercontent.com/58491489/224508919-c69c0f68-e375-4e5c-b4e0-5d2915ebbe53.png">

I think libraries best fit into the "attraction" category, which is of undecided color in the style, maybe brown (see #820).

**Comment by StretchLongfellow** [comment]
I like the MUTCD version, though the book would be fine. I agree that the Carnegie library style is too specific; either of the other options is much easier to understand at a glance.
