### ISSUE TITLE
Two-digit Interstate shields are too wide

### ISSUE THREAD

**Issue by 1ec5** [ZeLonewolf/openstreetmap-americana#834]
Sometime in the last month, the text sizing code changed in such a way that two-digit Interstate shields are too wide and their numerals are too large, at least on macOS where a condensed font is being applied.

[<img src="https://user-images.githubusercontent.com/1231218/227449131-43e71700-654d-4465-ad2e-d37c60aeee5f.png" width="400" alt="Indianapolis">](https://zelonewolf.github.io/openstreetmap-americana/#map=12/39.6868/-86.18271)

**Comment by 1ec5** [comment]
`git bisect` identifies #803 as the culprit.

**Comment by claysmalley** [comment]
Not seeing any issues on Firefox/Ubuntu:

<img src="https://user-images.githubusercontent.com/1732117/227572038-834bce0c-d1b2-4cba-a85d-e912be3275c1.png" width=400 alt=screenshot />

**Comment by 1ec5** [comment]
I should’ve mentioned that this is in Firefox and Safari, but not in Chrome. I’m also seeing it in @quincylvania’s screenshots: compare #798 and #817.

You seem to be getting the Overpass font, which isn’t a default font on any operating system. Until #768 lands, we should be concerned about any regression when using default fonts, even if on some systems it has never been quite right and on others it’s always been fine.

**Comment by ZeLonewolf** [comment]
This does not seem to be a problem in Chrome/Firefox on #768. I'm thinking we can close this as resolved with that PR.
