### ISSUE TITLE
All-caps Georgian labels are invisible

### ISSUE THREAD

**Issue by 1ec5** [ZeLonewolf/openstreetmap-americana#837]
When the preferred language is set to Georgian, any layer that contains all-capital letters appears blank, namely, state/provincial labels and boundary edge labels.

[<img src="https://user-images.githubusercontent.com/1231218/227757322-9da85b06-5ee3-4cf2-a474-e3d00fdfba39.png" width="400" alt="English">](https://zelonewolf.github.io/openstreetmap-americana/#map=5/41.23/-81.35&language=en) [<img src="https://user-images.githubusercontent.com/1231218/227757332-7dddd88d-d263-4002-ad31-002796208d0d.png" width="400" alt="Georgian">](https://zelonewolf.github.io/openstreetmap-americana/#map=5/41.23/-81.35&language=ka)
_English versus Georgian_

In practice, the Georgian alphabet is unicameral, but capital letters are used for decorative purposes, such as the reason why we’re uppercasing these labels.

**Comment by 1ec5** [comment]
The capital letters are located in the Georgian Extended block, 0x1C90–0x1CBF. The downloaded Noto Sans Georgian Regular font does contain glyphs for each of these codepoints, but the range 7312–7359 needs to be associated with Georgian so that the generated Americana-Regular font will contain these codepoints:

https://github.com/ZeLonewolf/openstreetmap-americana/blob/e26d76a1af1248b7380d93e4c0c9f9d3c8082aa7/scripts/fonts.json#L84-L87

I’ve tried adding this range and doing a clean rebuild, but the uppercase letters still aren’t showing up.

**Comment by 1ec5** [comment]
This issue doesn’t reproduce in 22615bea6a4037637b5891e531cfa0b7006f6fee, which was right before #801 and used the OpenHistorical fontstack:

<img src="https://user-images.githubusercontent.com/1231218/227760638-6b288232-fa3c-40b6-8f17-2854803b892e.png" width="400" alt="OpenHistorical">

**Comment by ZeLonewolf** [comment]
Initial debugging shows that the issue manifests when text-transform: uppercase is used.

![image](https://user-images.githubusercontent.com/3254090/227794561-adf4bd2d-06ba-40c3-8a0c-f02cba811f80.png)

**Comment by 1ec5** [comment]
Yes, because the font PBFs don’t contain glyphs for the uppercase letters.

**Comment by ZeLonewolf** [comment]
Noto Sans Georgian does seem to have the characters:

![image](https://user-images.githubusercontent.com/3254090/227794920-aec3aa28-0fad-4751-b2e1-17558b59aa9f.png)

I'm pulling in the ranges:

[4256, 4351],
[11520, 11567]

Which should correspond to the regular and supplemental Georgian language blocks

**Comment by ZeLonewolf** [comment]
[FontDrop](https://fontdrop.info/) reports Georgian language support and draws Georgian capital letter characters
![image](https://user-images.githubusercontent.com/3254090/227795278-d408ebe9-0bf1-45ac-83f1-1a4072594c38.png)

**Comment by ZeLonewolf** [comment]
Oh I just saw your note about the missing range.

**Comment by 1ec5** [comment]
Doh, adding the range didn’t work for me locally because the style was pointed to the production glyphs.
