### ISSUE TITLE
Branch Motorways in Italy

### ISSUE THREAD

**Issue by ZeLonewolf** [ZeLonewolf/openstreetmap-americana#85]
Branch motorways in Italy are numbered based on the two motorways that they connect:

![image](https://user-images.githubusercontent.com/3254090/150456656-b24bc9e8-e8f2-4ebd-a7cb-d099edc56510.png)

The shields on these roads use a stacked configuration as follows:

![image](https://user-images.githubusercontent.com/3254090/150456767-6a16f4f8-71f1-4eaf-a150-3086ce34bbfc.png)

In the database, these route relations use the form `ref=A7/A26`.  These will need to be parsed and split by the slash in a vertical configuration.

**Comment by Mashin6** [comment]
Would '/' --> '\n' replacement work or are special characters not supported for text rendering?

**Comment by ZeLonewolf** [comment]
Javascript canvas doesn't have multi line support, so that wouldn't work out of the box.

**Comment by claysmalley** [comment]
Stacked refs tracked in #366.
