### ISSUE TITLE
Wide shields showing up for 1 & 2 digit shields at DPR 1 

### ISSUE THREAD

**Issue by zekefarwell** [ZeLonewolf/openstreetmap-americana#86]
When device pixel ratio (DPR) is > 1, standard width shields are used for 1 and 2 digit route numbers and the wide shield is used for 3 digit route numbers.  Here is DPR 2 for example:
![DPR2](https://user-images.githubusercontent.com/281482/150576770-251d9916-8ea3-4724-a092-dbbe37028308.png)

The same area at DPR 1 shows wide shields used for 1 and 2 digit route numbers which should be using the regular width shield:
![DPR1](https://user-images.githubusercontent.com/281482/150576773-d97f4e42-fab6-4205-8c49-b999b9547432.png)

**Comment by jleedev** [comment]
Safari appears to still be consistently choosing the wrong shield (both 1x and 2x):

![Screen Shot 2022-06-16 at 11 45 50](https://user-images.githubusercontent.com/23022/174112091-25a5bdbd-723d-4f6f-a248-abe94c4c1bcd.png)
![Screen Shot 2022-06-16 at 11 46 19](https://user-images.githubusercontent.com/23022/174112096-6ed9fcc0-ec3d-4acb-8055-2e4913419d1f.png)
