### ISSUE TITLE
Make shield generator compatible with ES2019

### ISSUE THREAD

**Issue by 1ec5** [ZeLonewolf/openstreetmap-americana#890]
The maplibre-shield-generator library is built for `ESNext` (which would be ECMAScript 2023 at the time of writing):

https://github.com/ZeLonewolf/openstreetmap-americana/blob/4ba85f903250b1747688d9729f0059d95dba0288/tsconfig.json#L3-L4

This build setting is so bleeding-edge that it could apparently open the door to [code that no released browser can parse at all](https://github.com/evanw/esbuild/releases/tag/v0.18.7) if we upgrade esbuild too soon. A more immediate issue is that even some of the recent ECMAScript versions would be incompatible with websites that might be interested in adopting the library.

For example, the OpenStreetMap Wiki recently integrated maplibre-shield-generator, loading it dynamically on [pages that embed OSM Americana](https://wiki.openstreetmap.org/wiki/Special:PermanentLink/2551555#New_templates_for_vector_maps). This makes it the first “core” OSM website to adopt client-side-rendered vector maps. Unfortunately, the mere presence of this library breaks all JavaScript for users of browsers such as Firefox 91 ESR (released in 2021). Since the library is compiled as a module, it becomes necessary to [dynamically import](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/import) it from another script, which leads to the following error:

> SyntaxError: import declarations may only appear at top level of a module

The OSM Wiki currently runs [MediaWiki 1.39](https://wiki.openstreetmap.org/wiki/Special:Version), which [provides “grade-A” support](https://www.mediawiki.org/wiki/Special:PermanentLink/6012138#Browser_support_matrix) for “modern browsers”, defined as the last three years of Chromium releases, two LTS releases of Firefox, and Safari 11 (2018). Scripts are loaded by [ResourceLoader](https://www.mediawiki.org/wiki/ResourceLoader/Core_modules#mw.loader.load), a built-in bundler and minifier. ResourceLoader bundles maplibre-shield-generator with other site scripts, such as the one that powers taginfo statistics and taglists.

The OSM Wiki isn’t required to support every configuration that MediaWiki does, but Americana is currently embedded on so few pages that limiting browser support based on it would be quite a tail-wagging-the-dog situation. I can also imagine other websites besides wikis facing similar hurdles from how an ESNext-targeted library might interact with other dependencies.

It would make a lot of sense for maplibre-shield-generator, as a MapLibre GL JS plugin, to support the same browsers that MapLibre GL JS does. As far as I know, MapLibre GL JS lacks a clearly articulated browser compatibility policy, but its build system is configured to target [ES2019](https://github.com/maplibre/maplibre-gl-js/blob/30c0e1d47f019f159edc6c6ef8c5e068f14a696e/tsconfig.json#L17).

**Comment by 1ec5** [comment]
If I set `target` to `es2021` and `module` to `es2020`, running `npm run build:code` produces this error:

```
/Users/mxn/Documents/Code/hub/openstreetmap-americana/node_modules/ts-node/src/index.ts:859
    return new TSError(diagnosticText, diagnosticCodes, diagnostics);
           ^
TSError: ⨯ Unable to compile TypeScript:
scripts/build.ts:86:1 - error TS1378: Top-level 'await' expressions are only allowed when the 'module' option is set to 'es2022', 'esnext', 'system', 'node16', or 'nodenext', and the 'target' option is set to 'es2017' or higher.

86 await build();
   ~~~~~

    at createTSError (/Users/mxn/Documents/Code/hub/openstreetmap-americana/node_modules/ts-node/src/index.ts:859:12)
    at reportTSError (/Users/mxn/Documents/Code/hub/openstreetmap-americana/node_modules/ts-node/src/index.ts:863:19)
    at getOutput (/Users/mxn/Documents/Code/hub/openstreetmap-americana/node_modules/ts-node/src/index.ts:1077:36)
    at Object.compile (/Users/mxn/Documents/Code/hub/openstreetmap-americana/node_modules/ts-node/src/index.ts:1433:41)
    at transformSource (/Users/mxn/Documents/Code/hub/openstreetmap-americana/node_modules/ts-node/src/esm.ts:400:37)
    at /Users/mxn/Documents/Code/hub/openstreetmap-americana/node_modules/ts-node/src/esm.ts:278:53
    at async addShortCircuitFlag (/Users/mxn/Documents/Code/hub/openstreetmap-americana/node_modules/ts-node/src/esm.ts:409:15)
    at async nextLoad (node:internal/modules/esm/loader:161:22)
    at async ESMLoader.load (node:internal/modules/esm/loader:594:20)
    at async ESMLoader.moduleProvider (node:internal/modules/esm/loader:446:11) {
  diagnosticCodes: [ 1378 ]
}
```

Would it be possible to compile the shield library with more lenient options than the rest of the Americana package, since it needs wider distribution? Or would that be dependent on moving the shield library to a separate repository (#889)?

**Comment by ZeLonewolf** [comment]
This error is coming from the build script itself, not from any of the package code.  Though there might be other issues once we start peeling this back.  Is there a particular ES target that would make sense to code for that isn't too old but isn't too new?

**Comment by ZeLonewolf** [comment]
> refactoring the build scripts to avoid too-new ECMAScript syntax
This seems like a quick win and desirable, whether or not the shield library is split out.

**Comment by 1ec5** [comment]
>> Since the library is compiled as a module, it becomes necessary to [dynamically import](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/import) it from another script, which leads to the following error:
> 
>> SyntaxError: import declarations may only appear at top level of a module

#900 decouples the shield library’s build settings from the main package’s build settings. Any expanded compatibility for the shield library will promote its reuse. However, the mere fact that it’s compiled as a module precludes its standalone use on sites that require compatibility with slightly older browsers. Even for newer browsers, it requires developers to include the script using newer, unfamiliar syntax (`type="module"`) that may not be supported by various CMSes and sanitizers.

**Comment by 1ec5** [comment]
#901 repackages the shield library as an ordinary script. #900 is still worthwhile in order to avoid using too-new syntax.
