### ISSUE TITLE
Add shield for Ohio River Scenic Byway

### ISSUE THREAD

**Issue by 1ec5** [ZeLonewolf/openstreetmap-americana#892]
The Ohio River Scenic Byway is a National Scenic Byway that crosses Ohio, Indiana, and Illinois. Its [route superrelation](https://www.openstreetmap.org/relation/16058238) is tagged `US:ORSB`. It currently only has [a half-completed route relation in Ohio](https://www.openstreetmap.org/relation/12238016).

All three states post the same shield, depicting a blue Ohio River with green hills and a white sky in the background and a black silhouette of a typical river town skyline in the foreground. This shield is most likely copyrighted, but it should be possible to design a much simpler, copyright-free icon reminiscent of this shield.

[![West Indiana State Road 56 and Ohio River Scenic Byway directional assembly](https://upload.wikimedia.org/wikipedia/commons/thumb/8/86/Ohio_SB_19-10-16_403.jpg/576px-Ohio_SB_19-10-16_403.jpg)](https://commons.wikimedia.org/wiki/File:Ohio_SB_19-10-16_403.jpg)

**Comment by ZeLonewolf** [comment]
Why is this tagged planetiler?

**Comment by 1ec5** [comment]
The route relation lacked a [`network`](https://www.openstreetmap.org/changeset/138155743) tag until [changeset 138,155,743](https://www.openstreetmap.org/changeset/138155743) today.
