### ISSUE TITLE
Get translations of nature reserve names from Wikidata

### ISSUE THREAD

**Issue by verhovsky** [ZeLonewolf/openstreetmap-americana#939]
The names of national/state parks are named in the language I've selected for OSM Americana only if the corresponding translated name exists in the OSM data, but for the most part OSM seems to expect you to get the translation from Wikidata, so when you zoom around the Americana map (on non- English-speaking countries) you see a lot of untranslated text because of all the parks. For example this park in Spain has no `name:en` tag in OSM but has an English name on the linked Wikidata item

https://zelonewolf.github.io/openstreetmap-americana/#map=9.54/42.6383/0.5376&language=en

https://www.openstreetmap.org/way/49134015

https://www.wikidata.org/wiki/Q3112046

**Comment by 1ec5** [comment]
Unfortunately, the OpenMapTiles schema doesn’t include Wikidata translations of park names or, for that matter, OSM translations in any language other than German and English. This is reflected in Planetiler’s OpenMapTiles compatibility profile that we’re using:

https://github.com/openmaptiles/planetiler-openmaptiles/blob/613d0a8f7eba34ef75ac202538843f78b0e28284/src/main/java/org/openmaptiles/layers/Park.java#L116

**Comment by verhovsky** [comment]
I think this got fixed. The park I linked to originally now has an English translation, despite not having one in OSM still.

**Comment by 1ec5** [comment]
You’re right, the fallbacks do seem to work now, even though the code I pointed out hasn’t changed. I have no idea how it works, but I’m glad it does.
