### ISSUE TITLE
Missing CORS-headers for `https://tile.ourmap.us/data/v3.json`

### ISSUE THREAD

**Issue by pietervdvn** [ZeLonewolf/openstreetmap-americana#961]
Hi,

The Americana style is included in MapComplete. 
It loads `https://tile.ourmap.us/data/v3.json`, but that doesn't serve 'CORS'-headers, which breaks using it in a third-party website. Disabling the CORS-checks with a plugin fixes the issue.

Would it be possible to add CORS-headers?

You can test this at https://dev.mapcomplete.org, pick any theme and select the 'background layer selection' button (stacked squares) at the bottom left

**Comment by ZeLonewolf** [comment]
Hi, currently https://mapcomplete.osm.be is on the CORS whitelist. Which domains do we need to add?

**Comment by pietervdvn** [comment]
MapComplete recently moved domains, from "mapcomplete.osm.be" to "mapcomplete.org". Can you update this please?

Note that some subdomains (`dev.mapcomplete.org` and `hosted.mapcomplete.org`) exist as well; but -if possible- whitelisting _all_ subdomains (`*.mapcomplete.org`) would be best.

**Comment by ZeLonewolf** [comment]
I've added mapcomplete.org and *.mapcomplete.org to the tile server's CORS white list.  Additionally, I disabled CORS entirely on the TileJSON and static elements of tile.ourmap.us.

**Comment by claysmalley** [comment]
I can't load Americana on localhost due to missing CORS headers. Is there a workaround for this?

**Comment by ZeLonewolf** [comment]
@claysmalley are you getting CORS issues on the tiles or the TileJSON?

**Comment by claysmalley** [comment]
Here's the error message.
```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://tile.ourmap.us/data/v3.json. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).
```

**Comment by ZeLonewolf** [comment]
I just restored the whitelist CORS policy on the TileJSON, which should fix the localhost issue.

**Comment by pietervdvn** [comment]
> I can't load Americana on localhost due to missing CORS headers. Is there a workaround for this?

With a browser plugin, one can disable CORS during the testing session. This allows to use the external API without them having 'localhost' or '127.0.0.1' enabled. For firefox, I'm using this one: https://addons.mozilla.org/en-US/firefox/addon/cors-everywhere/

**Comment by pietervdvn** [comment]
I can also confirm that the layer now works on MapComplete

Thanks for fixing this!
