### ISSUE TITLE
Albany County Wyoming Shields

### ISSUE THREAD

**Issue by the-spui-ninja** [ZeLonewolf/openstreetmap-americana#968]
County roads in Albany County, WY (proposed network US:WY:Albany) are signed with a mix of either the standard US CR pentagon or on the streetblades themselves (green square with white border). There doesn't appear to be one dominant way over the other from my knowledge (lived in Laramie for two years). I would recommend using the pentagons to display all of them, but if you want me to break them out into two separate networks I can do that as well (US:WY:Albany1 and US:WY:Albany2 for example).

**Comment by claysmalley** [comment]
Many counties around the country have inconsistent signage. I don't think it's worth it to maintain two separate `network` values for that purpose. `US:WY:Albany` follows accepted tagging conventions, and the standard pentagon seems fine.

**Comment by the-spui-ninja** [comment]
I'll start adding in that system then.
