### ISSUE TITLE
South Dakota "secondary" route shields

### ISSUE THREAD

**Issue by the-spui-ninja** [ZeLonewolf/openstreetmap-americana#970]
So South Dakota doesn't have an official secondary route system, but some minor highways (namely 251, 258, and 473 from my memory) are signed using a small white rectangle with a black outline. Is this worth splitting from the US:SD system (proposed network would be US:SD:Secondary if this moves forward)?

**Comment by claysmalley** [comment]
Yes, I would give these routes a different tag—`US:SD:Secondary` seems alright. We'll be happy to support these routes once a few of them are on the map.

**Comment by the-spui-ninja** [comment]
Will do. For the record, they look kind of like this:
![image](https://github.com/ZeLonewolf/openstreetmap-americana/assets/14971501/66c98727-3a7d-465c-a7ae-736ede1b258e)
