### ISSUE TITLE
South Dakota Custer State Park shields

### ISSUE THREAD

**Issue by the-spui-ninja** [ZeLonewolf/openstreetmap-americana#971]
Custer State Park in South Dakota has a numbered route network (https://www.custercountysd.com/wp-content/uploads/2022/12/CusterCountyAtlas2022.pdf, scroll to the "Road Numbers" page on page 60 of the pdf). These are signed with a version of the Custer State Park logo (https://www.google.com/search?sca_esv=575375586&rlz=1C1CHBF_enUS770US770&q=custer+state+park+logo&tbm=isch&source=lnms&sa=X&ved=2ahUKEwjF9Yj4o4aCAxUVMUQIHe9yCa4Q0pQJegQICxAB&biw=1366&bih=619&dpr=1#imgrc=mxPW_lATeaVlWM) with the number either in the middle of the bison or below the logo. This would be US:SD:CSP. I'm not sure if the logo is copyrighted or not, which is kind of a stumbling block here.

**Comment by claysmalley** [comment]
Do any other state parks of South Dakota have their own numbered road system? If so, let's find a `network` value that can accommodate those as well. If not, `US:SD:CSP` is fine.

Simple geometry is uncopyrightable, though we'll probably need to try a few different bison outlines to make sure 3 digits can fit. 

Just making sure—the bison is brown and the text is white, right?

**Comment by the-spui-ninja** [comment]
To my knowledge, this is a Custer County peculiarity, they even gave Wind Cave National Park numbered routes (making SD one of two states with NPS numbered routes, the other being NJ).

Yes. Not sure if you want to add the "Custer State Park" text below the bison, as that might get over-complicated for a web map.

**Comment by claysmalley** [comment]
> To my knowledge, this is a Custer County peculiarity

If Custer County is responsible for assigning the numbers and putting up the signs, then it would be a subnetwork of Custer County roads: `network=US:SD:Custer:CSP`.

> Not sure if you want to add the "Custer State Park" text below the bison, as that might get over-complicated for a web map.

Indeed. Our goal with shields is to simplify the design to look good at icon size, while keeping it recognizable. Complicated text typically gets omitted in this process. In this case, I think a brown bison shape would be enough to remain recognizable while matching the design language of the other shields.

**Comment by the-spui-ninja** [comment]
> If Custer County is responsible for assigning the numbers and putting up the signs, then it would be a subnetwork of Custer County roads: `network=US:SD:Custer:CSP`.

So from my understanding, Parks maintains the roads and I believe SDDOT put up the most recent streetblades. The numbering scheme is the only thing that I think came from Custer County, though the roads are essentially the same quality as Custer County roads. I'm fine with either way of doing the network, but as a lifelong SD resident I'd lean towards SD:CSP since Custer County only added the numbers and does nothing else with the roads. Forest Service roads are in that Custer PDF as well, and they're not a subset of Custer County roads.

**Comment by 1ec5** [comment]
The arrangement kind of reminds me of how AASHTO assigns Interstate and U.S. Route numbers, hence `US:I` and `US:US`, but they have nothing else to do with the roads. (There’s `operator` for that.) Not a huge deal either way, but I find it interesting that a county can have influence up the administrative hierarchy too.

What should we do about the routes in Wind Cave National Park? There are already a handful of routes around the country tagged [`US:NPS`](https://www.openstreetmap.org/relation/16438854) for [standard NPS branding](https://wiki.aaroads.com/wiki/Pierce_Stocking_Scenic_Drive) or [`US:NPS:*`](https://www.openstreetmap.org/relation/3300032) for [one-off branding](https://wiki.aaroads.com/wiki/Natchez_Trace_Parkway). But as far as I know, all these routes owe their identities to the NPS rather than a local jurisdiction’s numbering or naming scheme.

**Comment by the-spui-ninja** [comment]
> Not a huge deal either way, but I find it interesting that a county can have influence up the administrative hierarchy too.

More than likely the Custer County Highway Department head at the time E911 was introduced was pushy about it and Parks didn't care enough to say no.

So the other two NPS numbered routes in New Jersey (602 and 615 in the Delaware Water Gap NRA) are currently under their associated county road relation. Those two are actually signed, while NPS 5 just has text on a wooden board and I haven't driven out to the 5/6 junction to see if there's a street blade with a shield there. 

I've changed my mind about the network tag, and I think that would work for a proposal for these. Since these park systems just seem to be extensions of the local county road numbering, how about `US:SD:Custer:CSP`, `US:SD:Custer:NPS`, `US:SD:Custer:CSP`, `US:NJ:Warren:NPS` and `US:NJ:Sussex:NPS`? Then the shields can be matched to each system.

**Comment by claysmalley** [comment]
> Since these park systems just seem to be extensions of the local county road numbering, how about `US:SD:Custer:CSP`, `US:SD:Custer:NPS`, `US:NJ:Warren:NPS` and `US:NJ:Sussex:NPS`? Then the shields can be matched to each system.

Go for it. Could you write up another issue for the NPS shields? We'd want to support those too, of course.
