### ISSUE TITLE
Weld County Colorado Shields

### ISSUE THREAD

**Issue by the-spui-ninja** [ZeLonewolf/openstreetmap-americana#988]
There are signed county routes in Weld County, CO (`US:CO:Weld`), and in an additional peculiarity, the Weld County Parkway (composed of part of CR 47 and CR 49) has its own design style (https://www.weld.gov/Government/Departments/Public-Works/Transportation-Planning/Access-Control-Plans/WCR-49-ACP, https://www.weld.gov/Government/Departments/Public-Works/Transportation-Planning/Access-Control-Plans/WCR-47-ACP, matches the field signage pretty closely) (`US:CO:Weld:WCP`).

**Comment by ZeLonewolf** [comment]
In case anyone encounters this in the future:

![image](https://github.com/ZeLonewolf/openstreetmap-americana/assets/3254090/18a9a90e-2fe6-41a3-aaf3-c1f6f0ff2716)

**Comment by ZeLonewolf** [comment]
It (a) looks garish and (b) accurately reflects how hideous that shield is.  But I would want to know what is actually shielded on the ground to decide what to display?  Also if there's two shield schemes in use, I'd advocate for using the newer one on the assumption that older shields will eventually be replaced.

**Comment by the-spui-ninja** [comment]
So the last time I was there (last December), the WCP uses the purple-and-green shields almost exclusively on the route itself. Other Weld County roads have been given pentagons at/near I-25, so there's not just street blade county roads in Weld. When I lived in that part of the country, CODOT was actively adding the pentagons where they didn't exist before.

**Comment by ZeLonewolf** [comment]
I did not find examples of this cruising Google Maps, so it sounds like the purple signs might be newer than the Google imagery.

I did encounter this in the media:

![image](https://github.com/ZeLonewolf/openstreetmap-americana/assets/3254090/4d194677-293b-4ff1-a38a-f3ebedbb1c42)
