### ISSUE TITLE
[Allowlisting request] Wikimedia Commons Android app

### ISSUE THREAD

**Issue by nicolas-raoul** [ZeLonewolf/openstreetmap-americana#989]
Hi Americana,

We (the open source Wikimedia Commons Android app) would love to rely on your map, if our purpose seems useful to you.

In our app, users see a map of Wikipedia articles missing a picture. They can then go take a picture, and upload to each article.
These pictures are often used by OSM contributors to understand the context and better map these places.

14k daily users, 800k monthly tile requests.
We currently use Mapbox, but that is starting to cost us money as we are now over the free tier, and we are all volunteers (the app is 100% run by volunteers, even though it has been accepted as an official Wikimedia app).
About the app: https://commons.wikimedia.org/wiki/Commons:Mobile_app

Here is our User-Agent: "Commons/<full version string> (https://mediawiki.org/wiki/Apps/Commons) Android/<short version string>"
I don't think we set a Referer, but we can set one if needed.
Note: We are not a website, but rather an Android app.

Does that sound doable? If you need more information, please do not hesitate to ask anything. :-)
![Screenshot_20231030-161141.png](https://github.com/ZeLonewolf/openstreetmap-americana/assets/99590/6f299349-1f15-471d-8d95-198ecc276aef)

**Comment by claysmalley** [comment]
Sorry for the late reply. I see that the underlying issue has been resolved [here](https://github.com/commons-app/apps-android-commons/issues/5372)—closing this issue.
